import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {aiContext} from '@/lib/ai/context';
import styles from '@/app/_components/humla-chat.module.css';
export const dynamic='force-dynamic';
const labels:Record<string,string>={description:'Beskrivning',kind:'Typ',amount:'Radbelopp',currency:'Valuta',occurred_on:'Artikeldatum / bokföringsdatum',vehicle_registration:'Fordon',project_reference:'Projekt',cost_center:'Kostnadsställe',account:'Konto',file_name:'Importfil',source_type:'Importkälla',status:'Status',created_at:'Importerad',registration_number:'Regnummer',object_type:'Typ',source_of_truth:'Källa',updated_at:'Senast uppdaterat',make:'Märke',model:'Modell',odometer:'Mätarställning',odometer_type:'Mätarenhet',reading_type:'Mätningstyp',reading_value:'Mätvärde',recorded_at:'Mätt vid',source_system:'Källa',quantity_liters:'Liter',source_amount:'Källbelopp',price_status:'Prisstatus',transaction_date:'Tankningsdatum',calculated_unit_price:'Pris per liter',order_number:'Order',title:'Rubrik',note:'Anteckning',quantity:'Mängd',unit_price:'À-pris'};
function Fields({data}:{data:Record<string,unknown>}){return <dl className={styles.fields}>{Object.entries(data).filter(([,v])=>v!==null&&v!==''&&v!==undefined).map(([k,v])=><div key={k}><dt>{labels[k]??k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>;}
export default async function EvidencePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{type?:string}>}){
 const c=await aiContext();if('error'in c){if(c.status===401)redirect('/kpi/login');return <main>{c.error}</main>;}const {id}=await params;const {type}=await searchParams;if(!/^[0-9a-f-]{36}$/i.test(id))notFound();
 let original:Record<string,unknown>={},facts:Record<string,unknown>={},importInfo:Record<string,unknown>={},title='Originalunderlag';
 if(type==='transaction'){const {data:r,error}=await c.db.from('kpi_import_rows').select('id,batch_id,row_number,data_kind,occurred_on,description,amount,currency,vehicle_registration,project_reference,cost_center,account,source_data,created_at').eq('tenant_id',c.tenantId).eq('id',id).eq('is_valid',true).maybeSingle();if(error||!r)notFound();const {data:b}=await c.db.from('kpi_import_batches').select('file_name,source_type,status,created_at').eq('tenant_id',c.tenantId).eq('id',r.batch_id).in('status',['completed','needs_review']).maybeSingle();if(!b)notFound();original=r.source_data??{};facts={description:r.description,kind:r.data_kind==='revenue'?'Intäkt':r.data_kind==='cost'?'Kostnad':r.data_kind,amount:r.amount,currency:r.currency,occurred_on:r.occurred_on,vehicle_registration:r.vehicle_registration,project_reference:r.project_reference,cost_center:r.cost_center,account:r.account};importInfo={...b,row_number:r.row_number};title=[original.Kundnamn,original.ArtikelKommentar??original.Artikelnamn??r.description].filter(Boolean).join(' · ');}
 else if(type==='object'){const {data:r,error}=await c.db.from('hub_objects').select('id,object_type,status,data,source_of_truth,updated_at').eq('tenant_id',c.tenantId).eq('id',id).not('object_type','in','(ExternalDriver,Person,Employee,FuelAccount)').maybeSingle();if(error||!r)notFound();const allowed=['registration_number','description','make','model','status','department','internal_ref','odometer','odometer_type','active','vehicle_type','asset_id','reading_type','reading_value','recorded_at','source_system','product_name','quantity_liters','quantity_unit','calculated_unit_price','price_status','source_amount','transaction_date','transaction_id','customer_number','order_number','title','note','project_reference','source_file','total','vehicle','planned_start','planned_end','date','amount','article_number','parent_order_number','quantity','unit_price'];original=Object.fromEntries(Object.entries(r.data??{}).filter(([k])=>allowed.includes(k)));if(original.asset_id){const {data:v}=await c.db.from('hub_objects').select('data').eq('tenant_id',c.tenantId).eq('id',String(original.asset_id)).eq('object_type','Vehicle').maybeSingle();if(v?.data?.registration_number)original.registration_number=v.data.registration_number;}facts={object_type:r.object_type,status:r.status,source_of_truth:r.source_of_truth,updated_at:r.updated_at};title=[original.registration_number,r.object_type].filter(Boolean).join(' · ');}
 else notFound();
 return <div className="kpi-app"><main className={styles.page}><Link href="/kpi/ai" prefetch={false} className={styles.back}>← Fråga Humla</Link><h1>{title}</h1><p>Underlaget läses direkt från Hubben med din aktuella behörighet. En importerad rad är inte automatiskt hela fakturan.</p><h2>Uppgifter i Hubben</h2><Fields data={facts}/><h2>Originalfält från källan</h2><Fields data={original}/>{Object.keys(importInfo).length>0&&<><h2>Importens ursprung</h2><Fields data={importInfo}/></>}</main></div>;
}
