"use client";
import {KpiAttendanceSettings} from '../../_components/kpi-attendance-settings';
import {useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
export default function Page(){
 const [secret,setSecret]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function save(){setBusy(true);setMessage("");try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error("Supabase-konfiguration saknas.");const s=createClient(url,key);const {data:{session}}=await s.auth.getSession();if(!session)throw new Error("Du behöver vara inloggad i Humla.");const r=await fetch(url+"/functions/v1/hub-credential-config",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token,apikey:key},body:JSON.stringify({client_id:"isv_humla-hub",client_secret:secret})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Kunde inte spara.");setSecret("");setMessage("Credentials sparade säkert i Humla Hub.");}catch(e){setMessage(e instanceof Error?e.message:"Kunde inte spara.");}finally{setBusy(false);}}
 return <><Link href="/integrationer" className="backlink">← Integrationer</Link><header className="topbar"><div><span className="eyebrow">TID & PERSONAL</span><h1>TransPA</h1><p>Visma TransPA Public API · tid och löneexport via Humla Hub.</p></div></header><section className="section"><span className="label">SÄKER KONFIGURATION</span><h2>Credentials</h2><p className="mutedcopy">Client Secret skickas direkt till Humla Hubs backend och lagras krypterat i Supabase Vault. Värdet visas inte igen.</p><div className="credentialForm"><label>Application ID<input value="isv_humla-hub" disabled /></label><label>Client Secret<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Klistra in hemligheten från Visma" /></label><button type="button" disabled={busy||secret.length<8} onClick={()=>void save()}>{busy?"Sparar…":"Spara säkert"}</button>{message&&<p>{message}</p>}</div></section><section className="section"><span className="label">STATUS</span><h2>TransPA Public API</h2><p className="mutedcopy">Arbetstidsrapporter hämtas via Hubben. Löneexportens tidsrader behövs för att skilja sjukfrånvaro, VAB och semester. En prenumeration finns hos TransPA, men dess leverans till Humla är ännu inte verifierad med en mottagen export.</p><KpiAttendanceSettings/></section></>;
}
