'use client';
import {useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {assetClasses,type Asset,type AssetTcoReport,type ComparisonStats} from '@/lib/hub/asset-tco';
import styles from './asset-tco-workspace.module.css';
import {marketSources,type MarketDiscovery} from '@/lib/hub/market-discovery';
import {MarketDiscoveryPanel} from './market-discovery';
import {MarketSearchTrial} from './market-search-trial';
import {CarMarketSearch} from './car-market-search';
import {AssetRegisterEvidence} from './asset-register-evidence';
import type {AssetRegisterReport} from '@/lib/hub/asset-register';
const number=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0});
const decimals=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:2});
const money=(n:number|null|undefined)=>n==null?'Saknat underlag':`${number.format(n)} kr`;
const date=(s:string|null)=>s?new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm'}).format(new Date(s)):'Datum saknas';
const labels:Record<string,string>={fuel:'Bränsle',service_repair:'Service & reparation',fixed:'Fasta kostnader'};
function Stats({value,label}:{value:ComparisonStats|null;label:string}){return <div className={styles.stat}><h3>{label}</h3>{value?<><strong>{money(value.median)} median</strong><p>{money(value.mean)} medelpris</p><p>{value.n} jämförelser · {value.sources} källor</p><p>{money(value.low)} – {money(value.high)}</p></>:<p>Saknar jämförbart underlag</p>}</div>;}
export function AssetTcoWorkspace({report,register,selectedId,today,discovery}:{report:AssetTcoReport;register:AssetRegisterReport|null;selectedId:string|null;today:string;discovery:MarketDiscovery|null}){
 const acquisitions=new Map((register?.rows??[]).filter(r=>r.asset_id&&r.link_kind==='asset'&&!r.sold).map(r=>[r.asset_id,r.evidence]));
 const params=useSearchParams();function assetHref(id:string|null){const p=new URLSearchParams(params);p.set('tab','tco');p.set('date',report.as_of);if(id)p.set('asset',id);else p.delete('asset');return `/kpi/fordon?${p}`;}
 const router=useRouter();const [search,setSearch]=useState('');const [kind,setKind]=useState('all');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const selected=report.assets.find(a=>a.id===selectedId);const editable=report.can_manage&&report.as_of===today;
 const assets=report.assets.filter(a=>(kind==='all'||a.ownership?.asset_class===kind||kind==='missing'&&!a.ownership)&&[a.registration,a.make,a.model,a.description,a.department].join(' ').toLocaleLowerCase('sv-SE').includes(search.toLocaleLowerCase('sv-SE')));
 async function save(asset:string,action:string,data:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/hub/asset-tco',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:asset,action,data})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage('Sparat i Hubben.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara.');}finally{setBusy(false);}}
 function submit(e:React.FormEvent<HTMLFormElement>,asset:Asset,action:string){e.preventDefault();const form=new FormData(e.currentTarget);const data:Record<string,unknown>=Object.fromEntries(form.entries());if(action==='comparable'){data.comparable_confirmed=form.get('comparable_confirmed')==='on';data.sale_confirmed=form.get('sale_confirmed')==='on';}void save(asset.id,action,data);}
 return <>
 {register&&<AssetRegisterEvidence report={register} selectedId={selectedId}/>}
 <section className="panel"><div className="panel-head"><div><span className="section-kicker">Fordonsansvarig</span><h2>Ägandekostnad och värde</h2></div><span className={styles.badge}>Personbilar · Lastbilar · Släp · Maskiner</span></div><p>Fordonsuppgifter och registrerad mätarhistorik hämtas från Fordonskontrollen via Hubben. Inköpsuppgifter och jämförelsepriser kompletteras här.</p><form className={styles.filters}><input type="hidden" name="tab" value="tco"/>{['fiscal_year','months','department'].map(k=>params.get(k)&&<input type="hidden" key={k} name={k} value={params.get(k)!}/>)}<label>Värde och kostnader till datum<input type="date" name="date" max={today} defaultValue={report.as_of} required/></label>{selectedId&&<input type="hidden" name="asset" value={selectedId}/>}<button>Visa</button></form><p className={styles.muted}>Kostnadsunderlag synkat {report.sync_at?date(report.sync_at):'inte tillgängligt'}. TCO visas som preliminär summa av tillgängligt underlag; komplett kostnadstäckning är inte verifierad.</p></section>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}
 {!selectedId?<><section className="panel"><div className={styles.filters}><label>Sök fordon<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Regnummer, modell eller avdelning"/></label><label>Jämförelsetyp<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Alla</option>{Object.entries(assetClasses).map(([value,label])=><option key={value} value={value}>{label}</option>)}<option value="missing">Saknar inköpsuppgifter</option></select></label></div><p>{assets.length} fordon och maskiner · klicka för uppgifter och underlag.</p><div className="table-wrap"><table><thead><tr><th>Fordon</th><th>Modell / avdelning</th><th>Mätarställning</th><th>Inköpspris</th><th>Planerat värde</th><th>Senaste värdering</th><th>TCO · preliminär</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td><Link prefetch={false} href={assetHref(a.id)}>{a.registration||a.description||'Öppna fordon'}</Link></td><td>{[a.make,a.model].filter(Boolean).join(' ')||a.description||'Modell saknas'}<small className={styles.block}>{a.department||a.vehicle_type||'Typ saknas'}</small></td><td>{a.current_meter==null?'Mätning saknas':`${number.format(a.current_meter)} ${a.ownership?.meter_type==='engine_hours'||a.source_meter_type==='K_OT_HOURS'?'h':'km'}`}<small className={styles.block}>{a.meter_date?date(a.meter_date):''}</small></td><td>{money(a.ownership?.purchase_cost??acquisitions.get(a.id)?.purchase_cost)}{!a.ownership&&acquisitions.has(a.id)&&<small className={styles.block}>Register · momsgrund ej fastställd</small>}</td><td>{money(a.planned_value)}</td><td>{money(a.market_value)}<small className={styles.block}>{a.market_date??''}</small></td><td>{money(a.tco)}</td></tr>)}</tbody></table></div></section></>:selected?<>
 <Link href={assetHref(null)} prefetch={false}>← Alla fordon och maskiner</Link>
 {discovery&&<MarketDiscoveryPanel plan={discovery}/>}
 <MarketSearchTrial key={selected.id} assetId={selected.id} canManage={report.can_manage}/>
 <CarMarketSearch key={`car-${selected.id}`} asset={selected} canManage={report.can_manage}/>
 <section className="panel"><h2>{selected.registration||selected.description} · {[selected.make,selected.model].filter(Boolean).join(' ')}</h2><p>{selected.description} · {selected.department||selected.vehicle_type||'Typ saknas'}</p><p>{selected.current_meter==null?'Mätarhistorik saknas':`${number.format(selected.current_meter)} ${selected.ownership?.meter_type==='engine_hours'||selected.source_meter_type==='K_OT_HOURS'?'drifttimmar':'km'} registrerat ${date(selected.meter_date)}`}</p></section>
 <div className={styles.cards}><div className={styles.stat}><h3>Planerad värdeminskning</h3><strong>{money(selected.depreciation)}</strong><p>{money(selected.monthly_depreciation)} / månad</p></div><div className={styles.stat}><h3>Drift och fasta kostnader</h3><strong>{money(selected.operating_cost)}</strong><p>{selected.ownership?'Från inköpsdatum till valt datum':'Tillgänglig kostnadshistorik till valt datum'}</p></div><div className={styles.stat}><h3>TCO · preliminär</h3><strong>{money(selected.tco)}</strong><p>{selected.tco_per_unit==null?'Saknar jämförbar användning':`${decimals.format(selected.tco_per_unit)} kr / ${selected.ownership?.meter_type==='engine_hours'?'drifttimme':'mil'}`}</p></div></div>
 <section className="panel"><h2>Så räknas ägandekostnaden</h2><p>Planerad värdeminskning = (inköpspris − restvärde) fördelat över innehavstiden. TCO = värdeminskning + importerade kostnader för bränsle, service/reparation och fasta kostnader. Befintliga avskrivningsposter och personallöner läggs inte till.</p><p>{selected.ownership?`Inköpspris ${money(selected.ownership.purchase_cost)} − beräknat värde ${money(selected.planned_value)} + drift ${money(selected.operating_cost)} = ${money(selected.tco)}.`:'Bekräfta momsgrund, framtida restvärde och innehavsplan för att beräkna TCO. Registeruppgifterna ovan är källunderlag, inte en komplett TCO-profil.'}</p>{selected.ownership?.price_basis==='gross'&&<p>Inköpsuppgifterna anges inklusive moms. TCO kombineras först när kostnader och inköp har samma prisgrund; KPI-kostnaderna är exklusive moms.</p>}<p>Poster märkta leasing, amortering eller avskrivning ingår inte i fasta TCO-kostnader för ett inköpt fordon. Kontrollera övriga finansieringsposter i underlaget. Gemensamma kostnader som saknar entydig fordonskoppling ingår inte.</p>{Boolean(selected.pending_cost_rows)&&<p>{selected.pending_cost_rows} övriga kostnadsrader behöver bedömas och ingår inte i TCO.</p>}<p>Senaste kostnadsdatum: {selected.last_cost_date??'saknas'}. Kostnad per mil/timme använder skillnaden mellan mätarställningen vid inköp och senaste registrerade mätning. Om mätningen är äldre än kostnaderna är jämförelsen preliminär.</p></section>
 <section className="panel"><h2>Inköp och innehav</h2>{editable?<form key={`${selected.id}-${selected.ownership?.revision??0}`} className={styles.form} onSubmit={e=>submit(e,selected,'ownership')}><label>Jämförelsetyp<select name="asset_class" defaultValue={selected.ownership?.asset_class??'other'}>{Object.entries(assetClasses).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Inköpsdatum<input name="purchase_date" type="date" required max={today} defaultValue={selected.ownership?.purchase_date??''}/></label><label>Inköpskostnad, kr<input name="purchase_cost" type="number" min="0" step="0.01" required defaultValue={selected.ownership?.purchase_cost??''}/></label><label>Beräknat restvärde, kr<input name="residual_value" type="number" min="0" step="0.01" required defaultValue={selected.ownership?.residual_value??''}/></label><label>Innehavstid, månader<input name="holding_months" type="number" min="1" max="600" required defaultValue={selected.ownership?.holding_months??60}/></label><label>Prisgrund<select name="price_basis" defaultValue={selected.ownership?.price_basis??'net'}><option value="net">Exklusive moms</option><option value="gross">Inklusive moms</option></select></label><label>Mätartyp<select name="meter_type" defaultValue={selected.ownership?.meter_type??(selected.source_meter_type==='K_OT_HOURS'?'engine_hours':selected.vehicle_type==='Släpvagn'?'none':'odometer_km')}><option value="odometer_km">Kilometer</option><option value="engine_hours">Drifttimmar</option><option value="none">Ingen mätare / släp</option></select></label><label>Mätarställning vid inköp, km eller h<input name="purchase_meter" type="number" min="0" step="0.01" defaultValue={selected.ownership?.purchase_meter??''}/></label><label>Årsmodell<input name="model_year" type="number" min="1900" max="2100" defaultValue={selected.ownership?.model_year??''}/></label><label>Variant, axlar och påbyggnad<input name="variant" maxLength={300} defaultValue={selected.ownership?.variant??''} placeholder="Exempel: 6×2, kran och lastväxlare"/></label><label className={styles.wide}>Anteckning<textarea name="notes" maxLength={2000} defaultValue={selected.ownership?.notes??''}/></label><button disabled={busy}>Spara inköpsuppgifter</button></form>:<p>{selected.ownership?`${money(selected.ownership.purchase_cost)} · ${selected.ownership.purchase_date} · ${selected.ownership.holding_months} månader`:'Inköpsuppgifter saknas.'}{!report.can_manage?' Behörighet att hantera fordon krävs för ändringar.':report.as_of!==today?' Välj dagens datum för att registrera uppgifter.':''}</p>}</section>
 <section className="panel"><h2>Marknadsvärde och jämförelser</h2><p>Senaste sparade värdering: <strong>{money(selected.market_value)}</strong> · {selected.market_date??'datum saknas'} · {selected.valuation_source??'källa saknas'}. Marknadsvärdet visas separat från planerat värde och bokförda avskrivningar.</p><div className={styles.cards}><Stats value={selected.sold_stats} label="Bekräftade försäljningar"/><Stats value={selected.asking_stats} label="Annonspriser"/></div><p>Motorn använder bekräftat jämförbara objekt från de senaste 180 dagarna, samma prisgrund och högst två års skillnad i årsmodell. Miltal/drifttimmar ska ligga inom 30 % eller 20 000 km / 1 000 h. För släp utan mätare jämförs årsmodell och det utförande du har bekräftat.</p><p>Minst tre objekt krävs för ett förslag. Försäljningspriser prioriteras när minst tre finns; annars används annonspriser. Ingen schablonjustering av priset görs för miltal eller årsmodell.</p>{selected.estimate&&<p><strong>Motorförslag: {money(selected.estimate.median)}</strong> · {selected.estimate.basis==='sold'?'bekräftade försäljningar':'begärda annonspriser'} · {selected.estimate.n} objekt.</p>}{editable&&selected.estimate&&<button disabled={busy} onClick={()=>save(selected.id,'accept_estimate',{})}>Spara motorförslaget som värdering</button>}
 <details><summary>Jämförelseunderlag ({report.comparables.length})</summary><div className="table-wrap"><table><thead><tr><th>Källa / objekt</th><th>Datum</th><th>Pris</th><th>Typ</th><th>Årsmodell / mätare</th><th>Kontroll</th>{editable&&<th>Åtgärd</th>}</tr></thead><tbody>{report.comparables.map(c=><tr key={c.id}><td><a href={c.url} target="_blank" rel="noopener noreferrer">{c.source} · {c.title}</a></td><td>{c.observed_on}</td><td>{money(c.price)}<small className={styles.block}>{c.price_basis==='net'?'exkl. moms':'inkl. moms'}</small></td><td>{c.price_type==='sold'?'Försäljningspris':'Annonspris'}</td><td>{c.model_year} · {c.meter==null?'Ingen mätare':number.format(c.meter)}</td><td>{c.comparable_confirmed?'Jämförbarhet bekräftad':'Ej bekräftat'}{c.price_type==='sold'&&!c.sale_confirmed?' · försäljning ej bekräftad':''}</td>{editable&&<td><button className="secondary" disabled={busy} onClick={()=>save(selected.id,'remove_comparable',{id:c.id})}>Ta bort</button></td>}</tr>)}</tbody></table></div></details>
 {editable&&<details><summary>Lägg till jämförelseobjekt</summary><form className={styles.form} onSubmit={e=>submit(e,selected,'comparable')}><label>Källa<select name="source">{marketSources.map(s=><option key={s.name}>{s.name}</option>)}<option>Bilpriser</option><option>Blocket</option><option value="Other">Annan källa</option></select></label><label>Annons / objektnamn<input name="title" required maxLength={300}/></label><label className={styles.wide}>Länk till underlaget<input name="url" type="url" pattern="https://.*" required maxLength={2000}/></label><label className={styles.wide}>Gemensam objektidentitet, om samma objekt finns på flera sajter<input name="listing_identity" maxLength={200} placeholder="Regnummer, chassinummer eller annan säker objektreferens"/></label><label>Pris, kr (utan köparavgift)<input name="price" type="number" required min="0.01" step="0.01"/></label><label>Prisgrund<select name="price_basis" defaultValue={selected.ownership?.price_basis??'net'}><option value="net">Exklusive moms</option><option value="gross">Inklusive moms</option></select></label><label>Pristyp<select name="price_type"><option value="asking">Begärt annonspris</option><option value="sold">Bekräftat försäljningspris</option></select></label><label>Prisdatum<input name="observed_on" type="date" required max={today} defaultValue={today}/></label><label>Årsmodell<input name="model_year" type="number" required min="1900" max="2100"/></label><label>Mätarställning, km eller h<input name="meter" type="number" min="0" step="0.01"/></label><label className={styles.wide}>Skick, utrustning och prisunderlag<textarea name="notes" maxLength={2000}/></label><label className={styles.check}><input name="comparable_confirmed" type="checkbox"/>Jag har kontrollerat modell, variant, utrustning och skick mot vårt fordon.</label><label className={styles.check}><input name="sale_confirmed" type="checkbox"/>Försäljningen är bekräftad. Priset är inte bara ett högsta bud.</label><button disabled={busy}>Spara jämförelseobjekt</button></form></details>}
 {editable&&<details><summary>Registrera egen värdering</summary><form className={styles.form} onSubmit={e=>submit(e,selected,'valuation')}><label>Värderingsdatum<input name="valued_on" type="date" required max={today} defaultValue={today}/></label><label>Värde, kr<input name="amount" type="number" min="0" step="0.01" required/></label><label>Källa<input name="source" required maxLength={300} placeholder="Värdering från handlare"/></label><label>Kommentar<input name="notes" maxLength={2000}/></label><button disabled={busy||!selected.ownership}>Spara värdering</button></form></details>}
 <details><summary>Värderingshistorik ({report.valuations.length})</summary><table><thead><tr><th>Datum</th><th>Värde</th><th>Källa</th><th>Mätarställning vid registrering</th></tr></thead><tbody>{report.valuations.map(v=><tr key={v.id}><td>{v.valued_on}</td><td>{money(v.amount)}</td><td>{v.source}</td><td>{v.meter==null?'Saknas':number.format(v.meter)} · {v.meter_recorded_at?date(v.meter_recorded_at):''}</td></tr>)}</tbody></table></details></section>
 <section className="panel"><h2>Kostnadsunderlag från Hubben</h2><div className={styles.cards}>{['fuel','service_repair','fixed'].map(k=><div className={styles.stat} key={k}><h3>{labels[k]}</h3><strong>{money(selected[k as 'fuel'|'service_repair'|'fixed'])}</strong></div>)}</div><details><summary>Visa ingående kostnadsrader ({selected.cost_evidence.length})</summary><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Källa</th><th>Kategori</th><th>Beskrivning</th><th>Konto</th><th>Belopp</th></tr></thead><tbody>{selected.cost_evidence.map((c,i)=><tr key={`${c.id}-${i}`}><td>{c.date}</td><td>{c.source}</td><td>{labels[c.category]??c.category}</td><td>{c.description}</td><td>{c.account??'–'}</td><td>{money(c.amount)}</td></tr>)}</tbody></table></div></details></section>
 </>:<p>Fordonet kunde inte hittas.</p>}
 <section className="panel"><h2>Marknadskällor och status</h2><p>{marketSources.map(s=>s.name).join(', ')} ingår i sökplanen. Öppna ett fordon för relevanta sökningar. <strong>Automatisk hämtning är inte ansluten.</strong> Sparade och kontrollerade jämförelsepriser räknas om av Hubben när vyn öppnas.</p><p>Auktionsbud är inte slutpriser. Moms, valuta, köparavgift och samma objekt på flera sajter måste kontrolleras. Inga sökträffar påverkar TCO eller marknadsvärde automatiskt.</p></section>
 </>;
}
