'use client';
import {useState} from 'react';
import type {Asset} from '@/lib/hub/asset-tco';
import {carSearchPlan,carSearchSources,type CarSearchResult} from '@/lib/hub/car-market-search';
const number=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0});
export function CarMarketSearch({asset,canManage}:{asset:Asset;canManage:boolean}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<CarSearchResult|null>(null),[error,setError]=useState('');
 if(asset.vehicle_type!=='Personbil'||!canManage)return null;
 const plan=carSearchPlan(asset);
 async function run(){setBusy(true);setError('');try{const response=await fetch('/api/hub/car-market-search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:asset.id})});const data=await response.json();if(!response.ok)throw Error(data.error);setResult(data);}catch(e){setError(e instanceof Error?e.message:'Sökningen kunde inte köras.');}finally{setBusy(false);}}
 const listings=result?.candidates.filter(c=>c.page_kind==='listing')??[];
 const other=result?.candidates.filter(c=>c.page_kind!=='listing')??[];
 const row=(c:CarSearchResult['candidates'][number])=><article key={c.url}><h3><a href={c.url} target="_blank" rel="noopener noreferrer">{c.source} · {c.title}</a></h3><p>{c.price_kind==='asking'?'Annons / fast pris – inte bekräftad försäljning':c.price_kind==='auction'?'Auktion – bud räknas inte som försäljningspris':'Pristyp måste kontrolleras'}</p><p style={{whiteSpace:'pre-line'}}>{c.snippet}</p>{c.date&&<small>Datum i sökindex: {c.date} – inte verifierat prisdatum.</small>}</article>;
 return <section className="panel"><h2>Marknadsunderlag · personbilar</h2><p>{asset.registration} · {[asset.make,asset.model].filter(Boolean).join(' ')} · {asset.current_meter==null?'Miltal saknas':`${number.format(asset.current_meter/10)} mil (${number.format(asset.current_meter)} km)`}{asset.meter_date?` · mätning ${asset.meter_date.slice(0,10)}`:''}</p><p>Källor: {carSearchSources.map(s=>s.name).join(', ')}. Endast modelluppgifter används i webbsökningen, aldrig regnummer eller personuppgifter. Enskilda annonser skiljs från samlingssidor.</p>{plan.missing.length>0&&<p><strong>Saknas för säker jämförelse:</strong> {plan.missing.join(', ')}. Inget medelpris eller marknadsvärde beräknas innan jämförbarheten har kontrollerats.</p>}<p>Avgränsad pilot: högst tre sökningar sammanlagt för arbetsytan, en per personbil. Sparade resultat återanvänds; inga återkommande körningar eller automatiska värdeändringar.</p><button disabled={busy||!asset.make||!asset.model} onClick={()=>void run()}>{busy?'Söker personbilsannonser…':result?'Visa sparat personbilsresultat':'Sök marknadsunderlag för personbil'}</button>{error&&<p role="alert">{error}</p>}{result&&<div aria-live="polite"><p>{result.candidates.length} träffar · {listings.length} enskilda objektsidor · sökning {result.searched_at}</p><p>{result.cost_usd==null?'Debiterad kostnad kunde inte verifieras.':`Gateway rapporterar ${result.cost_usd.toFixed(6)} USD för körningen.`}</p>{result.error&&<p role="alert">{result.error}</p>}<p>Uppgifter nedan är råa sökutdrag och kan vara gamla eller ofullständiga. Kontrollera pris, moms, motorvariant, årsmodell, miltal och skick. Samma bil på olika sajter får bara räknas en gång. Inget av detta ingår i värderingen ännu.</p><h3>Enskilda objektsidor ({listings.length})</h3>{listings.map(row)}<details><summary>Samlingssidor / ej säkert identifierade objektsidor ({other.length})</summary>{other.map(row)}</details></div>}</section>;
}
