"use client";
import {useEffect,useMemo,useState} from "react";
type V={id:string;name:string;registration:string}; type R={id:string;name:string;common_cost_type:string|null;cost_category:string|null;allocation_method:string;target_selection_mode:"all"|"selected"|"group";selected_object_ids:string[];monthly_cost:number|null;base_amount:number|null;po_percent:number|null;include_in_vehicle_result:boolean;valid_from:string|null;valid_to:string|null;notes:string|null};
const blank={name:"",common_cost_type:"other",cost_category:"other",allocation_method:"equal",target_selection_mode:"all",selected_object_ids:[] as string[],monthly_amount:"",base_amount:"",po_percent:"",include_in_vehicle_result:true,valid_from:new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Stockholm"}),valid_to:"",notes:""};
export function CommonCostAllocationManager(){
 const [rules,setRules]=useState<R[]>([]),[vehicles,setVehicles]=useState<V[]>([]),[form,setForm]=useState<any>(blank),[q,setQ]=useState(""),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/kpi/control-panel/common-costs",{cache:"no-store"}),j=await r.json();if(!r.ok)throw Error(j.error);setRules(j.rules??[]);setVehicles(j.vehicles??[])}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
 const shown=useMemo(()=>vehicles.filter(v=>(v.registration+" "+v.name).toLowerCase().includes(q.toLowerCase())),[vehicles,q]);
 function toggle(id:string){setForm((f:any)=>({...f,selected_object_ids:f.selected_object_ids.includes(id)?f.selected_object_ids.filter((x:string)=>x!==id):[...f.selected_object_ids,id]}))}
 async function save(){setMsg("Sparar…");const r=await fetch("/api/kpi/control-panel/common-costs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),j=await r.json();if(!r.ok){setMsg(j.error);return}setMsg("Sparat i Humla Hub");setForm(blank);await load()}
 return <div className="panel"><div className="control-section-head"><div><h3>Gemensamma kostnader & fördelning</h3><p>Klassificera kostnaden, välj vilka ekonomiska enheter som ska bära den och hur den ska fördelas.</p></div></div>
 <div className="form-grid"><label>Namn<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="T.ex. Tjänstemän Transport"/></label><label>Typ<select value={form.common_cost_type} onChange={e=>setForm({...form,common_cost_type:e.target.value})}><option value="salaried_staff">Tjänstemän</option><option value="management">Arbetsledning</option><option value="insurance">Försäkring</option><option value="premises">Lokaler</option><option value="administration">Administration</option><option value="other">Övrigt</option></select></label>
 {form.common_cost_type==="salaried_staff"?<><label>Månadslön<input type="number" value={form.base_amount} onChange={e=>setForm({...form,base_amount:e.target.value,monthly_amount:""})}/></label><label>PO-pålägg %<input type="number" step="0.1" value={form.po_percent} onChange={e=>setForm({...form,po_percent:e.target.value})}/></label></>:<label>Månadskostnad<input type="number" value={form.monthly_amount} onChange={e=>setForm({...form,monthly_amount:e.target.value})}/></label>}
 <label>Fördela efter<select value={form.allocation_method} onChange={e=>setForm({...form,allocation_method:e.target.value})}><option value="equal">Lika</option><option value="revenue_share">Omsättning</option><option value="hours_share">Timmar</option><option value="km_share">Kilometer</option><option value="fixed_share">Fast procentnyckel</option><option value="manual">Manuell</option><option value="exclude_vehicle_result">Utanför fordonsresultat</option></select></label>
 <label>Urval<select value={form.target_selection_mode} onChange={e=>setForm({...form,target_selection_mode:e.target.value,selected_object_ids:e.target.value==="selected"?form.selected_object_ids:[]})}><option value="all">Alla relevanta fordon</option><option value="selected">Enbart ikryssade fordon</option><option value="group">Vald grupp</option></select></label><label>Giltig från<input type="date" value={form.valid_from} onChange={e=>setForm({...form,valid_from:e.target.value})}/></label></div>
 {form.target_selection_mode==="selected"&&<div className="vehicle-picker"><div className="control-section-head"><strong>Välj fordon ({form.selected_object_ids.length} valda)</strong><button className="secondary" onClick={()=>setForm({...form,selected_object_ids:vehicles.map(v=>v.id)})}>Markera alla</button><button className="secondary" onClick={()=>setForm({...form,selected_object_ids:[]})}>Rensa</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Sök registreringsnummer eller enhet…"/><div className="checkbox-grid">{shown.map(v=><label key={v.id}><input type="checkbox" checked={form.selected_object_ids.includes(v.id)} onChange={()=>toggle(v.id)}/><b>{v.registration||"–"}</b> {v.name}</label>)}</div></div>}
 <label><input type="checkbox" checked={form.include_in_vehicle_result} onChange={e=>setForm({...form,include_in_vehicle_result:e.target.checked})}/> Ingår i fordonsresultatet</label><div><button onClick={save} disabled={!form.name||form.target_selection_mode==="selected"&&!form.selected_object_ids.length}>Spara fördelningsregel</button> <span role="status">{msg}</span></div>
 <div className="table-wrap"><table><thead><tr><th>Kostnad</th><th>Typ</th><th>Månad</th><th>Urval</th><th>Fördelning</th><th>Giltig från</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.common_cost_type??"–"}</td><td>{r.monthly_cost==null?"–":Number(r.monthly_cost).toLocaleString("sv-SE")+" kr"}</td><td>{r.target_selection_mode==="selected"?r.selected_object_ids.length+" valda":r.target_selection_mode==="all"?"Alla":"Grupp"}</td><td>{r.allocation_method}</td><td>{r.valid_from??"–"}</td></tr>)}</tbody></table></div></div>
}