'use client';
import {useEffect,useState} from 'react';
type Candidate={id:string;name:string;registration:string|null;projects:string[]};
export function CompoundUnitBuilder({from}:{from:string}){
 const [candidates,setCandidates]=useState<Candidate[]>([]),[main,setMain]=useState(''),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{fetch('/api/kpi/units').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setCandidates(j.candidates??[])}).catch(e=>setMessage(e.message))},[]);
 async function save(form:FormData){setBusy(true);setMessage('');try{const registrations=[...new Set([main,...selected.map(id=>candidates.find(c=>c.id===id)?.registration??'')].filter(Boolean))];const projects=[...new Set(selected.flatMap(id=>candidates.find(c=>c.id===id)?.projects??[]))];const r=await fetch('/api/kpi/units',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({unit_type:'compound',name:form.get('name'),main_vehicle:main,projects:projects.join('\n'),registrations:registrations.join('\n'),employees:String(form.get('employees')??''),valid_from:form.get('valid_from'),valid_to:null,enabled:true})});const j=await r.json();if(!r.ok)throw new Error(j.error);window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 return <section className="panel"><h2>Skapa ekonomisk enhet</h2><p>Välj huvudfordon och markera ingående objekt. Projekt kopplas bara efter ditt uttryckliga val. Övergripande kostnadsprojekt blir inga fordon.</p><form action={save}><fieldset disabled={busy}><label>Enhetsnamn<input name="name" required maxLength={120}/></label><label>Huvudfordon<select required value={main} onChange={e=>setMain(e.target.value)}><option value="">Välj fordon</option>{candidates.filter(c=>c.registration).map(c=><option key={c.id} value={c.registration!}>{c.name}</option>)}</select></label><details><summary>Markera ingående objekt ({selected.length})</summary><label>Sök projekt eller regnummer<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex. 9018 eller DFC86A"/></label>{candidates.filter(c=>(c.name+' '+c.projects.join(' ')).toLowerCase().includes(search.toLowerCase())).map(c=><label key={c.id} style={{display:'block'}}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(id=>id!==c.id))}/>{c.name} · {c.projects.join(', ')}</label>)}</details><label>Personreferenser från TransPA / anställningsnummer<textarea name="employees" placeholder="En verifierad referens per rad"/></label><p>Personreferenser innebär ingen verifierad permanent Humla Person-identitet.</p><label>Giltig från<input name="valid_from" type="date" required defaultValue={from}/></label><button className="primary">{busy?'Sparar…':'Spara enhet'}</button></fieldset></form>{message&&<p role="alert">{message}</p>}</section>
}
