'use client';
import {useState} from 'react';
export const types={cost:'Kostnadsregel',article:'Workify-artikel',project_group:'Projekt → verksamhetsgrupp',project_vehicle:'Projekt → fordon',depreciation:'Avskrivning'};
const costs={personnel:'Personal',fuel:'Bränsle',service_repair:'Service & Rep',depreciation:'Avskrivning',fixed:'Fasta kostnader',other:'Övrigt',material:'Ballast/Material',tipp_deponi:'Deponi/Tipp',hired:'Inhyrda'};
export type RuleKind=keyof typeof types;
export type RuleData={groups:Array<{id:string;name:string}>}&Record<string,unknown>;
export function DatedRuleManager({data,initialKind='cost',candidates=[]}:{data:RuleData;initialKind?:RuleKind;candidates?:Array<{id:string;name:string;registration:string|null;projects:string[]}>}){
 const [kind,setKind]=useState<keyof typeof types>(initialKind),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[reference,setReference]=useState(''),[seed,setSeed]=useState<Record<string,unknown>>({});
 const history=(Array.isArray(data[kind])?data[kind]:[]) as Array<Record<string,unknown>>;
 const visible=history.filter(row=>Object.values(row).some(value=>String(value??'').toLowerCase().includes(search.toLowerCase())));
 const refFor=(row:Record<string,unknown>)=>String(row.account??row.article_number??row.project_reference??row.object_reference??'');
 async function save(f:FormData){setBusy(true);setMessage('');try{const r=await fetch('/api/kpi/rules',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,rule:{...Object.fromEntries(f),include_in_vehicle_result:f.get('include_in_vehicle_result')==='on'}})});const j=await r.json();if(!r.ok)throw new Error(j.error);window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 return <><datalist id="kpi-project-suggestions">{candidates.flatMap(c=>c.projects.map(p=><option key={c.id+':'+p} value={p}>{c.name}</option>))}</datalist><datalist id="kpi-vehicle-suggestions">{candidates.filter(c=>c.registration).map(c=><option key={c.id} value={c.registration!}>{c.name}</option>)}</datalist><section className="panel"><h2>Daterade regler i Humla Hub</h2><p>Kontrollera koppling och startdatum innan du sparar. En ny regel avslutar föregående period dagen före startdatumet. Historiska värden behålls. Inga generella BAS-regler skapas automatiskt.</p><label>Regeltyp<select value={kind} onChange={e=>{setKind(e.target.value as RuleKind);setReference('');setSearch('');setSeed({})}}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><form key={kind+String(seed.id??'new')} action={save}><fieldset disabled={busy}><label>{kind==='cost'?'Exakt konto':kind==='article'?'Artikelnummer':kind==='depreciation'?'Fordon / kostnadsobjekt':'Projektnummer'}<input name="reference" list={kind.startsWith('project_')?'kpi-project-suggestions':undefined} required maxLength={100} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Skriv eller välj i registret nedan"/></label>
 {kind==='cost'&&<><label>Kostnadskategori<select name="category" defaultValue={String(seed.cost_category??'personnel')}>{Object.entries(costs).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><input name="include_in_vehicle_result" type="checkbox" defaultChecked={seed.include_in_vehicle_result!==false}/>Ingår i fordonsresultat</label><p>Avmarkerade kostnader finns kvar i transportens fullständiga total men fördelas inte till ett fordon.</p></>}
 {kind==='article'&&<><label>Artikelns namn<input name="name" defaultValue={String(seed.article_name??'')}/></label><label>Mottagare<select name="target_type" defaultValue={String(seed.target_type??'vehicle')}><option value="vehicle">Utförande fordon</option><option value="project">NEXT-projekt</option></select></label><label>NEXT-projekt (krävs för projektmottagare)<input name="project" defaultValue={String(seed.project_reference??'')}/></label><label>Intäktstyp<select name="category" defaultValue={String(seed.revenue_category??'transport')}><option value="transport">Transport</option><option value="material">Material</option><option value="tipp">Tipp</option><option value="hired">Inhyrda</option><option value="other">Övrigt</option></select></label></>}
 {kind==='project_group'&&<label>Verksamhetsgrupp<select name="group_id" defaultValue={String(seed.business_group_id??data.groups[0]?.id??'')}>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}
 {kind==='project_vehicle'&&<label>Verifierat registreringsnummer<input name="vehicle" defaultValue={String(seed.vehicle_registration??'')} list="kpi-vehicle-suggestions" required pattern="[A-Za-z]{3}[0-9]{2}[A-Za-z0-9]"/></label>}
 {kind==='depreciation'&&<label>Belopp per månad, kr<input name="monthly_amount" defaultValue={String(seed.monthly_depreciation??'')} type="number" step="0.01" min="0" max="10000000" required/></label>}
 <label>Giltig från<input name="valid_from" type="date" required/></label><label>Giltig till (valfritt)<input name="valid_to" type="date"/></label><button className="primary">{busy?'Sparar…':'Spara ny regelperiod'}</button></fieldset></form>{message&&<p role="alert">{message}</p>}</section><section className="panel"><h2>Register och historik · {types[kind]}</h2><label>Sök konto, projekt, regnummer eller artikel<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sök i befintliga regler"/></label><p>{visible.length} regelperioder. Välj en referens för att skapa nästa period; befintliga datum skrivs inte över.</p><div className="table-wrap"><table><thead><tr><th>Referens</th><th>Koppling / kategori</th><th>Giltig från</th><th>Giltig till</th><th>Åtgärd</th></tr></thead><tbody>{visible.map((row,i)=><tr key={String(row.id??i)}><td>{refFor(row)}</td><td>{String(row.vehicle_registration??row.cost_category??row.revenue_category??data.groups.find(g=>g.id===row.business_group_id)?.name??row.monthly_depreciation??'–')}{row.project_reference&&kind==='article'?` → ${row.project_reference}`:''}</td><td>{String(row.valid_from??'Äldre regel')}</td><td>{String(row.valid_to??'Tills vidare')}</td><td><button type="button" className="secondary" onClick={()=>{setReference(refFor(row));setSeed(row)}}>Ny period för {refFor(row)}</button><details><summary>Visa originalregel</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(row,null,2)}</pre></details></td></tr>)}</tbody></table></div>{!visible.length&&<p>Inga regler matchar sökningen. Skapa en verifierad koppling i formuläret ovan.</p>}</section></>
}
