'use client';
import {useState} from 'react';
const types={cost:'Kostnadsregel',article:'Workify-artikel',project_group:'Projekt → verksamhetsgrupp',project_vehicle:'Projekt → fordon',depreciation:'Avskrivning'};
const costs={personnel:'Personal',fuel:'Bränsle',service_repair:'Service & Rep',depreciation:'Avskrivning',fixed:'Fasta kostnader',other:'Övrigt',material:'Ballast/Material',tipp_deponi:'Deponi/Tipp',hired:'Inhyrda'};
export function DatedRuleManager({data}:{data:{groups:Array<{id:string;name:string}>}&Record<string,unknown>}){
 const [kind,setKind]=useState<keyof typeof types>('cost'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function save(f:FormData){setBusy(true);setMessage('');try{const r=await fetch('/api/kpi/rules',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,rule:{...Object.fromEntries(f),include_in_vehicle_result:f.get('include_in_vehicle_result')==='on'}})});const j=await r.json();if(!r.ok)throw new Error(j.error);window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 return <><section className="panel"><h2>Daterade regler i Humla Hub</h2><p>En ny regel avslutar föregående period dagen före startdatumet. Historiska värden behålls. Inga generella BAS-regler skapas automatiskt.</p><label>Regeltyp<select value={kind} onChange={e=>setKind(e.target.value as keyof typeof types)}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><form key={kind} action={save}><fieldset disabled={busy}><label>{kind==='cost'?'Exakt konto':kind==='article'?'Artikelnummer':kind==='depreciation'?'Fordon / kostnadsobjekt':'Projektnummer'}<input name="reference" required maxLength={100}/></label>
 {kind==='cost'&&<><label>Kostnadskategori<select name="category">{Object.entries(costs).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><input name="include_in_vehicle_result" type="checkbox" defaultChecked/>Ingår i fordonsresultat</label><p>Avmarkerade kostnader finns kvar i transportens fullständiga total men fördelas inte till ett fordon.</p></>}
 {kind==='article'&&<><label>Artikelns namn<input name="name"/></label><label>Mottagare<select name="target_type"><option value="vehicle">Utförande fordon</option><option value="project">NEXT-projekt</option></select></label><label>NEXT-projekt (krävs för projektmottagare)<input name="project"/></label><label>Intäktstyp<select name="category"><option value="transport">Transport</option><option value="material">Material</option><option value="tipp">Tipp</option><option value="hired">Inhyrda</option><option value="other">Övrigt</option></select></label></>}
 {kind==='project_group'&&<label>Verksamhetsgrupp<select name="group_id">{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}
 {kind==='project_vehicle'&&<label>Verifierat registreringsnummer<input name="vehicle" required pattern="[A-Za-z]{3}[0-9]{2}[A-Za-z0-9]"/></label>}
 {kind==='depreciation'&&<label>Belopp per månad, kr<input name="monthly_amount" type="number" step="0.01" min="0" max="10000000" required/></label>}
 <label>Giltig från<input name="valid_from" type="date" required/></label><label>Giltig till (valfritt)<input name="valid_to" type="date"/></label><button className="primary">{busy?'Sparar…':'Spara ny regelperiod'}</button></fieldset></form>{message&&<p role="alert">{message}</p>}</section><section className="panel"><h2>Register och historik</h2>{Object.entries(types).map(([k,label])=><details key={k}><summary>{label}</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(data[k],null,2)}</pre></details>)}</section></>
}
