'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
type Result={accepted:number;review:number;duplicates:number;rows:Array<{row:number;registration:string;status:string;reason?:string}>};
export function DistanceImport(){
 const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/kpi/distance',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.error);setResult(j);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Importen misslyckades');}finally{setBusy(false);}}
 return <section className="panel"><h2>Importera periodens körsträcka</h2><p>CSV eller Excel med rubrikerna <strong>Regnummer, Från, Till, Körsträcka, Enhet</strong>. Datum som text ÅÅÅÅ-MM-DD. Enhet: km eller mil. Från och Till ingår i perioden. En mil är 10 km.</p><p>Exempel på CSV-rad: <code>DFC86A;2026-08-01;2026-08-31;1250;mil</code>. Använd verifierad körsträcka från källan. Månadsvärden delas inte automatiskt upp i veckor eller dagar.</p><form onSubmit={submit}><label>Källa <input name="source" required placeholder="Fordonskontrollen, rapport augusti 2026" maxLength={300}/></label><label>Fil <input name="file" type="file" accept=".csv,.xlsx,.xls" required disabled={busy}/></label><button disabled={busy}>{busy?'Importerar…':'Importera körsträcka'}</button></form>{error&&<p role="alert">{error}</p>}{result&&<><p role="status">{result.accepted} sparade · {result.review} till granskning · {result.duplicates} dubbletter ignorerade</p><div className="table-wrap"><table><thead><tr><th>Rad</th><th>Regnummer</th><th>Status</th><th>Orsak</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.registration}</td><td>{r.status==='accepted'?'Sparad':r.status==='review'?'Behöver granskas':'Dubblett'}</td><td>{r.reason??'–'}</td></tr>)}</tbody></table></div><a href="/kpi/korstracka">Öppna granskning</a></>}</section>;
}
