"use client";
import {useEffect,useRef,useState} from 'react';
import type {KpiUnit} from '@/lib/kpi/units';
type EditableUnit=KpiUnit&{main_vehicle:string;periods:Array<{valid_from:string;valid_to:string|null}>};
function nextDate(date:string){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
export function ExistingUnitEditor(){
 const editRef=useRef<HTMLFormElement>(null);
 const [units,setUnits]=useState<EditableUnit[]>([]),[selected,setSelected]=useState<EditableUnit|null>(null),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[main,setMain]=useState('');
 useEffect(()=>{if(selected)editRef.current?.scrollIntoView({behavior:'smooth',block:'start'})},[selected]);
 async function load(){const r=await fetch('/api/kpi/units',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setUnits(j.units??[])}
 useEffect(()=>{let active=true;fetch('/api/kpi/units',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);if(active)setUnits(j.units??[])}).catch(e=>{if(active)setMessage(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(form:FormData){if(!selected||busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/kpi/units',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...Object.fromEntries(form),id:selected.id,revision:selected.revision,enabled:form.get('enabled')==='on'}),signal:AbortSignal.timeout(30000)});const j=await r.json();if(!r.ok)throw Error(j.error);setMessage(`${selected.name} uppdaterad från ${form.get('valid_from')}. Samma enhets-ID och tidigare historik är kvar.`);setSelected(null);await load()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 const visible=units.filter(u=>(u.name+' '+u.projects.join(' ')+' '+u.registrations.join(' ')).toLowerCase().includes(search.toLowerCase()));
 return <section className="panel"><h2>Redigera befintliga enheter</h2><label>Sök enhet, projekt eller regnummer<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex. DFC86A eller 9018"/></label>{loading?<p role="status">Hämtar enheter…</p>:<div className="table-wrap"><table><thead><tr><th>Enhet</th><th>Regnummer</th><th>Projekt</th><th>Senaste period</th><th>Åtgärd</th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td>{u.name}{!u.enabled?' (avstängd)':''}</td><td>{u.registrations.join(' + ')}</td><td>{u.projects.join(', ')}</td><td>{u.valid_from}</td><td><button type="button" className="secondary" onClick={()=>{setSelected(u);setMain(u.main_vehicle);setMessage('')}} disabled={busy}>Redigera {u.name}</button></td></tr>)}</tbody></table></div>}{selected&&<form ref={editRef} key={selected.id} action={save} className="panel"><h3>Redigera {selected.name}</h3><p>Senaste period börjar {selected.valid_from}. Ändringen får ett nytt startdatum efter detta datum; tidigare kopplingar bevaras.</p><fieldset disabled={busy}><label>Enhetsnamn · intäktsbärande huvudfordon{selected.registrations.length?<input name="name" required readOnly value={main}/>:<input name="name" required defaultValue={selected.name}/>}</label><input type="hidden" name="unit_type" value={selected.unit_type}/><label>Projekt · ett per rad<textarea name="projects" defaultValue={selected.projects.join('\n')}/></label><label>Bil och släp · ett regnummer per rad<textarea name="registrations" defaultValue={selected.registrations.join('\n')}/></label><label>Huvudfordon<input name="main_vehicle" value={main} onChange={e=>setMain(e.target.value.toUpperCase())} placeholder="Ska ingå bland regnumren"/></label><label>Personreferenser<textarea name="employees" defaultValue={selected.employees.join('\n')}/></label><label>Ändringen gäller från<input name="valid_from" type="date" required min={nextDate(selected.valid_from)} defaultValue={[nextDate(selected.valid_from),new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Stockholm'})].sort().at(-1)}/></label><label>Giltig till (valfritt)<input name="valid_to" type="date"/></label><label><input type="checkbox" name="enabled" defaultChecked={selected.enabled}/>Aktiv</label><button className="primary">{busy?'Sparar…':'Spara ändrade kopplingar'}</button><button className="secondary" type="button" onClick={()=>setSelected(null)}>Avbryt</button></fieldset></form>}{message&&<p role="status">{message}</p>}</section>
}
