'use client';
import {useState,useTransition} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {fleetCostLabels,type FleetComparisonReport} from '@/lib/hub/fleet-kpi';
import {FleetPeerComparison} from './fleet-peer-comparison';
import styles from './asset-tco-workspace.module.css';
const number=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0});
const decimal=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:2});
const money=(n:number|null)=>n===null?'Saknat underlag':`${number.format(n)} kr`;
const value=(n:number|null,unit:string)=>n===null?'Saknat underlag':`${decimal.format(n)} ${unit}`;
export function FleetKpiWorkspace({report,selectedId,department}:{report:FleetComparisonReport;selectedId:string|null;department:string}){
 const params=useSearchParams();const router=useRouter();const [pending,start]=useTransition();const [search,setSearch]=useState('');const [sort,setSort]=useState('cost');
 function href(change:Record<string,string|null>){const p=new URLSearchParams(params);p.delete('tab');for(const [k,v] of Object.entries(change)){if(v===null)p.delete(k);else p.set(k,v);}return `/kpi/fordon?${p}`;}
 const selected=report.assets.find(a=>a.id===selectedId);const s=report.summary;
 const assets=report.assets.filter(a=>[a.registration,a.model,a.description,a.department].join(' ').toLocaleLowerCase('sv-SE').includes(search.toLocaleLowerCase('sv-SE'))).toSorted((a,b)=>sort==='registration'?(a.registration??a.description??'').localeCompare(b.registration??b.description??'','sv'):sort==='department'?a.department.localeCompare(b.department,'sv'):(b[sort as 'cost'|'service_repair'|'cost_per_unit']??-Infinity)-(a[sort as 'cost'|'service_repair'|'cost_per_unit']??-Infinity));
 const maxCost=Math.max(1,...report.monthly.map(m=>Math.abs(m.cost??0)));
 return <>
 <section className="panel"><div className="panel-head"><div><span className="section-kicker">Fordonsansvarig · perioduppföljning</span><h2>{selected?`${selected.registration||selected.description} · ${selected.model}`:'Drift, användning och underhåll'}</h2></div><button className="secondary" disabled={pending} onClick={()=>start(()=>router.refresh())}>{pending?'Hämtar…':'Uppdatera fordonsvyn'}</button></div><p>Kostnader exklusive moms från det gemensamma Hub-underlaget. Periodens summa omfattar bränsle, service/reparation, fasta kostnader och importerade avskrivningar. Planerad värdeminskning från TCO läggs inte till här.</p><p className={styles.muted}>Synkat {report.sync_at?new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',dateStyle:'short',timeStyle:'short'}).format(new Date(report.sync_at)):'underlag saknas'}. Pågående period visas till {report.period.through}. Framtida månader ingår inte. Intäkter och personallöner ingår inte i fordonskostnaden.</p>
 {!selectedId&&<div className={styles.filters}><label>Avdelning<select aria-label="Fordonsavdelning" value={department} disabled={pending} onChange={e=>start(()=>router.push(href({department:e.target.value||null,asset:null})))}><option value="">Alla avdelningar</option>{report.departments.map(d=><option key={d}>{d}</option>)}</select></label></div>}
 </section>
 {selectedId&&<Link prefetch={false} href={href({asset:null})}>← Alla fordon med samma period och avdelning</Link>}
 <div className={styles.cards}>{[['Tillgänglig fordonskostnad',s.cost],['Bränsle',s.fuel],['Service och reparation',s.service_repair],['Fasta kostnader',s.fixed],['Importerade avskrivningar',s.depreciation]].map(([label,amount])=><div className={styles.stat} key={String(label)}><h3>{label}</h3><strong>{money(amount as number|null)}</strong><p>Valda månader · kopplat underlag</p></div>)}</div>
 <section className="panel"><h2>Underlagets täckning</h2><div className={styles.cards}>{[['Kostnader',s.cost_assets],['Körsträcka / drifttimmar',s.meter_assets],['Rapporterad fordonstid',s.time_assets],['Service, besiktning och fel',s.maintenance_assets]].map(([label,count])=><div className={styles.stat} key={String(label)}><h3>{label}</h3><strong>{count} / {s.assets}</strong><p>Fordon med underlag</p></div>)}</div><p>Kostnad per mil eller drifttimme visas bara när mätningar täcker samtliga valda månader. Saknade kostnader visas som saknat underlag; en registrerad nollpost visas som 0 kr.</p><p>Övriga kopplade kostnadskategorier behöver bedömas: {money(report.coverage.other_linked_cost)} · {report.coverage.other_linked_rows} rader, utanför fordonskostnaden.</p><details><summary>Poster utan entydig fordonskoppling · hela avdelningsregistret</summary><p>{money(report.coverage.unlinked_cost)} · {report.coverage.unlinked_rows} kostnadsrader saknar koppling till ett kanoniskt fordon och ingår inte i fordonskostnaden. Underlaget kan även innehålla projektkostnader och krediter. Kopplingarna behöver kontrolleras i Hubben.</p></details></section>
 {!selectedId&&<FleetPeerComparison assets={report.assets} groups={report.comparison_groups} canManage={report.can_manage} department={department} href={href}/>}
 <section className="panel"><h2>Rapporterad tid och nyttjande · schablon</h2><div className={styles.cards}><div className={styles.stat}><h3>Rapporterad fordonstid</h3><strong>{value(s.reported_hours,'h')}</strong><p>TransPA · {s.time_assets} fordon med tid</p></div><div className={styles.stat}><h3>Nyttjande av schablonkapacitet</h3><strong>{value(s.utilization,'%')}</strong><p>Rapporterad tid / arbetsdagarnas kapacitet</p></div><div className={styles.stat}><h3>Stillestånd och faktisk tillgänglighet</h3><strong>Saknat underlag</strong><p>Stilleståndsperioder är inte registrerade</p></div></div><p>Nyttjandegraden bygger på kapacitet per arbetsdag i Hub-inställningarna. Den kan överstiga 100 % vid långa pass. Faktiskt stillestånd och motortimmar ska följas med eget underlag.</p></section>
 <section className="panel"><h2>Kostnader per månad</h2><p className={styles.muted}>Klicka på en månad för att se dess fordon och kostnader.</p><div className="table-wrap"><table><thead><tr><th>Månad</th><th>Fordonskostnad</th><th>Bränsle</th><th>Service / reparation</th><th>Trend</th></tr></thead><tbody>{report.monthly.map(m=><tr key={m.date}><td><Link prefetch={false} href={href({months:String(Number(m.date.slice(5,7)))})}>{m.date.slice(0,7)}</Link></td><td>{money(m.cost)}</td><td>{money(m.fuel)}</td><td>{money(m.service_repair)}</td><td><div className={styles.trendTrack} aria-hidden="true"><span style={{width:`${Math.abs(m.cost??0)/maxCost*100}%`}}/></div></td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Kostnadsdelar</h2><p>Försäkring och fordonsskatt ligger gemensamt på konto 5612/5622. Leasing visas från 5615, finansieringsränta från 8410/8422 och tillsyn/avgifter från 6950. Underlaget särredovisas efter konto utan att gissa fördelningen på en faktura.</p><div className={styles.cards}>{report.components.map(c=><div className={styles.stat} key={c.component}><h3>{fleetCostLabels[c.component]??c.component}</h3><strong>{money(c.amount)}</strong><p>{c.rows} underlagsrader</p></div>)}</div></section>
 {!selectedId?<section className="panel"><h2>Fordon och maskiner</h2><div className={styles.filters}><label>Sök fordon<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Regnummer, modell eller avdelning"/></label><label>Sortera efter<select value={sort} onChange={e=>setSort(e.target.value)}><option value="cost">Högst fordonskostnad</option><option value="service_repair">Högst service / reparation</option><option value="cost_per_unit">Högst kostnad per mil / timme</option><option value="registration">Regnummer</option><option value="department">Avdelning</option></select></label></div><p>{assets.length} fordon · klicka för kostnadsrader och beräkningsunderlag. Mil- och timkostnader använder olika enheter; jämför fordon med samma användning.</p><div className="table-wrap"><table><thead><tr><th>Fordon / modell</th><th>Avdelning</th><th>Kostnad</th><th>Service / reparation</th><th>Samma period förra året</th><th>Användning</th><th>Kr / mil eller h</th><th>Rapporterade timmar</th><th>Nyttjande · schablon</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td><Link prefetch={false} href={href({asset:a.id})}>{a.registration||a.description||'Öppna fordon'}</Link><small className={styles.block}>{a.model}</small></td><td>{a.department}</td><td>{money(a.cost)}</td><td>{money(a.service_repair)}<small className={styles.block}>{a.repair_rows===null?'':`${a.repair_rows} kostnadsrader`}</small></td><td>{money(a.previous_cost)}<small className={styles.block}>{a.change_pct===null?'':`${a.change_pct>0?'+':''}${decimal.format(a.change_pct)} %`}</small></td><td>{value(a.usage===null?null:a.meter_type==='odometer_km'?a.usage/10:a.usage,a.meter_type==='engine_hours'?'h':'mil')}<small className={styles.block}>{a.interpolated?'Interpolerad mätning':''}</small></td><td>{value(a.cost_per_unit,a.meter_type==='engine_hours'?'kr/h':'kr/mil')}</td><td>{value(a.reported_hours,'h')}</td><td>{value(a.utilization,'%')}</td></tr>)}</tbody></table></div></section>:selected?<>
 <section className="panel"><h2>Användning och kostnad per enhet</h2><div className={styles.cards}><div className={styles.stat}><h3>{selected.meter_type==='engine_hours'?'Drifttimmar':'Körsträcka'}</h3><strong>{value(selected.usage===null?null:selected.meter_type==='odometer_km'?selected.usage/10:selected.usage,selected.meter_type==='engine_hours'?'h':'mil')}</strong><p>{selected.missing_months??0} månader saknar komplett mätning</p></div><div className={styles.stat}><h3>Kostnad per {selected.meter_type==='engine_hours'?'drifttimme':'mil'}</h3><strong>{value(selected.cost_per_unit,selected.meter_type==='engine_hours'?'kr/h':'kr/mil')}</strong><p>Periodens fordonskostnad / periodens användning</p></div><div className={styles.stat}><h3>Bränsle per enhet</h3><strong>{value(selected.fuel_per_unit,selected.meter_type==='engine_hours'?'kr/h':'kr/mil')}</strong><p>{value(selected.liters_per_unit,selected.meter_type==='engine_hours'?'liter/h':'liter/mil')} · liter visas endast med komplett volymunderlag</p></div></div><p>Mätarställningar måste omge periodens båda gränser. Mellan mätningarna används linjär interpolation; ingen extrapolering görs. Minskande mätarställningar och motstridiga källor ger saknat underlag. Släp utan mätare får ingen mil- eller timkostnad.</p><details><summary>Visa mätarunderlag per månad</summary><div className="table-wrap"><table><thead><tr><th>Period</th><th>Metod</th><th>Användning, km / h</th><th>Startgränsens mätningar</th><th>Slutgränsens mätningar</th></tr></thead><tbody>{report.meter_evidence.map(m=><tr key={m.from}><td>{m.from} – {m.to}</td><td>{m.estimate.basis==='interpolated'?'Interpolerat':m.estimate.basis==='meter_exact'?'Exakt':'Saknat / ogiltigt underlag'}</td><td>{value(m.estimate.distance_km??m.estimate.value??null,m.type==='engine_hours'?'h':'km')}</td><td>{m.estimate.start_before?.slice(0,10)??'–'} / {m.estimate.start_after?.slice(0,10)??'–'}</td><td>{m.estimate.end_before?.slice(0,10)??'–'} / {m.estimate.end_after?.slice(0,10)??'–'}</td></tr>)}</tbody></table></div></details></section>
 <section className="panel"><h2>Rapporterad fordonstid och nyttjande</h2><div className={styles.cards}><div className={styles.stat}><h3>TransPA · fordonstid</h3><strong>{value(selected.reported_hours,'h')}</strong></div><div className={styles.stat}><h3>Schablonkapacitet</h3><strong>{value(selected.capacity,'h')}</strong></div><div className={styles.stat}><h3>Nyttjande · schablon</h3><strong>{value(selected.utilization,'%')}</strong></div></div><p>Rapporterad fordonstid / arbetsdagarnas kapacitet enligt Hub-inställningen. Helger och svenska helgdagar undantas. Kapaciteten räknas tidigast från fordonets första tidsrapport. Detta är en schablon som kan överstiga 100 % vid långa pass; den visar inte faktisk tillgänglighet eller maskinens motortimmar.</p><details><summary>Visa rapporterad tid ({report.time_evidence.length} dagar)</summary><table><thead><tr><th>Datum</th><th>Fordonstimmar</th><th>Tidsrapporter</th></tr></thead><tbody>{report.time_evidence.map((t,i)=><tr key={`${t.date}-${i}`}><td>{t.date}</td><td>{value(t.hours,'h')}</td><td>{t.reports}</td></tr>)}</tbody></table></details></section>
 <section className="panel"><h2>Periodens kostnadsunderlag</h2><p>{report.evidence_count} rader · kostnadsdatum {selected.first_cost_date??'saknas'} – {selected.last_cost_date??'saknas'}. Krediter behåller sitt tecken. Tankkostnader följer samma avstämning som övriga KPI-vyn.</p><details><summary>Visa alla ingående rader</summary>{report.evidence_count>report.evidence.length&&<p>De senaste {report.evidence.length} raderna visas; totalsumman omfattar alla {report.evidence_count} rader.</p>}<div className="table-wrap"><table><thead><tr><th>Datum</th><th>Källa / fil / rad</th><th>Kostnadsdel</th><th>Konto</th><th>Beskrivning</th><th>Belopp</th></tr></thead><tbody>{report.evidence.map((c,i)=><tr key={`${c.id}-${i}`}><td>{c.date}</td><td>{c.source}<small className={styles.block}>{c.file_name??''}{c.row_number!==null?` · rad ${c.row_number}`:''}</small></td><td>{fleetCostLabels[c.component]??c.component}</td><td>{c.account??'–'}</td><td>{c.description}</td><td>{money(c.amount)}</td></tr>)}</tbody></table></div></details></section>
 </>:<p role="alert">Fordonet finns inte i det valda avdelningsurvalet.</p>}
 <section className="panel"><h2>Service, besiktning och öppna fel · aktuell status</h2><p>Visar registrerade uppgifter i Hubben oavsett ekonomisk period. Saknat underlag betyder att status inte kan verifieras.</p>{s.maintenance_assets===0?<p><strong>Saknat underlag.</strong> Serviceplaner, besiktningsdatum och felrapporter är ännu inte importerade för de valda fordonen.</p>:<div className="table-wrap"><table><thead><tr><th>Fordon</th><th>Typ</th><th>Uppgift</th><th>Förfallodatum</th><th>Status</th></tr></thead><tbody>{report.assets.flatMap(a=>(a.maintenance??[]).map(m=><tr key={m.id}><td><Link href={href({asset:a.id})}>{a.registration||a.description}</Link></td><td>{({service:'Service',inspection:'Besiktning',fault:'Fel'} as Record<string,string>)[m.type]??m.type}</td><td>{m.title}</td><td>{m.due?.slice(0,10)??'Saknas'}</td><td>{m.status??'Ej angiven'}</td></tr>))}</tbody></table></div>}</section>
 </>;
}
