'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import type {FleetAsset,FleetComparisonGroup,FleetComparisonMetric} from '@/lib/hub/fleet-kpi';
import styles from './asset-tco-workspace.module.css';
const number=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:1});
function Metric({m,unit}:{m:FleetComparisonMetric;unit:string}){
 return <><span>{m.value===null?'Saknat underlag':`${number.format(m.value)} ${unit}`}</span><small className={styles.block}>{m.median===null?`${m.peers} jämförbara andra · minst 3 krävs`:`Median andra: ${number.format(m.median)} ${unit} · ${m.peers} fordon`}</small>{m.change_pct!==null&&<small className={styles.block}>{m.outlier?'⚠ Granska · ':''}{m.change_pct>0?'+':''}{number.format(m.change_pct)} % mot median</small>}</>;
}
export function FleetPeerComparison({assets,groups,canManage,department,href}:{assets:FleetAsset[];groups:FleetComparisonGroup[];canManage:boolean;department:string;href:(change:Record<string,string|null>)=>string}){
 const router=useRouter();const [groupId,setGroupId]=useState('');const [editor,setEditor]=useState(false);const [editingId,setEditingId]=useState<string|null>(null);const [revision,setRevision]=useState<number|null>(null);
 const [name,setName]=useState('');const [category,setCategory]=useState('Lastbil');const [notes,setNotes]=useState('');const [members,setMembers]=useState<string[]>([]);const [search,setSearch]=useState('');const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 const group=groups.find(g=>g.id===groupId)??groups[0];
 function edit(g?:FleetComparisonGroup){setEditingId(g?.id??null);setRevision(g?.revision??null);setName(g?.name??'');setCategory(g?.class??'Lastbil');setNotes(g?.notes??'');setMembers(g?.members??[]);setSearch('');setMessage('');setEditor(true);}
 async function save(){setSaving(true);setMessage('');try{const r=await fetch('/api/hub/fleet-comparison',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editingId,revision,name,class:category,notes,members})});const data=await r.json();if(!r.ok)throw new Error(data.error??'Kunde inte spara');setGroupId(data.id);setEditor(false);setMessage('Gruppen sparades i Hubben.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara');}finally{setSaving(false);}}
 return <section className="panel"><h2>Jämför likvärdiga fordon och maskiner</h2><p>Bekräftade grupper efter fordonstyp, storlek, utrustning och användningsområde. Kostnader jämförs för samma valda period och avdelningsurval. Hög användning ger inte i sig en avvikelse.</p><p>Mil- och timkostnader hålls åtskilda. Medianen räknas på minst tre andra gruppmedlemmar med komplett mätartäckning. Över 30 % högre kostnad markeras för granskning. Saknade kostnadsposter kan inte upptäckas automatiskt; kontrollera bokföringens täckning innan slutsatser dras.</p>
 <div className={styles.filters}><label>Jämförelsegrupp<select aria-label="Jämförelsegrupp" value={group?.id??''} onChange={e=>setGroupId(e.target.value)}><option value="" disabled>Välj grupp</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.class}</option>)}</select></label>{canManage&&!department&&<><button className="secondary" onClick={()=>edit()}>Ny jämförelsegrupp</button>{group&&<button className="secondary" onClick={()=>edit(group)}>Ändra grupp</button>}</>}{canManage&&department&&<Link href={href({department:null,asset:null})}>Visa alla avdelningar för att ändra grupper</Link>}</div>
 {message&&<p role="status">{message}</p>}
 {!group&&<p>Inga grupper är bekräftade ännu. Gruppera exempelvis tippbilar med samma storlek och uppdrag, eller grävmaskiner i samma viktklass. Samma modellnamn räcker inte alltid för en rättvis jämförelse.</p>}
 {group&&<><h3>{group.name} · {group.class}</h3><p>{group.notes||'Ingen jämförelsebeskrivning angiven.'} · {group.members.length} medlemmar; {group.rows.length} i aktuellt urval. Gruppens nuvarande bekräftade definition används även för historiska perioder; kostnaderna ändras inte.</p><div className="table-wrap"><table><thead><tr><th>Fordon / maskin</th><th>Periodkostnad</th><th>Kostnad per mil / h</th><th>Bränsle per mil / h</th><th>Service / reparation per mil / h</th></tr></thead><tbody>{group.rows.map(a=><tr key={a.id}><td><Link prefetch={false} href={href({asset:a.id})}>{a.registration||a.description||'Visa fordon'}</Link><small className={styles.block}>{a.model}</small></td><td>{a.cost===null?'Saknat underlag':`${number.format(a.cost)} kr`}<small className={styles.block}>Service: {a.service_repair===null?'saknas':`${number.format(a.service_repair)} kr`}</small></td>{(['cost_per_unit','fuel_per_unit','repair_per_unit'] as const).map(key=><td key={key}><Metric m={a.metrics[key]} unit={a.meter_type==='engine_hours'?'kr/h':'kr/mil'}/></td>)}</tr>)}</tbody></table></div><p>Släp och andra tillgångar utan användningsmätare får periodkostnader men ingen automatisk mil-/timavvikelse. Ålder, uppdrag, verkstadsinsatser och kostnadsfördelning kan förklara skillnader.</p></>}
 {editor&&<div><h3>{editingId?'Ändra':'Ny'} bekräftad jämförelsegrupp</h3><label>Gruppnamn<input value={name} maxLength={120} onChange={e=>setName(e.target.value)} placeholder="Exempel: Tippbil 3-axlig"/></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{['Personbil','Lastbil','Släpvagn','Maskin'].map(c=><option key={c}>{c}</option>)}</select></label><label>Varför är dessa likvärdiga?<textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} placeholder="Storlek/viktklass, utrustning, ålder och jämförbar användning"/></label><p>Du bekräftar att fordonen är likvärdiga. Kända oförenliga fordonskategorier stoppas; saknad kategori måste bedömas manuellt. Fyra medlemmar med underlag behövs för avvikelsemarkering.</p><label>Sök medlemmar<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><fieldset><legend>{members.length} valda medlemmar</legend>{assets.filter(a=>[a.registration,a.description,a.model,a.department].join(' ').toLocaleLowerCase('sv-SE').includes(search.toLocaleLowerCase('sv-SE'))).map(a=><label key={a.id} className={styles.block}><input type="checkbox" checked={members.includes(a.id)} onChange={e=>setMembers(old=>e.target.checked?[...old,a.id]:old.filter(id=>id!==a.id))}/>{a.registration||a.description} · {a.model} · {a.department}</label>)}</fieldset><button disabled={saving||members.length<2||!name.trim()} onClick={save}>{saving?'Sparar…':'Bekräfta och spara grupp'}</button> <button className="secondary" disabled={saving} onClick={()=>setEditor(false)}>Avbryt</button></div>}
 </section>;
}
