"use client";
import {useEffect,useState} from "react";
type Item={id:string;type:string;name:string;identity_count:number;relation_count:number;created_at:string};
type Detail={object:{id:string;type:string;data:Record<string,unknown>};keys:Array<{id:string;type:string;value:string;confidence:number}>;relations:Array<{id:string;type:string;status:string;confidence:number;other_id:string;other_type:string;other_name:string|null;evidence:Record<string,unknown>}>};
export function HumlaIdentityRegister(){
 const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(""),[detailLoading,setDetailLoading]=useState(false);
 useEffect(()=>{if(!selected){setDetail(null);return;}const ctrl=new AbortController();setDetailLoading(true);setDetailError("");setDetail(null);fetch("/api/kpi/control-panel/identities/"+encodeURIComponent(selected),{signal:ctrl.signal,cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||"Kunde inte hämta objekt");setDetail(j)}).catch(e=>{if(e.name!=="AbortError")setDetailError(e.message)}).finally(()=>setDetailLoading(false));return()=>ctrl.abort()},[selected]);
 const [items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[type,setType]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[total,setTotal]=useState(0),[offset,setOffset]=useState(0);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);setError("");const q=new URLSearchParams({search,type,offset:String(offset)});
 fetch("/api/kpi/control-panel/identities?"+q,{signal:ctrl.signal,cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||"Kunde inte läsa identiteter");setItems(j.items||[]);setTotal(j.total||0)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>ctrl.abort()},[search,type,offset]);
 return <section><p>Humlas egna identiteter och verifierade relationer. En extern transaktion behöver inte vara matchad (CORE-002).</p><div className="dashboard-report-actions"><input aria-label="Sök identitet" placeholder="Sök namn, registrering eller Humla-ID" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/><select aria-label="Objekttyp" value={type} onChange={e=>{setType(e.target.value);setOffset(0)}}>{["","Vehicle","vehicle","Person","ExternalDriver","Project","Customer","Article","FuelTransaction","VehicleMeterReading"].map(t=><option key={t} value={t}>{t||"Alla typer"}</option>)}</select></div>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Hämtar…</p>}<p>{total} objekt</p><div className="table-wrap"><table><thead><tr><th>Objekt</th><th>Typ</th><th>Humla-ID</th><th>Identitetsnycklar</th><th>Relationer</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><button type="button" className="secondary" onClick={()=>setSelected(i.id)}>{i.name}</button></td><td>{i.type}</td><td><code>{i.id}</code></td><td>{i.identity_count}</td><td>{i.relation_count}</td></tr>)}</tbody></table></div><div className="dashboard-report-actions"><button disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-100))}>Föregående</button><button disabled={offset+100>=total||loading} onClick={()=>setOffset(offset+100)}>Nästa</button></div>{selected&&<section className="panel" aria-label="Objektdetaljer"><div className="dashboard-report-actions"><h3>Humla-objekt</h3><button type="button" onClick={()=>setSelected(null)}>Stäng</button></div>{detailLoading&&<p role="status">Hämtar detaljer…</p>}{detailError&&<p role="alert">{detailError}</p>}{detail&&<><p><strong>{detail.object.type}</strong> · <code>{detail.object.id}</code></p><h4>Externa identitetsnycklar</h4>{detail.keys.length===0?<p>Inga registrerade nycklar.</p>:<div className="table-wrap"><table><thead><tr><th>Typ</th><th>Värde</th><th>Säkerhet</th></tr></thead><tbody>{detail.keys.map(k=><tr key={k.id}><td>{k.type}</td><td>{k.value}</td><td>{Math.round(Number(k.confidence)*100)} %</td></tr>)}</tbody></table></div>}<h4>Relationer och historik</h4>{detail.relations.length===0?<p>Inga registrerade relationer. Det är tillåtet enligt CORE-002.</p>:<div className="table-wrap"><table><thead><tr><th>Koppling</th><th>Objekt</th><th>Status</th><th>Säkerhet</th><th>Underlag</th></tr></thead><tbody>{detail.relations.map(r=><tr key={r.id}><td>{r.type}</td><td><button type="button" className="secondary" onClick={()=>setSelected(r.other_id)}>{r.other_name||r.other_type}</button></td><td>{r.status}</td><td>{Math.round(Number(r.confidence)*100)} %</td><td><code>{JSON.stringify(r.evidence||{})}</code></td></tr>)}</tbody></table></div>}</>}</section>}</section>
}