'use client';
import {useEffect,useState} from 'react';
import type {InternalReport} from '@/lib/kpi/internal-transfers';
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'});
const statusLabel={new:'Nytt underlag',review:'Behöver granskas',changed:'Ändrat efter export',exported:'Exporterat',posted:'Omfört'};
const categoryLabel:Record<string,string>={transport:'Transport',material:'Material',tipp_deponi:'Tippavgift',unclassified:'Ej klassificerad'};
export function InternalTransfers({query,canManage}:{query:string;canManage:boolean}){
 const [report,setReport]=useState<InternalReport|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[page,setPage]=useState(0),[center,setCenter]=useState(new URLSearchParams(query).get('cost_center')??''),[reference,setReference]=useState(''),[fromCenter,setFromCenter]=useState(new URLSearchParams(query).get('from_center')??''),[toCenter,setToCenter]=useState(new URLSearchParams(query).get('to_center')??'');
 const scopedParams=new URLSearchParams(query);if(fromCenter)scopedParams.set('from_center',fromCenter);else scopedParams.delete('from_center');if(toCenter)scopedParams.set('to_center',toCenter);else scopedParams.delete('to_center');const reportQuery=scopedParams.toString();
 async function load(){setError('');try{const r=await fetch(`/api/kpi/internal-transfers?${reportQuery}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setReport(d);setSelected([]);}catch(e){setReport(null);setError(e instanceof Error?e.message:'Underlaget kunde inte läsas');}}
 useEffect(()=>{let ignore=false;setReport(null);setSelected([]);setError('');fetch(`/api/kpi/internal-transfers?${reportQuery}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!ignore){setReport(d);setSelected([]);setError('');}}).catch(e=>{if(!ignore){setReport(null);setError(String(e.message));}});return()=>{ignore=true;};},[reportQuery]);
 async function exportReport(){setBusy(true);setError('');try{const p=new URLSearchParams(reportQuery);p.set('download','report');if(center)p.set('cost_center',center);else p.delete('cost_center');const r=await fetch(`/api/kpi/internal-transfers?${p}`,{cache:'no-store'});if(!r.ok){const d=await r.json();throw Error(d.error);}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`humla-interna-fardigt-${p.get('from')}-${p.get('to')}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Exporten misslyckades');}finally{setBusy(false);}}
 async function act(action:'export'|'posted',id?:string,keys?:string[]){setBusy(true);setError('');try{const r=await fetch('/api/kpi/internal-transfers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='export'?{action,period:Object.fromEntries(new URLSearchParams(reportQuery)),keys:keys??selected}:{action,export_id:id,reference})});if(!r.ok){const d=await r.json();throw Error(d.error);}if(action==='export'){const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`humla-interna-${r.headers.get('X-Export-ID')}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}await load();}catch(e){setError(e instanceof Error?e.message:'Åtgärden misslyckades');}finally{setBusy(false);}}
 const rows=(report?.rows??[]).filter(r=>(!center||r.source_center===center||r.receiver_center===center)&&(status==='all'||r.status===status)&&(category==='all'||r.category===category)&&`${r.order} ${r.littra} ${r.vehicle} ${r.receiver_name??''} ${r.carrier_name??''} ${r.carrier_reference??''}`.toLowerCase().includes(search.toLowerCase()));
 const ready=rows.filter(r=>r.status==='new'&&r.ready);
 const totals=center?report?.totals_by_center?.[center]:report?.totals;
 const exports=Array.from(new Set((report?.rows??[]).filter(r=>r.status==='exported').map(r=>r.export_id).filter(Boolean))) as string[];
 return <section className="panel"><div className="panel-head"><div><span className="section-kicker">Ekonomins omföringsunderlag</span><h2>Interna körningar · Elleholms Maskin AB</h2></div><button className="secondary" onClick={load} disabled={busy}>Uppdatera underlag</button></div>
 <p>Samlad internintäkt per lastbil och lagerplats/projekt för omföring mellan kostnadsställena. Tippavgifter krediteras artikelns lagerplats/projekt enligt uppdelningen i Hubben. Projekt behöver inte vara kopplade. När mottagande kostnadsställe inte kan matchas används 10 – Entreprenad enligt standardregeln. Workifys benämning ”Lastbil” summeras separat som Inhyrda lastbilar. STENA ingår inte. Perioden följer artikeldatum; enbart fakturerade, entydigt kopplade rader kan exporteras.</p><p>Detta är ett separat omföringsunderlag: ingen intäkt läggs till i KPI och ingen bokföring sker automatiskt. Export och verifierad omföring har olika status. Endast period och kostnadsställe ärvs från Dashboarden; övriga urval görs här.</p>
 {error&&<p role="alert">{error}</p>}{!report&&!error&&<p role="status">Hämtar interna körningar…</p>}
 {report&&<><div className="period-form"><label>Från KST – kostnad<select value={fromCenter} onChange={e=>{setFromCenter(e.target.value);setCenter('');setPage(0);}}><option value="">Alla</option>{['10','20','30','40','50','60','90'].map(k=><option key={k}>{k}</option>)}</select></label><label>Till KST – intäkt<select value={toCenter} onChange={e=>{setToCenter(e.target.value);setCenter('');setPage(0);}}><option value="">Alla</option>{['10','20','30','40','50','60','90'].map(k=><option key={k}>{k}</option>)}</select></label><label>Sök order, littra eller intäktsbärare<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">Alla statusar</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Kategori<select value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="all">Alla kategorier</option>{Object.entries(categoryLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>KST – båda sidor<select value={center} onChange={e=>{setCenter(e.target.value);setPage(0);}}><option value="">Alla kostnadsställen</option>{['10','20','30','40','50','60','90'].map(k=><option key={k}>{k}</option>)}</select></label></div>
 <div className="panel-head"><h3>Samlad intäkt per intäktsbärare och kostnadsställe</h3><button className="secondary" disabled={busy||!totals?.rows} onClick={exportReport}>{busy?'Arbetar…':'Exportera färdig data till Excel'}</button></div><p>Hela periodens verifierade underlag, inklusive redan exporterade och omförda rader. Granskningsrader ingår inte i dessa belopp. En rad per intäktsbärare och par av kostnadsställen. Lastbilsintäkter summeras över uppdragsprojekten; tippavgifter summeras på respektive lagerplats/projekt. Exportera färdig data hämtar hela tabellens underlag för perioden och valt KST, inklusive tidigare exporterade och omförda rader. Rapportexporten ändrar ingen status. Exportknappen på en lastbilsrad skapar omföringsunderlag för gruppens nya rader. Status-, kategori- och sökfiltret nedan gäller endast orderdetaljerna.</p><div className="table-wrap"><table><thead><tr><th>Intäktsbärare</th><th>Från KST (kostnad)</th><th>Till KST (intäkt)</th><th>Transport</th><th>Material</th><th>Tippavgift</th><th>Total intäkt</th>{canManage&&<th>Omföringsunderlag</th>}</tr></thead><tbody><tr style={{fontWeight:700}}><td colSpan={3}>Summa · {totals?.rows??0} orderrader</td><td>{money.format(totals?.transport??0)}</td><td>{money.format(totals?.material??0)}</td><td>{money.format(totals?.tipp_deponi??0)}</td><td>{money.format(totals?.total??0)}</td>{canManage&&<td/>}</tr>{report.groups?.filter(g=>!center||g.source_center===center||g.receiver_center===center).map((g,i)=>{const keys=report.rows.filter(r=>r.ready&&r.status==='new'&&(r.carrier_type??'vehicle')===g.carrier_type&&(r.carrier_id??r.vehicle_id)===g.carrier_id&&r.source_center===g.source_center&&r.receiver_center===g.receiver_center).map(r=>r.source_key);return <tr key={i}><td><button onClick={()=>{setSearch(g.carrier_name);setPage(0);}}>{g.carrier_name}</button><small>{g.carrier_type==='project'?`Lagerplats/projekt ${g.carrier_reference??''}`:'Lastbil'}</small></td><td>{g.receiver_center}</td><td>{g.source_center}</td><td>{money.format(g.transport)}</td><td>{money.format(g.material)}</td><td>{money.format(g.tipp_deponi)}</td><td><strong>{money.format(g.total)}</strong></td>{canManage&&<td><button disabled={busy||!keys.length||keys.length>2000} onClick={()=>act('export',undefined,keys)}>Exportera nya rader ({keys.length})</button>{keys.length>2000&&<small>Välj en kortare period, högst 2 000 orderrader per export.</small>}</td>}</tr>;})}</tbody></table></div>
 <details><summary>Visa orderrader och granskningsunderlag</summary><p>{rows.length} av {report.count} rader · {ready.length} exportklara i urvalet · {selected.length} markerade. Saknade och motstridiga kopplingar visas nedan och hanteras i Kontrollpanelen. Högst 2 000 orderrader per export; välj en kortare period vid större urval.</p>
 {canManage&&<div className="actions"><button disabled={busy||!ready.length||ready.length>2000} onClick={()=>setSelected(ready.map(r=>r.source_key))}>Markera exportklara i urvalet</button><button className="primary" disabled={busy||!selected.length||selected.length>2000} onClick={()=>act('export')}>{busy?'Arbetar…':'Exportera markerade till Excel'}</button><button onClick={()=>setSelected([])} disabled={busy}>Avmarkera alla</button></div>}
 <div className="table-wrap"><table><thead><tr><th>Val</th><th>Datum / order</th><th>Mottagare / kostnads-KST</th><th>Intäktsbärare / intäkts-KST</th><th>Kategori / artikel</th><th>Belopp</th><th>Status / underlag</th></tr></thead><tbody>{rows.slice(page*100,(page+1)*100).map(r=><tr key={r.row_id}><td><input type="checkbox" aria-label={`Markera order ${r.order}, artikel ${r.article}`} disabled={!canManage||busy||r.status!=='new'||!r.ready} checked={selected.includes(r.source_key)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.source_key]:s.filter(k=>k!==r.source_key))}/></td><td><details><summary>{r.occurred_on} · {r.order}</summary><p>{r.description}</p><p>{r.comment}</p><p>{r.quantity??'–'} {r.unit} · Humla fordon: {r.vehicle_id??'saknas'} · Humla projekt: {r.receiver_id??'saknas'}</p><small>Källrad: {r.row_id}</small></details></td><td>{r.littra||'Littra saknas'}<small>{r.receiver_name??'Projekt ej verifierat'} · KST {r.receiver_center??'saknas'}</small>{r.receiver_rule&&<small>{r.receiver_rule}</small>}</td><td>{r.carrier_name??r.vehicle??'Intäktsbärare saknas'}<small>{r.carrier_type==='project'?`Lagerplats/projekt ${r.carrier_reference??''} · `:''}KST {r.source_center??'saknas'}</small>{r.vehicle_rule&&<small>{r.vehicle_rule}</small>}</td><td>{categoryLabel[r.category]??r.category}<small>{r.article}</small></td><td>{r.amount===null?'Belopp saknas':money.format(r.amount)}</td><td>{statusLabel[r.status]}<small>{r.review_reason}</small>{r.export_id&&<a href={`/api/kpi/internal-transfers?export_id=${r.export_id}`}>Hämta sparat underlag</a>}{r.booking_reference&&<small>Verifikation: {r.booking_reference}</small>}{r.receipt_url&&/^https:\/\//i.test(r.receipt_url)&&<a href={r.receipt_url} target="_blank" rel="noopener noreferrer">Öppna bilaga</a>}</td></tr>)}</tbody></table></div>
 <div className="actions"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Föregående</button><span>Sida {page+1} / {Math.max(1,Math.ceil(rows.length/100))}</span><button disabled={(page+1)*100>=rows.length} onClick={()=>setPage(p=>p+1)}>Nästa</button></div>
 </details>
 {canManage&&exports.length>0&&<details><summary>Markera redan bokfört underlag som omfört</summary><p>Gör detta först efter att ekonomi genomfört omföringen. Verifikationsreferens sparas tillsammans med tid och användare.</p><label>Verifikationsreferens<input value={reference} maxLength={200} onChange={e=>setReference(e.target.value)}/></label>{exports.map(id=><div className="actions" key={id}><a href={`/api/kpi/internal-transfers?export_id=${id}`}>Export {id}</a><button disabled={busy||!reference.trim()} onClick={()=>{if(confirm('Har ekonomi bokfört hela detta exporterade underlag?'))act('posted',id);}}>Markera hela exporten som omförd</button></div>)}</details>}
 </>}
 </section>;
}
