'use client';
import {useEffect,useState} from 'react';
import type {InternalReport} from '@/lib/kpi/internal-transfers';
const money=(n:number|null|undefined)=>n==null?'Underlag saknas':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(n);
const priceStatus:Record<string,string>={order_supplier_review:'Täkt behöver granskas',order_comment_review:'Flera täkter i kommentarer',customer_paid_review:'Uttaget på kund – kostnad oklar',special_material_review:'Specialprodukt – exakt pris saknas',receipt_price_list:'Kvitto + prislista',preliminary_source:'Täktpris – preliminärt',average_estimate:'Medelpris – preliminärt',missing_price:'Inköpspris saknas',ambiguous_material:'Fraktion behöver granskas',tipping_set_price:'Tippavgiftens satta pris används som kostnad',missing_tipping_price:'Tippkostnad saknas',not_applicable:'Ej materialinköp'};
export function InternalPurchaseEvidence({query}:{query:string}){
 const [report,setReport]=useState<InternalReport|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(0),[revision,setRevision]=useState(0);
 const p=new URLSearchParams(query);p.delete('view');const purchaseQuery=p.toString();
 useEffect(()=>{const controller=new AbortController();setReport(null);setError('');setPage(0);fetch(`/api/kpi/internal-transfers?${purchaseQuery}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Inköpsunderlaget kunde inte läsas');if(!controller.signal.aborted)setReport(d);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Inköpsunderlaget kunde inte läsas');});return()=>controller.abort();},[purchaseQuery,revision]);
 async function download(){setBusy(true);setError('');try{const params=new URLSearchParams(purchaseQuery);params.set('download','purchase');const r=await fetch(`/api/kpi/internal-transfers?${params}`,{cache:'no-store'});if(!r.ok){const d=await r.json();throw Error(d.error||'Exporten misslyckades');}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='humla-interna-inkopsunderlag.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Exporten misslyckades');}finally{setBusy(false);}}
 const rows=report?.rows.filter(r=>r.category==='material'||r.category==='tipp_deponi')??[];
 return <section aria-label="Inköpspriser – arbetsunderlag"><p>Vi fortsätter med inköpspriser, kvitton och prislistor här. Detta är ett separat arbetsunderlag för hela periodens interna material- och tipprader, även andra KST-par och granskningsrader. Det ändrar inte de två omföringssummorna ovan. Saknade priser visas inte som noll.</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>setRevision(n=>n+1)}>Uppdatera inköpsunderlag</button><button className="secondary" disabled={busy||!report} onClick={()=>void download()}>Exportera inköpsunderlag till Excel</button></div>{error&&<p role="alert">{error}</p>}{!report&&!error&&<p role="status">Hämtar inköpspriser…</p>}{report&&<><p>{report.purchase_basis}</p><p>{rows.length} material- och tipprader. Preliminär inköpskostnad för hela raden är inte samma sak som kostnaden för kvittomatchad mängd. Excel-exporten behåller alla interna orderrader och deras prisunderlag.</p><div className="table-wrap"><table><thead><tr><th>Datum / order</th><th>Artikel / material</th><th>Mängd</th><th>Inköpspris / enhet</th><th>Beräknat inköp</th><th>Prisstatus och underlag</th></tr></thead><tbody>{rows.slice(page*100,(page+1)*100).map(r=><tr key={r.row_id}><td>{r.occurred_on}<small>{r.order} · {r.littra}</small></td><td>{r.article}<small>{r.description}</small></td><td>{r.purchase?.quantity??r.quantity??'Underlag saknas'} {r.purchase?.unit??r.unit}</td><td>{money(r.purchase?.rate)}</td><td>{money(r.purchase?.amount)}{r.purchase?.receipt_cost!=null&&<small>Kvittomatchad mängd: {money(r.purchase.receipt_cost)}</small>}</td><td><details><summary>{priceStatus[r.purchase?.status??'missing_price']??r.purchase?.status}</summary><p>{r.purchase?.supplier??'Täkt ej fastställd'} · {r.purchase?.fraction??'Fraktion saknas'}</p><p>{r.purchase?.price_source}</p><p>{r.purchase?.note}</p>{r.purchase?.price_sources?.map((s,i)=><p key={i}>{s.supplier}: {money(s.price)} · {s.source}</p>)}<p>Kvitto: {r.purchase?.receipt_reference??'Saknas'} · {r.purchase?.receipt_read_status??'Ej läst'}</p>{r.receipt_url&&/^https:\/\//i.test(r.receipt_url)&&<a href={r.receipt_url} target="_blank" rel="noopener noreferrer">Öppna bilaga</a>}</details></td></tr>)}</tbody></table></div><div className="actions"><button disabled={page===0} onClick={()=>setPage(n=>n-1)}>Föregående</button><span>Sida {page+1} / {Math.max(1,Math.ceil(rows.length/100))}</span><button disabled={(page+1)*100>=rows.length} onClick={()=>setPage(n=>n+1)}>Nästa</button></div></>}</section>;
}
