'use client';
import {Fragment,useState} from 'react';
export type EconomicUnit={key:string;label:string;revenue:number;cost:number;result:number;rows:number;children:Array<{key:string;label:string;vehicle:string|null;project:string|null;revenue:number;cost:number;result:number;rows:number}>};
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0});
export function KpiEconomicUnits({units,query,totals,canManage}:{units:EconomicUnit[];query:string;totals:{revenue:number;cost:number;result:number};canManage:boolean}){
 const [expanded,setExpanded]=useState<string[]>([]);
 function href(unit:string,child?:EconomicUnit['children'][number],dashboard=false){const p=new URLSearchParams(query);p.set('unit',unit);p.delete('vehicle');p.delete('project');if(child?.vehicle)p.set('vehicle',child.vehicle);else if(child?.project)p.set('project',child.project);p.set(dashboard?'view':'level',dashboard?'kpi':'project');return (dashboard?'/kpi?':'/kpi/analys?')+p;}
 return <article className="panel"><h2>Ekonomiska enheter</h2><p>Kopplad bil, släp och övriga delar visas tillsammans. Fäll ut en enhet för delarna eller välj Visa endast för att filtrera hela KPI-vyn.</p><div className="table-wrap"><table><thead><tr><th>Enhet / ingående objekt</th><th>Omsättning</th><th>Kostnad</th><th>Resultat</th><th>Urval</th></tr></thead><tbody>{units.map(u=><Fragment key={u.key}><tr className="economic-parent"><td><button className="unit-expand" aria-expanded={expanded.includes(u.key)} aria-label={`${expanded.includes(u.key)?'Fäll ihop':'Visa delar i'} ${u.label}`} onClick={()=>setExpanded(s=>s.includes(u.key)?s.filter(k=>k!==u.key):[...s,u.key])}>{expanded.includes(u.key)?'−':'+'} {u.label}</button><small>{u.rows} transaktioner · {u.children.length} delar i urvalet</small></td><td>{money.format(u.revenue)}</td><td>{money.format(u.cost)}</td><td><strong>{money.format(u.result)}</strong></td><td><a href={href(u.key,undefined,true)}>Visa endast</a> · <a href={href(u.key)}>Detaljer</a></td></tr>{expanded.includes(u.key)&&u.children.map(c=><tr className="economic-child" key={c.key}><td><a href={href(u.key,c)}>{c.label}</a><small>{c.vehicle?'Fordon':'Projekt / ej fördelat'} · {c.rows} rader</small></td><td>{money.format(c.revenue)}</td><td>{money.format(c.cost)}</td><td>{money.format(c.result)}</td><td><a href={href(u.key,c)}>Transaktioner</a></td></tr>)}</Fragment>)}</tbody><tfoot><tr><th>Total för urvalet</th><td>{money.format(totals.revenue)}</td><td>{money.format(totals.cost)}</td><td>{money.format(totals.result)}</td><td/></tr></tfoot></table></div>{canManage&&<a href={`/kpi/kontrollpanel?${query}`}>Matcha ofördelade poster i kontrollpanelen →</a>}<p>Delraderna ingår redan i enhetens total. Att fälla ut dem ändrar inte urvalet.</p></article>;
}
