'use client';
import {useId,useRef,useState} from 'react';
import type {Item} from './kpi-match-workbench';
import {UnitHistoryCompletion} from './unit-history-completion';
export type InlineUnit={id:string;name:string;registrations:string[];projects:string[];employees:string[];revision:number;valid_from:string;enabled?:boolean;initial_version?:{registrations?:string[];projects?:string[];employees?:string[];valid_from?:string;main_vehicle?:string}|null};
type Candidate={name:string;registration:string|null;projects:string[]};
export function KpiRowResolution({item,units,candidates,groups,onMap,onClose,onBusy}:{item:Item;units:InlineUnit[];candidates:Candidate[];groups:Array<{id:string;name:string}>;onMap:(unit:string)=>void;onClose:()=>void;onBusy:(busy:boolean)=>void}){
 const known=(item.vehicles??[]).filter(r=>/^[A-Z]{3}[0-9]{2}[A-Z0-9]$/.test(r));
 const [type,setType]=useState<'vehicle'|'project'>(known.length?'vehicle':'project'),[name,setName]=useState(item.project_name??''),[vehicle,setVehicle]=useState(known[0]??''),[from,setFrom]=useState(item.first_date),[group,setGroup]=useState(groups.find(g=>item&&'current_groups'in item&&(item.current_groups as string[]).includes(g.name))?.id??''),[projects,setProjects]=useState<string[]>([]),[extraProjects,setExtraProjects]=useState(''),[history,setHistory]=useState<InlineUnit|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[created,setCreated]=useState<{id:string;name:string}|null>(null);
 const saving=useRef(false);const listId=useId();
 const related=units.filter(u=>u.enabled!==false&&(u.registrations.some(r=>known.includes(r)||r===vehicle)||u.projects.some(p=>item.projects?.some(x=>x.reference===p))));
 const availableProjects=[...new Set([...(item.projects??[]).map(p=>p.reference),...candidates.filter(c=>c.registration===vehicle&&!!vehicle).flatMap(c=>c.projects)])];
 const chosenProjects=[...new Set([...projects,...extraProjects.split(/[\n,;]/).map(p=>p.trim()).filter(Boolean)])];
 const unitName=type==='vehicle'?vehicle:name.trim();
 async function create(e:React.FormEvent){e.preventDefault();if(saving.current)return;if(type==='project'&&!chosenProjects.length){setMessage('Välj eller ange minst ett projekt för enheten.');return}saving.current=true;setBusy(true);onBusy(true);setMessage('');try{const r=await fetch('/api/kpi/units',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quick_create:true,name:unitName,main_vehicle:type==='vehicle'?vehicle:'',unit_type:type,registrations:type==='vehicle'?vehicle:'',projects:chosenProjects.join('\n'),employees:'',business_group_id:group||null,valid_from:from,valid_to:null,enabled:true,finalize_setup:false}),signal:AbortSignal.timeout(30000)});const j=await r.json();if(!r.ok)throw Error(j.error);setCreated({id:j.id,name:unitName});setMessage(unitName+' är skapad. Koppla posten nedan och förhandsgranska mappningen.');window.dispatchEvent(new Event('kpi-units-updated'));}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte skapa enheten')}finally{saving.current=false;setBusy(false);onBusy(false)}}
 if(history)return <UnitHistoryCompletion unit={history} initialFrom={item.first_date} onBusyChange={onBusy} onClose={()=>{setHistory(null);onClose()}}/>;
 return <section className="panel"><h3>Åtgärda här · {item.description??item.reference}</h3>{related.length>0&&<><p>Befintliga enheter som matchar postens fordon eller projekt:</p>{related.map(u=><div key={u.id} style={{marginBottom:10}}><strong>{u.name}</strong><p>{u.registrations.length?u.registrations.join(' + '):'Projekt '+u.projects.join(', ')} · gäller från {u.initial_version?.valid_from??u.valid_from}</p><button type="button" className="secondary" disabled={busy} onClick={()=>onMap(u.id)}>Använd {u.name} på posten</button>{u.initial_version?.valid_from&&item.first_date<u.initial_version.valid_from&&<button type="button" className="secondary" disabled={busy} onClick={()=>setHistory(u)}>Komplettera historiken här</button>}</div>)}</>}{!created&&<details open={related.length===0}><summary>Skapa saknad ekonomisk enhet här</summary><form onSubmit={create}><fieldset disabled={busy}><label>Enhetstyp<select value={type} onChange={e=>setType(e.target.value as 'vehicle'|'project')}><option value="project">Verksamhet / material / projekt</option><option value="vehicle">Fordon</option></select></label>{type==='vehicle'?<label>Huvudfordon<input required pattern="[A-Z]{3}[0-9]{2}[A-Z0-9]" maxLength={6} value={vehicle} onChange={e=>{setVehicle(e.target.value.trim().toUpperCase());setProjects([])}} list={listId}/></label>:<><label>Enhetsnamn<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Returträ eller Schakt"/></label><p>Kopplas via projekt. Inget registreringsnummer behövs.</p></>}<datalist id={listId}>{known.map(r=><option key={r} value={r}/>)}</datalist><label>Gäller från<input required type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Verksamhetsgrupp<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Behåll projektens grupper</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{availableProjects.length>0&&<fieldset><legend>Projekt som hör till enheten{type==='vehicle'?' · valfritt':''}</legend>{availableProjects.map(p=><label key={p}><input type="checkbox" checked={projects.includes(p)} onChange={e=>setProjects(s=>e.target.checked?[...s,p]:s.filter(x=>x!==p))}/>{p}</label>)}</fieldset>}<label>Andra projektnummer · ett per rad<textarea value={extraProjects} onChange={e=>setExtraProjects(e.target.value)} placeholder="Ex. 5012"/></label><button type="submit" className="secondary" disabled={!unitName||(type==='project'&&!chosenProjects.length)||(type==='vehicle'&&related.some(u=>u.registrations.includes(vehicle)))}>{busy?'Skapar…':'Skapa enheten här'}</button></fieldset></form></details>}{created&&<button type="button" className="primary" disabled={busy} onClick={()=>onMap(created.id)}>Koppla posten till {created.name}</button>}{message&&<p role="status">{message}</p>}<button type="button" className="secondary" disabled={busy} onClick={onClose}>Stäng åtgärden</button></section>;
}
