'use client';
import {Fragment,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
export type EconomicUnit={key:string;label:string;revenue:number;cost:number;result:number;rows:number;
 cost_categories?:Record<string,number|null>;margin_pct?:number|null;worked_hours?:number|null;productive_hours?:number|null;
 billing_percent?:number|null;utilization?:number|null;occupied_hours?:number|null;available_hours?:number|null;
 revenue_per_hour?:number|null;cost_per_hour?:number|null;distance_mil?:number|null;cost_per_mil?:number|null;
 revenue_per_mil?:number|null;fuel_cost_per_mil?:number|null;fuel_liters_per_mil?:number|null;
 children:Array<{key:string;label:string;vehicle:string|null;project:string|null;revenue:number;cost:number;result:number;rows:number}>};
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0});
const num=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:1});
const costs=[['personnel','Personal'],['fuel','Bränsle'],['service_repair','Service & Rep'],['fixed','Fasta'],['depreciation','Avskrivning'],['material','Material'],['tipp_deponi','Tipp/Deponi'],['hired','Inhyrda'],['other','Övrigt']] as const;
const ratios=[['margin_pct','Marginal','%'],['worked_hours','Arbetad tid','h'],['billing_percent','Debiteringsgrad*','%'],['utilization','Beläggningsgrad','%'],['revenue_per_hour','Intäkt / h','kr'],['cost_per_hour','Kostnad / h','kr'],['distance_mil','Körsträcka','mil'],['cost_per_mil','Kostnad / mil','kr'],['revenue_per_mil','Intäkt / mil','kr'],['fuel_cost_per_mil','Bränsle / mil','kr'],['fuel_liters_per_mil','Förbrukning / mil','l']] as const;
function value(n:number|null|undefined,suffix:string){return n==null?'–':num.format(n)+' '+suffix;}
export function KpiEconomicUnits({units,query,totals,canManage,groups=[]}:{units:EconomicUnit[];query:string;totals:{revenue:number;cost:number;result:number};canManage:boolean;groups:string[]}){
 const [expanded,setExpanded]=useState<string[]>([]),[sort,setSort]=useState('label');
 const [pending,startTransition]=useTransition();const router=useRouter();const selectedGroup=new URLSearchParams(query).get('group')??'';
 const ordered=[...units].sort((a,b)=>sort==='label'?a.label.localeCompare(b.label,'sv'):((b[sort as keyof EconomicUnit] as number|null)??-Infinity)-((a[sort as keyof EconomicUnit] as number|null)??-Infinity));
 function filterGroup(group:string){const p=new URLSearchParams(query);p.set('view','kpi');if(group)p.set('group',group);else p.delete('group');p.delete('unit');p.delete('vehicle');p.delete('project');startTransition(()=>router.push('/kpi?'+p));}
 function href(unit:string,child?:EconomicUnit['children'][number],dashboard=false,category?:string){const p=new URLSearchParams(query);p.set('unit',unit);p.delete('vehicle');p.delete('project');if(child?.vehicle)p.set('vehicle',child.vehicle);else if(child?.project)p.set('project',child.project);p.set(dashboard?'view':'level',dashboard?'kpi':'project');if(category){p.set('category',category);p.set('kind','cost');}return (dashboard?'/kpi?':'/kpi/analys?')+p;}
 const columns=5+costs.length+ratios.length;
 return <article className="panel economic-units" aria-busy={pending}><h2>Ekonomiska enheter</h2>
 <div className="unit-table-controls"><label>Verksamhetsgrupp<select value={selectedGroup} disabled={pending} onChange={e=>filterGroup(e.target.value)}><option value="">Alla verksamhetsgrupper</option>{Array.from(new Set([...groups,...(selectedGroup?[selectedGroup]:[])])).map(g=><option key={g} value={g}>{g}</option>)}</select></label>
 <label>Sortera enheter<select value={sort} onChange={e=>setSort(e.target.value)}><option value="label">Namn</option><option value="revenue">Omsättning, högst först</option><option value="result">Resultat, högst först</option><option value="cost">Kostnad, högst först</option><option value="utilization">Beläggning, högst först</option><option value="cost_per_mil">Kostnad per mil, högst först</option></select></label><span role="status">{pending?'Hämtar gruppens underlag…':`${units.length} enheter i urvalet`}</span></div>
 <p>Gruppvalet filtrerar hela KPI-vyn och totalsummorna. Tabellen kan scrollas i sidled. Fäll ut en enhet för ingående delar eller välj Visa endast.</p>
 <div className="table-wrap unit-metrics-table"><table><thead><tr><th>Enhet / ingående objekt</th><th>Omsättning</th><th>Total kostnad</th><th>Resultat</th>{costs.map(([k,l])=><th key={k}>{l}</th>)}{ratios.map(([k,l,s])=><th key={k}>{l}{['cost_per_mil','fuel_cost_per_mil'].includes(k)?` (${s})`:''}</th>)}<th>Urval</th></tr></thead><tbody>{ordered.map(u=><Fragment key={u.key}>
 <tr className="economic-parent"><td><button className="unit-expand" aria-expanded={expanded.includes(u.key)} aria-label={`${expanded.includes(u.key)?'Fäll ihop':'Visa delar i'} ${u.label}`} onClick={()=>setExpanded(s=>s.includes(u.key)?s.filter(k=>k!==u.key):[...s,u.key])}>{expanded.includes(u.key)?'−':'+'} {u.label}</button><small>{u.rows} transaktioner · {u.children.length} delar</small></td><td>{money.format(u.revenue)}</td><td>{money.format(u.cost)}</td><td><strong>{money.format(u.result)}</strong></td>
 {costs.map(([k,l])=><td key={k}><a href={href(u.key,undefined,false,k)} aria-label={`${l} för ${u.label}`}>{u.cost_categories?.[k]==null?'–':money.format(u.cost_categories[k]!)}</a></td>)}
 {ratios.map(([k,,s])=><td key={k} title={u[k]==null?'Verifierat underlag saknas för urvalet':undefined}>{value(u[k],s)}</td>)}
 <td><a href={href(u.key,undefined,true)}>Visa endast</a> · <a href={href(u.key)}>Detaljer</a></td></tr>
 {expanded.includes(u.key)&&<tr className="economic-unit-basis"><td colSpan={columns}><strong>Underlag för {u.label}</strong><p>Beläggning: {value(u.occupied_hours,'h')} av {value(u.available_hours,'h')} tillgänglig tid. Intäktskopplad tid: {value(u.productive_hours,'h')} av {value(u.worked_hours,'h')}. Milnyckeltal använder hela enhetens ekonomi och huvudfordonets sträcka.</p>{u.distance_mil==null&&<p>Körsträcka saknas för hela urvalet. <a href={`/kpi/korstracka?${query}`}>Visa eller importera periodens körsträcka →</a></p>}</td></tr>}
 {expanded.includes(u.key)&&u.children.map(c=><tr className="economic-child" key={c.key}><td><a href={href(u.key,c)}>{c.label}</a><small>{c.vehicle?'Fordon':'Projekt / ej fördelat'} · {c.rows} rader</small></td><td>{money.format(c.revenue)}</td><td>{money.format(c.cost)}</td><td>{money.format(c.result)}</td><td colSpan={costs.length+ratios.length}>Ingår redan i enhetens total · <a href={href(u.key,c)}>Visa underliggande kostnader och transaktioner</a></td><td><a href={href(u.key,c)}>Transaktioner</a></td></tr>)}
 </Fragment>)}</tbody><tfoot><tr><th>Total för urvalet</th><td>{money.format(totals.revenue)}</td><td>{money.format(totals.cost)}</td><td>{money.format(totals.result)}</td><td colSpan={costs.length+ratios.length}>Beräknat i Humla Hub. Procent och kvoter summeras inte.</td><td/></tr></tfoot></table></div>
 <p>* Debiteringsgrad visar intäktskopplad TransPA-tid / arbetad TransPA-tid, samma grund som tidigare. Det är inte en verifierad andel fakturerade timmar. Förbrukning i l/mil inväntar verifierad bränslevolym.</p>
 {canManage&&<a href={`/kpi/kontrollpanel?${query}`}>Matcha ofördelade poster i kontrollpanelen →</a>}<p>Streck betyder att underlag saknas. Delraderna ingår redan i enhetens total. Att fälla ut dem ändrar inte urvalet.</p></article>;
}
