'use client';
import {useEffect,useMemo,useState,type DragEvent} from 'react';
import {useSearchParams} from 'next/navigation';
type Item={source:string;kind:string;reference_type:string;reference:string;description:string|null;project_name?:string|null;rows:number;amount:number;first_date:string;last_date:string;vehicles?:string[];register_vehicles?:string[][];projects?:Array<{reference:string;name:string|null}>;accounts?:string[];suppliers?:string[];samples?:Array<{occurred_on:string;amount:number;project:string|null;project_name:string|null;vehicle:string|null;account:string|null;description:string|null;file_name:string|null;row_number:number|null;original:Record<string,unknown>}>};
type Queue={items:Item[];total_groups:number;rows:number;groups:Array<{name:string}>;units:Array<{id:string;name:string}>;cost_centers:Array<{code:string;name:string}>;history:Array<{dimension:string;source:string;reference:string;target:string;valid_from:string;valid_to:string|null;reason:string}>};
type Registry={candidates:Array<{name:string;registration:string|null;projects:string[]}>;units:Array<{name:string;registrations:string[];projects:string[]}>};
const dimensions={cost_center:'Kostnadsställe',group:'Verksamhetsgrupp',unit:'Ekonomisk enhet',vehicle:'Fordon',category:'Kategori',shared_cost:'Gemensamma kostnadsprojekt'};
const categories={personnel:'Personal',fuel:'Bränsle',service_repair:'Service & Rep',fixed:'Fasta kostnader',depreciation:'Avskrivning',material:'Material',tipp_deponi:'Tipp / Deponi',hired:'Inhyrda',other:'Övrigt',transport:'Transportintäkt',tipp:'Tippintäkt'};
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:2});
const key=(i:Item)=>JSON.stringify([i.source,i.kind,i.reference_type,i.reference]);
function MatchEvidence({item,from,to}:{item:Item;from:string;to:string}){
 const registered=[...new Set(item.register_vehicles?.flat()??[])].filter(Boolean);
 const examples=(field:string)=>[...new Set((item.samples??[]).map(s=>s.original?.[field]).filter(v=>v!==undefined&&v!==null&&v!==''))].map(String).join(', ');
 const originalDocument=(value:unknown)=>{if(typeof value!=='string')return null;try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='app.workifyit.com'?u.href:null}catch{return null}};
 const projectLink=(project:string)=>'/kpi/analys?'+new URLSearchParams({from,to,source:item.source,kind:item.kind,project,level:'transaction'});
 return <div className="match-evidence">
 <small><strong>Kopplat fordon:</strong> {item.vehicles?.length?item.vehicles.join(', '):'Ingen verifierad fordonskoppling'}</small>
 {registered.length>0&&<small><strong>Fordon i daterat projektregister:</strong> {registered.join(', ')}</small>}
 {item.projects?.map(p=><small key={p.reference}><strong>Projekt:</strong> <a href={projectLink(p.reference)} target="_blank" rel="noopener noreferrer">{p.reference}{p.name?' – '+p.name:''}</a></small>)}
 {Boolean(item.accounts?.length)&&<small><strong>Konto:</strong> {item.accounts?.join(', ')}</small>}
 {Boolean(item.suppliers?.length)&&<small><strong>Leverantör:</strong> {item.suppliers?.join(', ')}</small>}
 {['Ordernummer','Kundnamn','Littranummer','Artikelnummer','Rubrik'].filter(field=>examples(field)).map(field=><small key={field}><strong>{({Ordernummer:'Order',Kundnamn:'Kund',Littranummer:'Littra / projekt',Artikelnummer:'Artikel',Rubrik:'Uppdrag'} as Record<string,string>)[field]} (exempel):</strong> {examples(field)}</small>)}
 <details><summary>Visa originalunderlag · {item.samples?.length??0} exempel</summary>
 <p>Upp till fem rader visas här. Projektlänken öppnar projektets transaktioner. Saknas fordonsuppgift och verifierad koppling behöver posten kontrolleras före matchning.</p>
 {item.samples?.map((s,index)=><article key={index}><h4>{s.occurred_on} · {s.amount==null?'Belopp saknas':money.format(s.amount)}</h4><p>{s.description??'Beskrivning saknas'}{s.project&&<> · <a href={projectLink(s.project)} target="_blank" rel="noopener noreferrer">Projekt {s.project}{s.project_name?' – '+s.project_name:''}</a></>}</p><small>Källfil: {s.file_name??item.source} · rad {s.row_number??'saknas'}</small>{originalDocument(s.original?.FilUrl)&&<p><a href={originalDocument(s.original.FilUrl)!} target="_blank" rel="noopener noreferrer">Öppna originaldokument i Workify</a></p>}<dl>{Object.entries(s.original??{}).filter(([k,v])=>!k.startsWith('_humla')&&v!==null&&v!=='').map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></article>)}
 </details></div>;
}
export function KpiMatchWorkbench(){
 const params=useSearchParams();const today=new Date(),year=Number(params.get('fiscal_year'))||(today.getMonth()<8?today.getFullYear()-1:today.getFullYear());
 const [from,setFrom]=useState(params.get('from')||`${year}-09-01`),[to,setTo]=useState(params.get('to')||`${year+1}-08-31`),[dimension,setDimension]=useState('cost_center'),[scope,setScope]=useState('project'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const [request,setRequest]=useState(()=>new URLSearchParams({from,to,dimension,reference_type:scope,search,page:'0'}).toString()),[revision,setRevision]=useState(0),[data,setData]=useState<Queue|null>(null),[selected,setSelected]=useState<string[]>([]),[target,setTarget]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dragOver,setDragOver]=useState(false);
 const [registry,setRegistry]=useState<Registry|null>(null),[registryError,setRegistryError]=useState(''),[registrySearch,setRegistrySearch]=useState(''),[lookup,setLookup]=useState('');
 useEffect(()=>{
  const controller=new AbortController();
  fetch('/api/kpi/units',{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setRegistry({candidates:j.candidates??[],units:j.units??[]});}).catch(e=>{if(e.name!=='AbortError')setRegistryError(e.message);});
  return ()=>controller.abort();
 },[]);
 const registryOptions=useMemo(()=>{
  const projects=new Map<string,Set<string>>(),vehicles=new Map<string,Set<string>>();
  for(const object of [...(registry?.candidates??[]).map(c=>({...c,registrations:c.registration?[c.registration]:[]})),...(registry?.units??[])]){
   for(const project of object.projects){if(!projects.has(project))projects.set(project,new Set());projects.get(project)!.add(object.name);}
   for(const registration of object.registrations){if(!vehicles.has(registration))vehicles.set(registration,new Set());for(const project of object.projects)vehicles.get(registration)!.add(project);}
  }
  return {projects:[...projects].map(([value,names])=>({value,label:`${value} – ${[...names].join(' / ')}`})).sort((a,b)=>a.label.localeCompare(b.label,'sv',{numeric:true})),vehicles:[...vehicles].map(([value,projects])=>({value,label:`${value}${projects.size?' – Projekt '+[...projects].join(', '):''}`})).sort((a,b)=>a.label.localeCompare(b.label,'sv',{numeric:true}))};
 },[registry]);
 useEffect(()=>{
  const controller=new AbortController();
  fetch('/api/kpi/matching?'+request,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}).catch(e=>{if(e.name!=='AbortError')setMessage(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return ()=>controller.abort();
 },[request,revision]);
 function load(nextPage=0,nextDimension=dimension,nextScope=scope,nextSearch=search){setLoading(true);setData(null);setSelected([]);setMessage('');setPage(nextPage);setRequest(new URLSearchParams({from,to,dimension:nextDimension,reference_type:nextScope,search:nextSearch,page:String(nextPage)}).toString());setRevision(v=>v+1);}
 function chooseDimension(value:string){setDimension(value);setTarget('');const nextScope=value==='shared_cost'?'project':scope;setScope(nextScope);load(0,value,nextScope);}
 function toggle(item:Item){const id=key(item);setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 function drop(e:DragEvent){e.preventDefault();setDragOver(false);const id=e.dataTransfer.getData('application/x-humla-match');if(data?.items.some(i=>key(i)===id))setSelected(s=>s.includes(id)?s:[...s,id]);}
 async function save(form:FormData){
  if(saving||loading)return;setSaving(true);setMessage('');
  try{
   const items=data?.items.filter(i=>selected.includes(key(i))).map(({source,kind,reference_type,reference})=>({source,kind,reference_type,reference}))??[];
   if(!items.length||!target)throw Error('Välj poster och mottagare.');
   if(dimension==='shared_cost'&&target!=='none'&&form.get('equal_share')!=='on')throw Error('Kryssa i jämn fördelning för att aktivera regeln.');
   const r=await fetch('/api/kpi/matching',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,dimension,target,from:form.get('valid_from'),to:form.get('valid_to'),reason:form.get('reason')}),signal:AbortSignal.timeout(60000)});const j=await r.json();if(!r.ok)throw Error(j.error);
   load(page);setMessage(`${j.saved} kopplingar sparade i Hubben. Öppna rapporten för omräknade totaler.`);
  }catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara');}finally{setSaving(false);}
 }
 const busy=loading||saving;
 const matchesRegistry=(label:string)=>label.toLocaleLowerCase('sv').includes(registrySearch.trim().toLocaleLowerCase('sv'));
 const choices=dimension==='shared_cost'?[{value:'*',label:'Alla ekonomiska enheter'},...(data?.groups.map(g=>({value:g.name,label:`Enheter i ${g.name}`}))??[]),{value:'none',label:'Avsluta fördelning från valt datum'}]:dimension==='cost_center'?data?.cost_centers.map(c=>({value:c.code,label:`${c.code} – ${c.name}`})):dimension==='group'?data?.groups.map(g=>({value:g.name,label:g.name})):dimension==='unit'?data?.units.map(u=>({value:u.id,label:u.name})):dimension==='category'?Object.entries(categories).map(([value,label])=>({value,label})):[];
 return <section className="panel matching-workbench"><h2>Matcha och fördela kostnader</h2><p>Välj vad som saknas, sök och markera poster. Dra en post till matchningsrutan eller använd kryssrutorna. Beloppen räknas i Hubben.</p>
 <div className="matching-filters"><label>Koppling eller fördelning<select value={dimension} disabled={saving} onChange={e=>chooseDimension(e.target.value)}>{Object.entries(dimensions).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Samla poster efter<select value={scope} disabled={saving||dimension==='shared_cost'} onChange={e=>{setScope(e.target.value);load(0,dimension,e.target.value)}}><option value="project">Projekt</option><option value="vehicle">Fordon</option><option value="article">Artikel</option><option value="account">Konto</option><option value="fact">Enskild transaktion</option></select></label><label>Rapport från<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Rapport till<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 <div className="matching-filters"><label>Sök i projekt-/fordonslistan<input type="search" value={registrySearch} disabled={saving} onChange={e=>setRegistrySearch(e.target.value)} placeholder="Projektnummer, projektnamn eller regnummer"/></label><label>Välj Projekt/Regnummer<select value={lookup} disabled={saving||!registry} onChange={e=>{const value=e.target.value;setLookup(value);const nextSearch=value.slice(value.indexOf(':')+1);setSearch(nextSearch);load(0,dimension,scope,nextSearch)}}><option value="">Alla · återställ sökningen</option>{lookup&&!registryOptions.projects.concat(registryOptions.vehicles).some(o=>matchesRegistry(o.label)&&(lookup==='project:'+o.value||lookup==='vehicle:'+o.value))&&<option value={lookup}>{lookup.slice(lookup.indexOf(':')+1)} · valt</option>}<optgroup label="Projekt">{registryOptions.projects.filter(o=>matchesRegistry(o.label)).map(o=><option key={o.value} value={'project:'+o.value}>{o.label}</option>)}</optgroup><optgroup label="Regnummer">{registryOptions.vehicles.filter(o=>matchesRegistry(o.label)).map(o=><option key={o.value} value={'vehicle:'+o.value}>{o.label}</option>)}</optgroup></select></label></div>
 {registryError&&<p role="status">Projekt-/fordonslistan kunde inte hämtas: {registryError}. Du kan fortfarande söka och skriva regnummer manuellt.</p>}
 <form onSubmit={e=>{e.preventDefault();setLookup('');load()}} className="matching-search"><label>Sök poster<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Projekt, konto, regnummer eller beskrivning"/></label><button className="secondary" disabled={saving}>Sök och uppdatera</button></form>
 {message&&<p role="status">{message}</p>}{loading&&<p role="status">Hämtar matchningskö från Humla Hub…</p>}
 <div className="matching-columns"><section><p>{data?`${data.total_groups} referenser · ${data.rows} transaktioner · högst 100 per sida`:''}</p><div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Markera alla på sidan" disabled={busy||!data?.items.length} checked={Boolean(data?.items.length)&&selected.length===data?.items.length} onChange={e=>setSelected(e.target.checked?data?.items.map(key)??[]:[])}/></th><th>Referens / original</th><th>Källa</th><th>Rader</th><th>Belopp</th></tr></thead><tbody>{data?.items.map(i=><tr key={key(i)} draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('application/x-humla-match',key(i));e.dataTransfer.effectAllowed='copy'}}><td><input type="checkbox" aria-label={`Markera ${i.reference}`} checked={selected.includes(key(i))} disabled={busy} onChange={()=>toggle(i)}/></td><td><strong>{i.reference_type==='fact'?'Enskild transaktion':i.reference}</strong>{i.project_name&&<small>{i.project_name}</small>}<small>{i.description??'Ingen beskrivning'}</small><small>{i.first_date} – {i.last_date}</small><MatchEvidence item={i} from={from} to={to}/></td><td>{i.source}<small>{i.kind==='cost'?'Kostnad':'Intäkt'}</small></td><td>{i.rows}</td><td>{money.format(i.amount??0)}</td></tr>)}</tbody></table></div>{data?.items.length===0&&<p>Inga poster matchar detta urval.</p>}<div className="matching-pagination"><button disabled={busy||page===0} onClick={()=>load(page-1)}>Föregående</button><span>Sida {page+1}</span><button disabled={busy||!data||(page+1)*100>=data.total_groups} onClick={()=>load(page+1)}>Nästa</button></div></section>
 <form action={save} className={'matching-target'+(dragOver?' drag-over':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-humla-match')){e.preventDefault();setDragOver(true)}}} onDragLeave={()=>setDragOver(false)} onDrop={drop}><fieldset disabled={busy}><h3>Matcha {selected.length} valda referenser</h3><p>Dra poster hit eller markera dem till vänster.</p>{dimension==='shared_cost'&&<><p>Välj kostnadsprojekt, exempelvis vattentunna eller släp. Fördela mellan alla ekonomiska enheter eller enheterna i vald grupp. Gruppens daterade kopplingar styr mottagarna.</p><label><input type="checkbox" name="equal_share" required={target!=='none'} disabled={target==='none'}/> Fördela kostnaden jämnt</label></>}<label>{dimensions[dimension as keyof typeof dimensions]}{dimension==='vehicle'?<><select aria-label="Välj mottagande regnummer" value={target} onChange={e=>setTarget(e.target.value)} disabled={!registry}><option value="">Välj registrerat fordon</option>{target&&!registryOptions.vehicles.some(o=>o.value===target)&&<option value={target}>{target} · manuellt angivet</option>}{registryOptions.vehicles.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><input aria-label="Regnummer · manuellt" value={target} onChange={e=>setTarget(e.target.value.toUpperCase())} required pattern="[A-Z]{3}[0-9]{2}[A-Z0-9]" placeholder="Kan även skrivas manuellt"/></>:<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Välj mottagare</option>{choices?.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select>}</label><label>Giltig från<input name="valid_from" type="date" required defaultValue={from}/></label><label>Giltig till (valfritt)<input name="valid_to" type="date"/></label><label>Motivering<input name="reason" required minLength={3} maxLength={1000} placeholder="Varför hör posterna hit?"/></label><p>Kopplingen gäller exakt vald referens, källa och typ. En projekt- eller kontoregel kan påverka fler rader än de som nu är ofördelade. Originalbeloppen ändras inte. {dimension==='shared_cost'&&'Hubben delar varje kostnad mellan giltiga mottagare på kostnadens datum. Totalen bevaras exakt och varje andel kan följas till originaltransaktionen. Utan mottagare ligger kostnaden kvar som ofördelad.'}</p><button className="primary" disabled={busy||!selected.length||!target}>{saving?'Sparar…':'Spara verifierad koppling'}</button></fieldset></form></div>
 <details><summary>Senaste matchningar och historik</summary><div className="table-wrap"><table><thead><tr><th>Koppling</th><th>Referens</th><th>Mottagare</th><th>Giltighet</th><th>Motivering</th></tr></thead><tbody>{data?.history.map((h,i)=><tr key={i}><td>{dimensions[h.dimension as keyof typeof dimensions]} · {h.source}</td><td>{h.reference}</td><td>{h.target}</td><td>{h.valid_from} – {h.valid_to??'Tills vidare'}</td><td>{h.reason}</td></tr>)}</tbody></table></div></details><p>Rader med ogiltigt datum eller belopp behöver fortfarande granskas i Dataimport.</p></section>;
}
