'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
export type AiProposal={id:string;reference_key:string;targets:Record<string,string>;reason:string;confidence:number;status:string};
export function useKpiAiProposals(query:string,ready:boolean,visiblePage=0){
 const [proposals,setProposals]=useState<Record<string,AiProposal>>({}),[running,setRunning]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const control=useRef<AbortController|null>(null),started=useRef(''),cursor=useRef(0);
 const run=useCallback(async(startPage?:number)=>{if(control.current)return;const c=new AbortController();control.current=c;setRunning(true);setError('');setMessage('Hubben tar fram förslag. Knapparna aktiveras när förslagen är klara.');try{
 let page=startPage??cursor.current;
 while(!c.signal.aborted){const r=await fetch('/api/kpi/matching/suggestions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'generate',query,page}),signal:c.signal});const j=await r.json();if(!r.ok)throw Error(j.error);if(c.signal.aborted)break;setProposals(s=>({...s,...Object.fromEntries((j.proposals as AiProposal[]).map(p=>[p.reference_key,p]))}));setMessage('Förslag sparade · sida '+(page+1)+' av '+Math.max(1,Math.ceil(j.total_groups/100)));if(j.next_page===null){setMessage('Urvalet är bedömt. Godkänn på raden eller markera flera förslag.');cursor.current=0;break}page=j.next_page;cursor.current=page;
 }
 }catch(e){if(!c.signal.aborted){const msg=e instanceof Error?e.message:'Förslagen kunde inte hämtas';setError(msg);setMessage('Bedömningen stoppades. Sparade förslag går fortfarande att godkänna.')}}finally{if(control.current===c){control.current=null;setRunning(false)}}},[query]);
 const pause=useCallback(()=>{control.current?.abort();control.current=null;setRunning(false);setMessage('Pausat. Sparade förslag finns kvar.')},[]);
 useEffect(()=>{pause();cursor.current=0;setProposals({});setError('');started.current='';return()=>{control.current?.abort();control.current=null}},[query,pause]);
 useEffect(()=>{if(ready&&started.current!==query){started.current=query;void run(visiblePage)}},[ready,query,run,visiblePage]);
 useEffect(()=>{if(!ready)return;const c=new AbortController();fetch('/api/kpi/matching/suggestions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'list',query,page:visiblePage}),signal:c.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);if(!c.signal.aborted)setProposals(s=>({...s,...Object.fromEntries((j.proposals as AiProposal[]).map(p=>[p.reference_key,p]))}))}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[ready,query,visiblePage]);
 async function reassess(p:AiProposal|undefined,page:number){if(!p)return;pause();setRunning(true);setError('');const c=new AbortController();control.current=c;try{const r=await fetch('/api/kpi/matching/suggestions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'generate',query,page,reassess_key:p.reference_key}),signal:c.signal});const j=await r.json();if(!r.ok)throw Error(j.error);if(!c.signal.aborted){setProposals(s=>({...s,...Object.fromEntries((j.proposals as AiProposal[]).map(v=>[v.reference_key,v]))}));setMessage('Raden är bedömd igen med aktuellt underlag.')}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Kunde inte bedöma raden')}finally{if(control.current===c){control.current=null;setRunning(false)}}}
 async function resolve(p:AiProposal,action:'approve'|'reject'){pause();const r=await fetch('/api/kpi/matching/suggestions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,id:p.id}),signal:AbortSignal.timeout(110000)});const j=await r.json();if(!r.ok)throw Error(j.error);setProposals(s=>({...s,[p.reference_key]:{...p,status:action==='approve'?'approved':'rejected'}}));return j;}
 return {proposals,running,message,error,run,pause,resolve,reassess};
}
export function KpiAiRow({proposal,disabled,onResolve,onEdit,onGenerate,onReassess,label,error,running}:{proposal?:AiProposal;disabled:boolean;onResolve:(p:AiProposal,a:'approve'|'reject')=>void;onEdit:()=>void;onGenerate:()=>void;onReassess:()=>void;label:(d:string,v:string)=>string;error:string;running:boolean}){
 const canApprove=proposal?.status==='pending'&&Object.keys(proposal.targets).length>0;
 const why=!proposal?(error?'AI-förslaget kunde inte skapas. Försök igen eller koppla manuellt här.':running?'AI bedömer underlaget. Godkänn aktiveras när ett förslag är klart.':'Ett förslag behöver skapas innan raden kan godkännas.'):proposal.status==='needs_input'?'Komplettera underlaget eller kopplingen innan godkännande.':proposal.status==='rejected'?'Förslaget är avvisat.':'';
 return <aside aria-label="AI-förslag" style={{padding:'12px',marginTop:'10px',background:'#f3f7f6',borderRadius:'8px',maxWidth:'520px'}}><strong>{proposal?.status==='approved'?'Godkänd och sparad':proposal?.status==='rejected'?'Avvisat förslag':proposal?.status==='needs_input'?'Underlag behöver kompletteras':proposal?'AI-förslag':'AI-förslag saknas'}</strong>{proposal&&Object.keys(proposal.targets).length>0&&<ul>{Object.entries(proposal.targets).map(([d,v])=><li key={d}>{label(d,v)}</li>)}</ul>}{proposal&&<><p>{proposal.reason}</p>{Object.keys(proposal.targets).length>0&&<small>AI:s säkerhetsbedömning: {Math.round(Number(proposal.confidence)*100)} %</small>}</>}{why&&<p>{why}</p>}<div style={{display:'flex',gap:'8px',flexWrap:'wrap',marginTop:'10px'}}><button type="button" className="primary" disabled={disabled||!canApprove} onClick={()=>proposal&&onResolve(proposal,'approve')}>{proposal?.status==='approved'?'Godkänd':'Godkänn förslag'}</button><button type="button" disabled={disabled} onClick={onEdit}>Ändra / koppla här</button>{!proposal&&<button type="button" disabled={disabled||running} onClick={onGenerate}>Skapa AI-förslag</button>}{proposal?.status==='needs_input'&&<button type="button" disabled={disabled} onClick={onReassess}>Bedöm igen efter komplettering</button>}{canApprove&&<button type="button" disabled={disabled} onClick={()=>proposal&&onResolve(proposal,'reject')}>Avvisa</button>}</div></aside>;
}
