'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {fiscalMonths,monthLabels,parseMonthPeriod,stockholmToday} from '@/lib/kpi/period';
import {metricStatus,monthlyValue,type MonthlyTransportReport} from '@/lib/kpi/monthly-report';
import styles from './kpi-monthly-report.module.css';
export function KpiMonthlyReport({query}:{query:string}){
 const initial=new URLSearchParams(query),period=parseMonthPeriod(initial.get('fiscal_year')??undefined,initial.get('months')??undefined);
 const today=stockholmToday(),previousMonth=today.month===1?12:today.month-1;
 const defaultMonth=period.months.length===1?period.months[0]:period.fiscalYear===period.currentYear&&previousMonth!==8?previousMonth:8;
 const defaultYear=period.months.length!==1&&period.fiscalYear===period.currentYear&&today.month===9?period.fiscalYear-1:period.fiscalYear;
 const [year,setYear]=useState(defaultYear),[month,setMonth]=useState(defaultMonth),[center,setCenter]=useState(initial.get('cost_center')||'30');
 const [loaded,setLoaded]=useState<{query:string;data:MonthlyTransportReport}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[retry,setRetry]=useState(0);
 const cache=useRef(new Map<string,MonthlyTransportReport>());
 const scope=new URLSearchParams({fiscal_year:String(year),report_month:String(month),cost_center:center});
 for(const k of ['group','unit','vehicle','project']){const value=initial.get(k);if(value)scope.set(k,value);}
 const reportQuery=scope.toString();
 const report=loaded?.query===reportQuery?loaded.data:null;
 useEffect(()=>{
  const controller=new AbortController();let ignore=false;
  async function load(){await Promise.resolve();if(ignore)return;setError('');
  const cached=cache.current.get(reportQuery);if(cached){setLoaded({query:reportQuery,data:cached});setBusy(false);return;}
  setLoaded(null);setBusy(true);
  fetch('/api/kpi/monthly-report?'+reportQuery,{signal:controller.signal,cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(!ignore){if(cache.current.size>=24)cache.current.delete(cache.current.keys().next().value!);cache.current.set(reportQuery,data);setLoaded({query:reportQuery,data});}}).catch(e=>{if(!ignore)setError(e instanceof Error?e.message:'Rapporten kunde inte hämtas.');}).finally(()=>{if(!ignore)setBusy(false);});
  }
  void load();return()=>{ignore=true;controller.abort();};
 },[reportQuery,retry]);
 async function download(format:'pdf'|'xlsx',variant:'ledning'|'utforlig'='utforlig'){
  setExporting(true);setError('');try{const response=await fetch('/api/kpi/monthly-report?'+reportQuery+'&format='+format+(format==='pdf'?'&variant='+variant:''));if(!response.ok){const data=await response.json();throw Error(data.error);}
  const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=format==='pdf'?`humla-manadsrapport-${variant}-${report!.period.from.slice(0,7)}.pdf`:`humla-nyckeltal-transport-${report!.period.from.slice(0,7)}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }catch(e){setError(e instanceof Error?e.message:'Exporten misslyckades.');}finally{setExporting(false);}
 }
 function change(nextYear:number,nextMonth:number,nextCenter:string){setYear(nextYear);setMonth(nextMonth);setCenter(nextCenter);const p=new URLSearchParams(query);p.set('view','monthly');p.set('fiscal_year',String(nextYear));p.set('months',String(nextMonth));p.set('cost_center',nextCenter);p.delete('from');p.delete('to');window.history.replaceState(null,'','/kpi?'+p);void fetch('/api/kpi/selection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:p.toString()})}).catch(()=>{});}
 const centers=report?.cost_centers?.length?report.cost_centers:[{code:'10',name:'Entreprenad'},{code:'20',name:'Sortergården'},{code:'30',name:'Transport'},{code:'40',name:'Verkstad'},{code:'50',name:'Fastigheter'},{code:'60',name:'Skåne'},{code:'90',name:'Övrigt'}];
 const years=Array.from(new Set([year,period.currentYear,...Array.from({length:6},(_,i)=>period.currentYear-i)])).sort((a,b)=>b-a);
 return <section aria-busy={busy}>
 <span className="section-kicker">Månadsleverans enligt Nyckeltal Transport</span><h2>Välj månad och hämta rapporten</h2><p>Välj enkel rapport till ledningsgruppen eller utförlig rapport. Båda PDF-filerna visar KST 20 och 30 var för sig, med avdelningarnas KPI och YTD – utan fordonsuppdelning. Excel-exporten följer valt kostnadsställe.</p>
 <div className={styles.toolbar}><label>Verksamhetsår<select value={year} onChange={e=>change(Number(e.target.value),month,center)}>{years.map(y=><option key={y} value={y}>{y}/{y+1}</option>)}</select></label><label>Månad<select value={month} onChange={e=>change(year,Number(e.target.value),center)}>{fiscalMonths.map((m,i)=><option value={m} key={m}>{monthLabels[i]} {m>=9?year:year+1}</option>)}</select></label><label>Kostnadsställe<select value={center} onChange={e=>change(year,month,e.target.value)}>{!centers.some(c=>c.code===center)&&<option value={center}>{center} (samlat urval)</option>}{centers.map(c=><option key={c.code} value={c.code}>{c.code} – {c.name}</option>)}</select></label><button className="secondary" onClick={()=>{cache.current.delete(reportQuery);setRetry(v=>v+1);}}>Hämta underlag igen</button></div>
 <div className={styles.actions}><button className="primary" disabled={!report||busy||exporting} onClick={()=>download('pdf','ledning')}>{exporting?'Skapar rapport…':'Ledningsgrupp – enkel PDF (KST 20 + 30)'}</button><button className="secondary" disabled={!report||busy||exporting} onClick={()=>download('pdf','utforlig')}>Utförlig PDF (KST 20 + 30)</button><button className="secondary" disabled={!report||busy||exporting} onClick={()=>download('xlsx')}>Hämta Excel med underlag</button></div>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Hämtar månadsrapport från Hubben…</p>}
 {report&&<><p>{report.tenant} · {report.period.from} – {report.period.to} · YTD {report.period.ytd_from} – {report.period.to}<br/><small>Underlag synkat {new Date(report.synced_at).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'})}. Urval: {Object.entries(report.scope).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small></p>
 <div className={styles.notice}>Alla registrerade intäkter räknas som fakturerade enligt din rapportregel. Originalstatusen ändras inte. Omsättningen följer artikeldatum och samma intäktsurval som KPI-vyn. Bränsle hämtas från Piusi och NEXT utan dubbelt inköp till egen tank. Resultatet använder denna bränslekostnad och TransPA-personalschablon. Tid och beläggning kommer från TransPA; debiteringsgraden är en indikator för intäktskopplad tid. Bränsleandel omfattar även annat drivmedel än diesel.</div>
 <div className={styles.grid}>{report.month.metrics.map((metric,i)=><article className={styles.card} key={metric.key}><h3>{metric.label}</h3><div className={styles.values}><div>Månad<strong>{monthlyValue(metric.value,metric.unit)}</strong><small>{metricStatus[metric.status]}</small></div><div>YTD<strong>{monthlyValue(report.ytd.metrics[i].value,metric.unit)}</strong><small>{metricStatus[report.ytd.metrics[i].status]}</small></div></div><p>{metric.basis}</p></article>)}</div>
 <section className="panel"><h3>Kompletterande underlag – månad</h3><p>Registrerade intäkter: {monthlyValue(report.month.recorded_revenue,'kr')} · Utanför rapportens faktureringsregel: {monthlyValue(report.month.uninvoiced_revenue,'kr')}<br/>Bränsle totalt: {monthlyValue(report.month.fuel,'kr')} · Bränsleandel: {monthlyValue(report.month.fuel_share,'%')}<br/>Aktiva egna fordonsenheter: {report.month.active_vehicle_count} · Rapporterad TransPA-tid / kapacitet: {monthlyValue(report.indicators.reported_vehicle_utilization,'%')}</p><small>{report.indicators.definition}</small></section>
 <section className="panel"><h3>Bränsle – Piusi + NEXT</h3><p>Piusi tankningar: {monthlyValue(report.month.fuel_sources?.piusi_cost,'kr')} · {monthlyValue(report.month.fuel_sources?.piusi_liters,'liter')}<br/>Övrigt bränsle i NEXT: {monthlyValue(report.month.fuel_sources?.next_cost,'kr')}<br/>NEXT egen tank (5360), avstämning utanför summan: {monthlyValue(report.month.fuel_sources?.next_tank_purchase_excluded,'kr')}</p><p>{report.month.fuel_sources?.basis}</p><p>Piusi: {report.month.fuel_sources?.piusi_rows??0} tankningar i urvalet · {report.month.fuel_sources?.provisional_rows??0} preliminära priser · {report.month.fuel_sources?.review_rows??0} prisrader för granskning · {report.month.fuel_sources?.unclassified_rows??0} okopplade tankningar i perioden över hela arbetsytan.</p><p>Senaste Piusi-synkning: {report.month.fuel_sources?.source_state.last_connector_success?new Date(report.month.fuel_sources.source_state.last_connector_success).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'}):'Saknas'} · Anslutningsstatus: {report.month.fuel_sources?.source_state.connector_status??'Okänd'}</p><details><summary>Visa bränsleunderlag – månad</summary><div className={styles.table}><table><thead><tr><th>Datum</th><th>Källa</th><th>Fordon</th><th>Produkt / konto</th><th>Liter</th><th>Kostnad</th><th>Prisunderlag</th></tr></thead><tbody>{report.month.fuel_sources?.transactions.map(t=><tr key={t.source+':'+t.id}><td>{t.dt}</td><td>{t.source}</td><td>{t.vehicle??'Ej kopplat'}</td><td>{t.product}</td><td>{monthlyValue(t.liters,'l')}</td><td>{monthlyValue(t.amount,'kr')}</td><td><details><summary>{({provisional:'Preliminärt API-pris',approved:'Godkänt',excluded:'Undantaget',manual_review:'Behöver granskas',imported:'NEXT-underlag'} as Record<string,string>)[t.price_status]??t.price_status}</summary>Källreferens: {t.id}</details></td></tr>)}</tbody></table></div></details></section>
 <section className="panel"><h3>Timmar – TransPA</h3><div className={styles.table}><table><thead><tr><th>Underlag</th><th>Månad</th><th>YTD</th></tr></thead><tbody>{([['Rapporterad fordonstid','reported_vehicle_hours'],['Tillgänglig fordonskapacitet','available_vehicle_hours'],['Arbetad chaufförstid','worked_driver_hours'],['Intäktskopplad chaufförstid','revenue_linked_driver_hours'],['Oklassificerad chaufförstid','unclassified_driver_hours']] as const).map(([label,key])=><tr key={key}><td>{label}</td><td>{monthlyValue(report.month.time?.[key],'h')}</td><td>{monthlyValue(report.ytd.time?.[key],'h')}</td></tr>)}</tbody></table></div><p>Intäktskopplad tid betyder rapporterad TransPA-tid på dagar med kopplad intäkt. Det är inte verifierad fakturerad tid.</p></section>
 <section className="panel"><h3>Kostnadsenheter – samma som i KPI</h3><p>Fordon, sammansatta enheter och lager/projekt läses från samma förberedda Hub-rapport som KPI. Ändrade kopplingar och namn följer med vid nästa rapportsynkning. Bränslet i denna rapport följer modellen Piusi + NEXT ovan.</p><div className={styles.table}><table><thead><tr><th>Kostnadsenhet</th><th>Omsättning</th><th>Kostnad</th><th>Bränsle</th><th>Arbetad tid</th><th>Rapporterad fordonstid</th><th>Underlag</th></tr></thead><tbody>{report.month.economic_units?.map(u=><tr key={u.key}><td>{u.label}</td><td>{monthlyValue(u.revenue,'kr')}</td><td>{monthlyValue(u.cost,'kr')}</td><td>{monthlyValue(u.fuel,'kr')}</td><td>{monthlyValue(u.worked_hours,'h')}</td><td>{monthlyValue(u.occupied_hours,'h')}</td><td><Link prefetch={false} href={'/kpi/analys?'+new URLSearchParams({fiscal_year:String(year),months:String(month),cost_center:center,...Object.fromEntries(Object.entries(report.scope).filter(([k])=>k!=='cost_center'&&k!=='unit')),unit:u.key,level:'transaction',grain:'month'})}>Visa KPI-underlag</Link></td></tr>)}</tbody></table></div></section>
 </>}
 </section>;
}
