'use client';
import {useEffect,useState} from 'react';
type Data={settings:{start_time:string;end_time:string;break_minutes:number};salary_resources:number;pending_events:number;last_received:string|null;codes:Array<{pay_type_code:string;rows:number;category:string|null;unit:string|null}>};
export function KpiAttendanceSettings(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function reload(){const r=await fetch('/api/kpi/attendance',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}
 useEffect(()=>{reload().catch(e=>setError(e.message))},[]);
 async function save(code:string,category:string,unit:string){if(!category||!unit)return;setBusy(true);setError('');try{const r=await fetch('/api/kpi/attendance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pay_type_code:code,category,unit})});const j=await r.json();if(!r.ok)throw Error(j.error);await reload()}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 return <section className="panel"><h3>Närvaro · TransPA via Humla Hub</h3>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Hämtar anslutningen…</p>}{data&&<><p>Ordinarie schema: måndag–fredag {data.settings?.start_time.slice(0,5)??'07:00'}–{data.settings?.end_time.slice(0,5)??'16:00'}, rast {data.settings?.break_minutes??60} minuter. 8 arbetstimmar per dag.</p><p>{data.salary_resources} mottagna löneexporter · {data.pending_events} väntar på hämtning{data.last_received?' · Senast '+new Date(data.last_received).toLocaleString('sv-SE'):''}.</p>{!data.codes.length?<p>Hubben väntar på TransPA:s löneexport med tidsrader och lönearter. Ingen frånvaroprocent kan beräknas ännu. När rader kommer in kan sjukfrånvaro, VAB, semester och övrig frånvaro mappas här.</p>:<><p>Välj vad företagets lönearter betyder och om mängden anges i timmar eller dagar. Sparas direkt på raden. Närvaro kräver även ett komplett underlag för vald period.</p><table><thead><tr><th>Löneart</th><th>Tidsrader</th><th>Typ</th><th>Enhet</th></tr></thead><tbody>{data.codes.map(c=><tr key={c.pay_type_code}><td>{c.pay_type_code}</td><td>{c.rows}</td><td><select aria-label={'Typ för '+c.pay_type_code} disabled={busy} value={c.category??''} onChange={e=>save(c.pay_type_code,e.target.value,c.unit??'hours')}><option value="">Välj typ</option>{Object.entries({worked:'Arbetad tid',sick:'Sjukfrånvaro',vab:'VAB',vacation:'Semester',other:'Övrig frånvaro'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><select aria-label={'Enhet för '+c.pay_type_code} disabled={busy} value={c.unit??'hours'} onChange={e=>save(c.pay_type_code,c.category??'',e.target.value)}><option value="hours">Timmar</option><option value="days">Dagar</option></select></td></tr>)}</tbody></table></>}</>}</section>;
}
