'use client';
import {useState} from 'react';
import {trialAssetId,type SearchTrialResult} from '@/lib/hub/market-search-trial';
export function MarketSearchTrial({assetId,canManage}:{assetId:string;canManage:boolean}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<SearchTrialResult|null>(null),[error,setError]=useState('');
 if(assetId!==trialAssetId||!canManage)return null;
 async function run(){setBusy(true);setError('');try{const response=await fetch('/api/hub/market-search-trial',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({asset_id:assetId})});const data=await response.json();if(!response.ok)throw Error(data.error);setResult(data);}catch(e){setError(e instanceof Error?e.message:'Testet kunde inte köras.');}finally{setBusy(false);}}
 return <section className="panel"><h2>Avgränsat webbsökningstest</h2><p>En sökning genom Humlas befintliga AI-tjänst. Endast fabrikat och modell skickas; inga regnummer, kostnader eller personuppgifter. Inga marknadsvärden ändras. Testet kan inte starta en ny betald sökning när det väl har reserverats.</p><button disabled={busy} onClick={()=>void run()}>{busy?'Söker underlag…':result?'Visa sparat testresultat':'Kör avgränsat sökningstest'}</button>{error&&<p role="alert">{error}</p>}{result&&<div aria-live="polite"><p>Sökning: <strong>{result.query}</strong> · {result.candidates.length} kandidater · {result.searched_at}</p><p>{result.cost_usd==null?'Debiterad kostnad kunde inte verifieras.':`Gateway rapporterar ${result.cost_usd.toFixed(6)} USD för körningen.`}</p>{result.error&&<p role="alert">{result.error}</p>}<p>Sökträffar är inte godkända jämförelseobjekt. Pris, moms, valuta, miltal och genomförd försäljning måste kontrolleras.</p>{result.candidates.map(c=><article key={c.url}><h3><a href={c.url} target="_blank" rel="noopener noreferrer">{c.source} · {c.title}</a></h3><p>{c.snippet}</p>{c.date&&<small>Datum i sökindex: {c.date} (inte bekräftat försäljningsdatum)</small>}</article>)}</div>}</section>;
}
