"use client"; import {useEffect,useState} from "react";
type P={project_reference:string;project_name:string|null;cost_center:string|null;row_count:number;total_cost:number;mapping_id:string|null;vehicle_registration:string|null;allocation_id:string|null;allocation_type:string|null;allocation_method:string|null;selected_object_ids:string[]|null};
const labels:any={vehicle:"Fordon",selected_vehicles:"Valda fordon",all_vehicles:"Alla fordon",business_group:"Verksamhetsgrupp",overhead:"Övergripande",exclude_vehicle_result:"Utanför fordonsresultat"};
export function NextCostProjectQueue(){
 const [u,setU]=useState<P[]>([]),[m,setM]=useState<P[]>([]),[edit,setEdit]=useState<string|null>(null),[type,setType]=useState("all_vehicles"),[method,setMethod]=useState("equal"),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/kpi/control-panel/next-cost-projects",{cache:"no-store"}),j=await r.json();if(!r.ok)throw Error(j.error);setU(j.unmatched??[]);setM(j.matched??[])}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
 async function save(p:P){setMsg("Sparar…");const r=await fetch("/api/kpi/control-panel/next-cost-projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_reference:p.project_reference,allocation_type:type,allocation_method:method,valid_from:new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Stockholm"})})}),j=await r.json();if(!r.ok){setMsg(j.error);return}setEdit(null);setMsg("Sparat");await load()}
 return <section className="panel"><h3>NEXT-projekt med kostnader</h3><p>Projekt med bokförda kostnader som ännu saknar kostnadsenhet eller fördelningsregel. När en regel sparas flyttas projektet automatiskt till Matchade & fördelade.</p>{msg&&<p role="status">{msg}</p>}
 <h4>Behöver matchas ({u.length})</h4><div className="table-wrap"><table><thead><tr><th>Projekt</th><th>Namn</th><th>KST</th><th>Kostnad</th><th>Rader</th><th>Åtgärd</th></tr></thead><tbody>{u.map(p=><tr key={p.project_reference}><td><b>{p.project_reference}</b></td><td>{p.project_name??"–"}</td><td>{p.cost_center??"–"}</td><td>{Number(p.total_cost).toLocaleString("sv-SE")} kr</td><td>{p.row_count}</td><td>{edit===p.project_reference?<div><select value={type} onChange={e=>setType(e.target.value)}><option value="all_vehicles">Alla fordon</option><option value="selected_vehicles">Valda fordon</option><option value="business_group">Verksamhetsgrupp</option><option value="overhead">Övergripande</option><option value="exclude_vehicle_result">Utanför fordonsresultat</option></select><select value={method} onChange={e=>setMethod(e.target.value)}><option value="equal">Lika</option><option value="revenue_share">Omsättning</option><option value="hours_share">Timmar</option><option value="km_share">Kilometer</option><option value="fixed_share">Procent</option><option value="manual">Manuell</option></select><button onClick={()=>save(p)}>Spara</button></div>:<button className="secondary" onClick={()=>setEdit(p.project_reference)}>Matcha / fördela</button>}</td></tr>)}</tbody></table></div>
 <h4>Matchade & fördelade ({m.length})</h4><div className="table-wrap"><table><thead><tr><th>Projekt</th><th>Namn</th><th>Kostnad</th><th>Typ</th><th>Fördelning</th></tr></thead><tbody>{m.map(p=><tr key={p.project_reference}><td><b>{p.project_reference}</b></td><td>{p.project_name??"–"}</td><td>{Number(p.total_cost).toLocaleString("sv-SE")} kr</td><td>{p.mapping_id?("Fordon "+(p.vehicle_registration??"")):labels[p.allocation_type??""]??p.allocation_type}</td><td>{p.mapping_id?"Direkt":p.allocation_method??"–"}</td></tr>)}</tbody></table></div></section>
}