'use client';
import {useState} from 'react';
import {parsePaymentCsv} from '@/lib/hub/payment-import';
import type {Payment,PaymentForecast} from '@/lib/hub/payment-forecast';
import type {AutomaticForecast} from '@/lib/hub/payment-outcome-forecast';
const money=(n:number|null)=>n===null?'Underlag saknas':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(n);
const payrollMethod={registered:'Registrerade timmar + löneschablon',historical_trend:'Föregående år × årets lönetrend',latest_month:'Reservprognos: senaste avslutade månad',missing:'Tillräckligt löneunderlag saknas'};
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function PaymentForecastWorkspace(){
 const [periodOffset,setPeriodOffset]=useState(0);
 const [mode,setMode]=useState<'automatic'|'manual'>('automatic');
 const [asOf,setAsOf]=useState(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));
 const [historyFrom,setHistoryFrom]=useState(''),[historyTo,setHistoryTo]=useState('');
 const [ledger,setLedger]=useState<Payment[]|null>(null),[history,setHistory]=useState<Payment[]>([]);
 const [files,setFiles]=useState({ledger:'',history:''});
 const [basis,setBasis]=useState<'payment'|'booked'>('payment'),[inDays,setInDays]=useState(30),[outDays,setOutDays]=useState(30);
 const [result,setResult]=useState<(PaymentForecast&Partial<Pick<AutomaticForecast,'automatic'>>)|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const invalidate=()=>{setResult(null);setError('');setPeriodOffset(0)};
 async function upload(file:File|undefined,kind:'ledger'|'history'){
  invalidate();if(!file)return;setBusy(true);if(kind==='ledger'){setLedger(null)}else setHistory([]);setFiles(p=>({...p,[kind]:''}));
  try{if(file.size>4_000_000)throw Error('Max 4 MB per fil');const rows=parsePaymentCsv(await file.text());if(kind==='ledger')setLedger(rows);else setHistory(rows);setFiles(p=>({...p,[kind]:file.name}))}catch(e){setError(e instanceof Error?e.message:'Import misslyckades')}finally{setBusy(false)}
 }
 async function calculate(offset=periodOffset){setBusy(true);setError('');setResult(null);try{
  const res=await fetch('/api/kpi/payment-forecast',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='automatic'?{mode,asOf,periodOffset:offset,supplierDays:outDays}:{asOf,periodOffset:offset,ledger,history,historyFrom,historyTo,basis,inDays,outDays})});
  const body=await res.json();if(!res.ok)throw Error(body.error||'Beräkningen misslyckades');setResult(body);setPeriodOffset(offset);
 }catch(e){setError(e instanceof Error?e.message:'Beräkningen misslyckades')}finally{setBusy(false)}}
 function exportCsv(){if(!result)return;
  const rows:(string|number)[][]=[['Humla – avdelningens betalningsprognos'],['Rapportdatum',result.asOf],['Underlag',result.automatic?'Workify / NeXT, exklusive moms':files.ledger],['Utfall',result.automatic?'Humla Hub':files.history],['Historik från',result.historyCoverage.from,'till',result.historyCoverage.to],['Metod',result.method],['Vecka','Från','Till','KST','Avdelning','Kundinbetalningar — prognos','Kostnader — prognos','Netto','Löner — prognos (brutto)','Interna intäkter — prognos','Interna kostnader — prognos',result.automatic?'Registrerade intäkter – beräknad betalningsvecka':'Kända inbetalningar',result.automatic?'Registrerade kostnader – beräknad betalningsvecka':'Kända utbetalningar']];
  if(result.automatic)rows.splice(6,0,['Underlag synkat',result.automatic.syncedAt],...result.automatic.warnings.map(w=>['Observera',w]));
  if(result.automatic?.payroll)rows.splice(rows.length-1,0,...result.automatic.payroll.details.map(d=>['Löneunderlag','KST',d.center,'Utbetalning',d.payDate,'Arbetsmånad',d.workMonth,'Bruttolön',d.amount??'Underlag saknas','Metod',payrollMethod[d.method],'Grundmånad',d.sourceMonth??'','Bas',d.baseline??'','Trendfaktor',d.factor??'']));
  for(const w of result.weeks){for(const p of [...w.parts,{center:'20+30',name:'Totalt',internal:w.internal,...w.total}])rows.push([`${w.year}-V${w.number}`,w.from,w.to,p.center,p.name,p.incoming.total??'Underlag saknas',p.outgoing.total??'Underlag saknas',p.net??'Underlag saknas',result.automatic?(p.payroll??'Underlag saknas'):'Ingår inte manuellt',p.internal.incoming??'Underlag saknas',p.internal.outgoing??'Underlag saknas',p.incoming.known,p.outgoing.known])}
  rows.push([],['Andra / saknade kostnadsställen – ingår inte i totalen'],['Rad-ID','KST','Typ','Datum','Restbelopp']);result.unknown.forEach(r=>rows.push([r.id,r.center,r.kind,r.date,r.amount]));
  rows.push([],['Förfallna poster – ingår inte i framtida veckor'],['Rad-ID','KST','Typ','Datum','Restbelopp']);result.overdue.forEach(r=>rows.push([r.id,r.center,r.kind,r.date,r.amount]));
  rows.push([],['Interna körningar / överföringar – ingår inte i betalningsprognos eller trend'],['Underlag','Rad-ID','KST','Typ','Datum','Belopp']);
  for(const [source,items] of Object.entries(result.internal))items.forEach(r=>rows.push([source==='ledger'?'Reskontra':'Historiskt utfall',r.id,r.center,r.kind,r.date,r.amount]));
  const csv=rows.map(row=>row.map(v=>'"'+String(typeof v==='number'?String(v).replace('.',','):String(v).replace(/^[=+@-]/,"'$&")).replaceAll('"','""')+'"').join(';')).join('\r\n');
  download(`Betalningsprognos_${result.asOf}.csv`,'\uFEFF'+csv);
 }
 return <div className="content" style={{maxWidth:1400,margin:'auto'}}>
  <p>Hela avdelningen: <strong>30 Transport · 20 Sortergården</strong>. Vecka 1 visar vecka 5–8. Fordons- och projektfilter används inte.</p>
  <p><label>Underlag <select value={mode} disabled={busy} onChange={e=>{invalidate();setMode(e.target.value as 'automatic'|'manual')}}><option value="automatic">Workify + NeXT — hämtas från Hubben</option><option value="manual">Egen reskontra och historik — filimport</option></select></label></p>
  {mode==='automatic'&&<section className="panel"><h2>Prognos från befintliga underlag</h2><p>Föregående års utfall justeras med årets trend för avslutade månader i verksamhetsåret. Workify ger intäkterna, NeXT ger kostnaderna. Inga filer behöver laddas upp.</p><p><strong>Kundvillkor:</strong> 30 dagar som standard; Linnestofta Maskin och Thomas Håkansson Entreprenad 45 dagar från fakturadatum. Stena har 45 dagar från leveransmånadens sista dag och beloppen samlas per avräkningsmånad. Saknas fakturadatum används leveransdatum som ett tydligt antagande.</p><p>Beloppen visas <strong>exklusive moms</strong> enligt källunderlagen. Detta är en prognos, inte verifierad kund- eller leverantörsreskontra.</p><p><label>Rapportdatum <input type="date" disabled={busy} value={asOf} onChange={e=>{invalidate();setAsOf(e.target.value)}}/></label> <label>Antagen betalningstid för NeXT-kostnader (dagar) <input type="number" min={0} max={180} disabled={busy} value={outDays} onChange={e=>{invalidate();setOutDays(Number(e.target.value))}}/></label></p><button className="primary" disabled={busy} onClick={()=>void calculate()}>{busy?'Hämtar och beräknar…':'Hämta och beräkna från Hubben'}</button></section>}
  {mode==='manual'&&<section className="panel"><h2>1. Underlag</h2><p>Importera en komplett öppen kund- och leverantörsreskontra per rapportdatum. Ange återstående betalning <strong>inklusive moms</strong>. Markera interna överföringar.</p>
   <label>Rapportdatum <input type="date" disabled={busy} value={asOf} onChange={e=>{invalidate();setAsOf(e.target.value)}}/></label>
   <p><label>Öppen reskontra (CSV) <input type="file" disabled={busy} accept=".csv" onChange={e=>void upload(e.target.files?.[0],'ledger')}/></label><br/>{files.ledger&&`${files.ledger} — ${ledger?.length} rader`}</p>
   <p><label>Föregående års och årets utfall (CSV) <input type="file" disabled={busy} accept=".csv" onChange={e=>void upload(e.target.files?.[0],'history')}/></label><br/>{files.history&&`${files.history} — ${history.length} rader`}</p>
   <label>Historikens datum avser <select disabled={busy} value={basis} onChange={e=>{invalidate();setBasis(e.target.value as 'payment'|'booked')}}><option value="payment">Faktisk betalningsdag</option><option value="booked">Bokfört utfall (omräknat inklusive moms)</option></select></label>
   {basis==='booked'&&<p><label>Antagen tid till kundbetalning (dagar) <input type="number" min={0} max={180} value={inDays} disabled={busy} onChange={e=>{invalidate();setInDays(Number(e.target.value))}}/></label> <label>Antagen tid till leverantörsbetalning (dagar) <input type="number" min={0} max={180} value={outDays} disabled={busy} onChange={e=>{invalidate();setOutDays(Number(e.target.value))}}/></label></p>}
   <p><label>Komplett utfallsperiod från <input type="date" disabled={busy} value={historyFrom} onChange={e=>{invalidate();setHistoryFrom(e.target.value)}}/></label> <label> till <input type="date" disabled={busy} value={historyTo} onChange={e=>{invalidate();setHistoryTo(e.target.value)}}/></label></p>
   <details><summary>Format och prognosmetod</summary><p>Semikolonseparerade kolumner: <code>id;kst;typ;datum;belopp;intern</code>. Typ: <code>in/out</code>. Intern: <code>ja/nej</code>. Datum: ÅÅÅÅ-MM-DD. Unikt rad-ID även för delad faktura. Kreditposter med minus.</p><p>Föregående års motsvarande vecka × årets trend för 13 avslutade veckor jämfört med samma period förra året. Veckor matchas 52 veckor bakåt. Reskontra minskar den ännu inte fakturerade prognosen. Komplett historik måste inkludera båda åren och även dagar utan utfall. Saknad trend ger ”Underlag saknas”. Bokfört utfall förskjuts med vald betalningstid; ingen automatisk momsberäkning.</p><button type="button" onClick={()=>download('Betalningsunderlag_mall.csv','\uFEFFid;kst;typ;datum;belopp;intern\r\n')}>Hämta tom CSV-mall</button></details>
   <p>Första versionen sparar inte underlag automatiskt. Exportera rapporten innan du lämnar sidan.</p>
   <button className="primary" disabled={busy||ledger===null} onClick={()=>void calculate()}>{busy?'Beräknar i Hubben…':'2. Beräkna prognos'}</button>
  </section>}
  {error&&<p role="alert">{error}</p>}
  {result?.automatic?.payroll&&<section className="panel"><h2>Löner från TransPA</h2><p>Föregående månads timmar → den 25:e följande månad. <strong>Uppskattad bruttolön, inte nettoutbetalning.</strong> Löneprognosen ingår redan i Kostnader — prognos och Netto; lägg inte till den igen. PO-pålägg ingår inte.</p><details><summary>Visa arbetsmånad och beräkning för löneprognosen</summary><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>KST</th><th>Arbetsmånad</th><th>Utbetalningsdatum</th><th>Bruttolön</th><th>Beräkningsgrund</th><th>Grundmånad</th><th>Trend</th></tr></thead><tbody>{result.automatic.payroll.details.map(d=><tr key={d.center+d.payDate}><td>{d.center}</td><td>{d.workMonth.slice(0,7)}</td><td>{d.payDate}</td><td>{money(d.amount)}</td><td>{payrollMethod[d.method]}</td><td>{d.sourceMonth?.slice(0,7)??'—'}</td><td>{d.factor===null?'—':`${((d.factor-1)*100).toFixed(1)} %`}</td></tr>)}</tbody></table></div><p>Schablon: månadslön {money(result.automatic.payroll.settings?.monthly_salary??null)}, normalvecka {result.automatic.payroll.settings?.weekly_hours??'—'} h, övertidsfaktor {result.automatic.payroll.settings?.overtime_multiplier??'—'}. En tillräckligt rapporterad månad är en underlagskontroll, inte en verifierad löneexport. Historiskt lönebelopp utan valt/bekräftat KST: {money(result.automatic.payroll.unassignedGross)} — ingår inte.</p></details></section>}
  {result&&<><nav aria-label="Prognosperiod" style={{display:'flex',alignItems:'center',gap:16,flexWrap:'wrap',margin:'20px 0'}}><button disabled={busy||periodOffset<=-104} onClick={()=>void calculate(periodOffset-4)}>← Föregående period</button><strong>V{result.weeks[0].number} / {result.weeks[0].year} – V{result.weeks[3].number} / {result.weeks[3].year}</strong><button disabled={busy||periodOffset>=104} onClick={()=>void calculate(periodOffset+4)}>Nästa period →</button></nav><section className="panel"><h2>Granska och leverera</h2><p>Rapportdatum {result.asOf}. {result.excludedInternal} interna rader uteslutna. {result.unknown.length} poster har annat/saknat kostnadsställe. {!result.automatic&&`${result.overdue.length} poster är förfallna.`} Undantagna poster visas separat i exporten.</p>{result.automatic&&<><p>Underlag synkat {result.automatic.syncedAt}. Trendperiod: {result.automatic.trendFrom} – {result.automatic.trendTo}.</p><ul>{result.automatic.warnings.map(w=><li key={w}>{w}</li>)}</ul></>}<button className="primary" onClick={exportCsv}>Exportera till ekonomi (Excel-kompatibel CSV)</button><p>Inte en fullständig likviditetsprognos: lön, skatt och lån ingår bara om de finns i underlagen. Ingen banksaldoprognos.</p></section>
   {['total','30','20'].map(center=><section className="panel" key={center}><h2>{center==='total'?'Sammanlagt — 30 + 20':result.weeks[0].parts.find(p=>p.center===center)?.name+' — KST '+center}</h2><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th scope="col">Betalningar</th>{result.weeks.map(w=><th scope="col" key={w.from}>V{w.number} / {w.year}<br/><small>{w.from} – {w.to}</small></th>)}</tr></thead><tbody>{[['incoming','total','Kundinbetalningar — prognos'],['outgoing','total','Kostnader — prognos'],['net','','Netto'],['internal','incoming','Interna intäkter — prognos'],['internal','outgoing','Interna kostnader — prognos'],['payroll','','Löner — prognos (brutto)'],['incoming','known',result.automatic?'Registrerade intäkter — beräknad betalningsvecka':'Kundinbetalningar — kända'],['outgoing','known',result.automatic?'Registrerade kostnader — beräknad betalningsvecka':'Leverantörsutbetalningar — kända']].filter(([kind])=>kind!=='payroll'||Boolean(result.automatic?.payroll)).map(([kind,field,label],index)=><tr key={label} style={{fontWeight:index<3?700:400}}><th scope="row" style={{fontWeight:index<3?700:400}}>{label}</th>{result.weeks.map(w=>{const p=center==='total'?w.total:w.parts.find(p=>p.center===center)!;const v=kind==='net'?p.net:kind==='payroll'?p.payroll:kind==='internal'?(center==='total'?w.internal:w.parts.find(p=>p.center===center)!.internal)[field as 'incoming'|'outgoing']:p[kind as 'incoming'|'outgoing'][field as 'known'|'total'];return <td key={w.from} style={{fontWeight:index<3?700:400}}>{money(v)}</td>})}</tr>)}</tbody></table></div></section>)}
   <section className="panel"><h2>Interna körningar — särredovisning</h2><p>Beloppen nedan avser hela respektive importunderlaget, inte bara de fyra prognosveckorna. De ingår inte i prognosen, föregående års bas eller årets trend. Externa kostnader för att utföra interna körningar ska fortfarande finnas med.</p><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th scope="col">Underlag</th><th scope="col">KST</th><th scope="col">Intern intäkt</th><th scope="col">Intern kostnad</th></tr></thead><tbody>{Object.entries(result.internal).flatMap(([source,items])=>['30','20'].map(center=><tr key={source+center}><th scope="row">{source==='ledger'?'Reskontra':'Historiskt utfall'}</th><td>{center}</td><td>{money(items.filter(r=>r.center===center&&r.kind==='in').reduce((sum,r)=>sum+r.amount,0))}</td><td>{money(items.filter(r=>r.center===center&&r.kind==='out').reduce((sum,r)=>sum+r.amount,0))}</td></tr>))}</tbody></table></div><p>Samtliga interna rader, även utan rätt kostnadsställe, finns i exporten.</p></section>
  </>}
 </div>;
}
