'use client';
import {useState} from 'react';
type Refs={registrations:string[];projects:string[];employees:string[]};
type Unit={id:string;name:string;revision:number;registrations:string[];projects:string[];employees:string[];valid_from:string;initial_version?:Partial<Refs>&{valid_from?:string;main_vehicle?:string}|null};
type Preview={from:string;to:string;unit:string;can_save:boolean;signature:string;impact:{rows:number;revenue:number;cost:number;basis:string};conflicts:Array<{id:string;name:string;from:string;to:string|null}>};
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:2});
export function UnitHistoryCompletion({unit,onClose}:{unit:Unit;onClose:()=>void}){
 const first=unit.initial_version??unit;const firstDate=first.valid_from??unit.valid_from;const main=unit.initial_version?.main_vehicle??unit.registrations[0]??'';
 const available:Refs={registrations:first.registrations??unit.registrations,projects:first.projects??unit.projects,employees:first.employees??unit.employees};
 const year=Number(firstDate.slice(0,4))-(Number(firstDate.slice(5,7))<=9?1:0);
 const [from,setFrom]=useState(year+'-09-01'),[refs,setRefs]=useState<Refs>(available),[reason,setReason]=useState('Kompletterar tidigare period som saknar ekonomisk enhet'),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState(false);
 function toggle(key:keyof Refs,value:string,checked:boolean){setPreview(null);setRefs(s=>({...s,[key]:checked?[...s[key],value]:s[key].filter(x=>x!==value)}));}
 async function submit(save:boolean){if(busy||save&&!preview?.can_save)return;setBusy(true);setMessage('');try{const r=await fetch('/api/kpi/units/history',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:unit.id,revision:unit.revision,from,reason,references:refs,preview:!save,signature:save?preview?.signature:null}),signal:AbortSignal.timeout(30000)});const j=await r.json();if(!r.ok)throw Error(j.error);if(save){setSaved(true);setMessage('Historiken är kompletterad. Rapporten har köats för omräkning. Befintliga perioder är bevarade.');window.dispatchEvent(new Event('kpi-units-updated'));}else setPreview(j);}catch(e){setPreview(null);setMessage(e instanceof Error?e.message:'Kunde inte komplettera historiken')}finally{setBusy(false)}}
 const maxDate=new Date(firstDate+'T00:00:00Z');maxDate.setUTCDate(maxDate.getUTCDate()-1);
 return <section className="panel"><h3>Komplettera äldre historik · {unit.name}</h3><p>Skapa en separat period före {firstDate}. Välj de delar som faktiskt ingick då. Befintliga perioder och deras lås behålls.</p>{!saved&&<form onSubmit={e=>{e.preventDefault();submit(false)}}><fieldset disabled={busy}><label>Historiken gäller från<input type="date" required min="2000-01-01" max={maxDate.toISOString().slice(0,10)} value={from} onChange={e=>{setFrom(e.target.value);setPreview(null)}}/></label><p>Gäller till {maxDate.toISOString().slice(0,10)}.</p>{Object.entries({registrations:'Fordon och släp',projects:'Projekt',employees:'Personreferenser'}).map(([key,label])=><fieldset key={key}><legend>{label}</legend>{available[key as keyof Refs].map(v=><label key={v}><input type="checkbox" checked={refs[key as keyof Refs].includes(v)} disabled={key==='registrations'&&v===main} onChange={e=>toggle(key as keyof Refs,v,e.target.checked)}/>{v}{key==='registrations'&&v===main?' · huvudfordon':''}</label>)}{!available[key as keyof Refs].length&&<p>Inga referenser</p>}</fieldset>)}<label>Motivering<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>{setReason(e.target.value);setPreview(null)}}/></label><button className="secondary" type="submit">{busy?'Kontrollerar…':'Förhandsgranska historiken'}</button></fieldset></form>}{preview&&!saved&&<section className="panel" aria-live="polite"><h4>Förhandsgranskning · {preview.from} – {preview.to}</h4><p>{preview.impact.rows} ofördelade rader i det senaste rapportunderlaget: intäkt {money.format(preview.impact.revenue)}, kostnad {money.format(preview.impact.cost)}.</p><p>{preview.impact.basis}. Personreferenser kan påverka ytterligare rader vid omräkning.</p>{preview.conflicts.length>0&&<><p role="alert">Överlappande kopplingar: välj vilka delar som faktiskt ingick i den äldre perioden innan du sparar.</p><ul>{preview.conflicts.map(c=><li key={c.id+c.from}>{c.name}: {c.from} – {c.to??'tills vidare'}</li>)}</ul></>}<button type="button" className="primary" disabled={busy||!preview.can_save} onClick={()=>submit(true)}>Spara historisk komplettering</button></section>}{message&&<p role="status">{message}</p>}<button type="button" className="secondary" disabled={busy} onClick={onClose}>{saved?'Stäng':'Avbryt'}</button></section>;
}
