'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
type Rule = {id:string;name:string;vehicle_label:string;valid_from:string;valid_to:string|null};
type Data = {rules:Rule[];vehicles:{id:string;label:string}[];names:{name:string;rows:number;amount:number}[]};
export function WorkifyNameRules({canManage}:{canManage:boolean}){
 const [data,setData]=useState<Data>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [name,setName]=useState('');const [vehicle,setVehicle]=useState('');const [from,setFrom]=useState('2025-09-01');const [to,setTo]=useState('');const [message,setMessage]=useState('');const router=useRouter();
 useEffect(()=>{const controller=new AbortController();fetch('/api/kpi/workify-names',{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[]);
 async function act(action:string,rule?:object){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/kpi/workify-names',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,rule})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setMessage(action==='apply'?(d.sync_warning??'Reglerna har körts på befintliga rader utan fordon. KPI-rapporten uppdateras i bakgrunden.'):'Regeln har sparats i Hubben.');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara')}finally{setBusy(false)}}
 return <section className="panel"><h2>Workify: namn → fordon</h2><p>Regnummer och registrerat fordon har alltid företräde. När båda saknas används en sparad regel för exakt namn i <strong>Förare</strong>. Stora och små bokstäver samt extra mellanslag spelar ingen roll. Regeln gäller transportartiklar; projekt- och lagerfördelning behålls.</p><p>Rader med tom eller 0 i Summa ignoreras. Originalunderlaget finns kvar.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!data&&!error&&<p>Hämtar regler…</p>}
 {canManage&&data&&<form onSubmit={e=>{e.preventDefault();void act('save',{name,vehicle_object_id:vehicle,valid_from:from,valid_to:to})}}><div className="mapping-grid"><label>Namn i Workify<input required maxLength={200} list="workify-driver-names" value={name} onChange={e=>setName(e.target.value)}/><datalist id="workify-driver-names">{data.names.map(n=><option key={n.name} value={n.name}/>)}</datalist></label><label>Fordon / intäktsbärare<select required value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Välj fordon</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.label==='INHYRDLASTBIL'?'Inhyrda Lastbilar':v.label}</option>)}</select></label><label>Gäller från<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Gäller till (valfritt)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button disabled={busy}>Spara namnregel</button></form>}
 {data&&<div className="table-wrap"><table><thead><tr><th>Namn</th><th>Fordon</th><th>Från</th><th>Till</th></tr></thead><tbody>{data.rules.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.vehicle_label==='INHYRDLASTBIL'?'Inhyrda Lastbilar':r.vehicle_label}</td><td>{r.valid_from}</td><td>{canManage?<input aria-label={`Slutdatum för ${r.name}`} type="date" defaultValue={r.valid_to??''} min={r.valid_from} disabled={busy} onBlur={e=>{if(e.target.value&&e.target.value!==r.valid_to)void act('end',{id:r.id,valid_to:e.target.value})}}/>:r.valid_to??'Tills vidare'}</td></tr>)}</tbody></table>{data.rules.length===0&&<p>Inga namnregler sparade. Välj namn och fordon ovan.</p>}</div>}
 {canManage&&<p><button disabled={busy||!data?.rules.length} onClick={()=>void act('apply')}>Använd regler på redan importerade rader utan fordon</button></p>}
 {data&&<details><summary>Namn på befintliga rader utan fordon ({data.names.length})</summary><div className="table-wrap"><table><thead><tr><th>Namn</th><th>Rader</th><th>Summa</th><th/></tr></thead><tbody>{data.names.map(n=><tr key={n.name}><td>{n.name}</td><td>{n.rows}</td><td>{new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(n.amount)}</td><td>{canManage&&<button onClick={()=>setName(n.name)}>Välj namn</button>}</td></tr>)}</tbody></table></div></details>}
 </section>
}
