export type MonthlyMetric={key:string;label:string;value:number|null;unit:'kr'|'%';status:'source'|'estimate'|'partial'|'missing';basis:string};
export type MonthlyVehicle={key:string;label:string;vehicle:string;invoiced_revenue:number;recorded_revenue:number;cost:number;fuel:number;hired:boolean};
export type FuelSourceReport={total_cost:number|null;piusi_cost:number|null;piusi_liters:number|null;next_cost:number|null;next_tank_purchase_excluded:number;piusi_rows:number;review_rows:number;provisional_rows:number;unclassified_rows:number;last_transaction_at:string|null;source_state:{captured_at:string;last_connector_success:string|null;connector_status:string|null};basis:string;transactions:Array<{source:string;id:string;dt:string;vehicle:string|null;amount:number|null;liters:number|null;price_status:string;product:string|null}>};
export type TranspaPeriodTime={reported_vehicle_hours:number|null;available_vehicle_hours:number|null;worked_driver_hours:number|null;revenue_linked_driver_hours:number|null;unclassified_driver_hours:number|null;vehicles:Array<Record<string,string|number>>;drivers:Array<Record<string,string|number>>};
export type MonthlyCostUnit={key:string;label:string;revenue:number;cost:number;fuel:number;fuel_liters:number|null;worked_hours:number|null;occupied_hours:number|null;available_hours:number|null;children:Array<{vehicle?:string|null;project?:string|null}>};
export type TransportPeriodReport={economic_units?:MonthlyCostUnit[];fuel_sources?:FuelSourceReport;time?:TranspaPeriodTime;metrics:MonthlyMetric[];recorded_revenue:number|null;uninvoiced_revenue:number|null;cost:number|null;estimated_payroll:number|null;fuel:number|null;fuel_share:number|null;active_vehicle_count:number;coverage:{requested_months:number[];revenue_months:number;cost_months:number};vehicles:MonthlyVehicle[]};
export type MonthlyTransportReport={version:1;title:string;tenant:string;period:{fiscal_year:number;month:number;from:string;to:string;ytd_from:string;ytd_months:number[]};scope:Record<string,string>;cost_centers?:{code:string;name:string}[];month:TransportPeriodReport;ytd:TransportPeriodReport;indicators:{reported_vehicle_utilization:number|null;reported_hours:number|null;available_hours:number|null;definition:string};generation:string;synced_at:string;generated_at:string;source_document:string;invoicing_rule:string};
export const metricStatus={source:'Enligt underlag och rapportregel',estimate:'Preliminärt / uppskattning',partial:'Ofullständigt periodunderlag',missing:'Underlag saknas'};
export function monthlyValue(value:number|null|undefined,unit:string){return value==null?'Underlag saknas':new Intl.NumberFormat('sv-SE',{maximumFractionDigits:unit==='%'?1:0}).format(value)+' '+unit;}
export function monthlyRows(report:MonthlyTransportReport){return report.month.metrics.map((metric,i)=>({Nyckeltal:metric.label,Månad:metric.value,YTD:report.ytd.metrics[i].value,Enhet:metric.unit,Status:metricStatus[metric.status],'Status YTD':metricStatus[report.ytd.metrics[i].status],Definition:metric.basis}));}
