"use client";
import {useRef,useState} from "react";
import {createClient} from "@supabase/supabase-js";
type ImportResult={ok?:boolean;parser_key?:string;reason?:string;error?:string;detail?:string;extraction?:{orders?:unknown[];order_count?:number};canonicalization?:{accepted?:boolean;orders?:number;rows?:number;events?:number}};
const TENANT="944597b6-9c46-4bef-998d-f19e23c4245b";
export default function DocumentImport(){
 const input=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ImportResult|null>(null);
 async function upload(){if(!file)return;setBusy(true);setError("");setResult(null);try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error("Importtjänsten saknar konfiguration.");const supabase=createClient(url,key);const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Du behöver vara inloggad i Humla för att importera.");const body=new FormData();body.append("file",file);body.append("tenant_id",TENANT);const response=await fetch(url+"/functions/v1/hub-document-import",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,apikey:key},body});const data=await response.json() as ImportResult;if(!response.ok)throw new Error(data.detail||data.error||data.reason||"Importen misslyckades.");setResult(data);}catch(e){setError(e instanceof Error?e.message:"Importen misslyckades.");}finally{setBusy(false);}}
 return <section className="section"><div className="sectionhead"><div><span className="label">IMPORTMOTOR</span><h2>PDF-import</h2></div></div><div className="importDrop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f?.type==="application/pdf")setFile(f);}}><input ref={input} hidden type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="importIcon">PDF</div><div><b>{file?file.name:"Släpp PDF här eller klicka för att välja"}</b><p>{file?Math.round(file.size/1024)+" kB":"Verifierade dokumentprofiler · max 20 MB"}</p></div><button type="button" disabled={!file||busy} onClick={e=>{e.stopPropagation();void upload();}}>{busy?"Tolkar…":"Importera"}</button></div>{error&&<div className="importAlert bad"><b>Importen stoppades</b><span>{error}</span></div>}{result&&<div className="importSummary"><article><small>STATUS</small><b className={result.ok?"green":""}>{result.ok?"Godkänd":"Kontroll krävs"}</b></article><article><small>PARSER</small><b>{result.parser_key||"Identifierad"}</b></article><article><small>ORDRAR</small><b>{result.extraction?.order_count??result.extraction?.orders?.length??result.canonicalization?.orders??0}</b></article><article><small>RADER</small><b>{result.canonicalization?.rows??0}</b></article><article><small>CANONICAL</small><b>{result.canonicalization?.accepted?"Skapad":"Kontrollerad"}</b></article></div>}</section>;
}
