"use client";
import {useEffect,useState} from "react";
type Row={id:string;external_vehicle_id:string;occurred_on:string;amount:number;account:string;description:string|null;status:string;external_reference:string;error_message:string|null};
export default function RepairOutbox(){
 const [rows,setRows]=useState<Row[]>([]),[picked,setPicked]=useState<string[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/integrationer/fordonskontrollen/reparationskostnader",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.rows);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function change(status:"approved"|"excluded"){setBusy(true);try{const r=await fetch("/api/integrationer/fordonskontrollen/reparationskostnader",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ids:picked,status})});const j=await r.json();if(!r.ok)throw Error(j.error);setError(j.updated+" rader uppdaterade. "+j.note);setPicked([]);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="page" style={{padding:24}}><h1>Fordonskontrollen – reparationskostnader</h1><p>NEXT-kostnader med entydig fordonskoppling. Granska innan återföring. Skriv-API för kostnader är ännu inte verifierat; godkännande skickar inte data externt.</p><p>Här visas högst 500 transaktioner åt gången. Välj alla omfattar endast dessa visade rader.</p><p>{rows.filter(r=>r.status==="pending_review").length} väntar på granskning · {rows.filter(r=>r.status==="approved").length} godkända</p>{error&&<p role="status">{error}</p>}<p><a href="/api/integrationer/fordonskontrollen/reparationskostnader/export">Exportera godkända kostnader (CSV)</a></p><button disabled={busy||!rows.some(r=>r.status==="pending_review")} onClick={()=>setPicked(rows.filter(r=>r.status==="pending_review").map(r=>r.id))}>Välj alla väntande (visade)</button> <button disabled={!picked.length} onClick={()=>setPicked([])}>Avmarkera alla</button> <button disabled={busy||!picked.length} onClick={()=>change("approved")}>Godkänn markerade</button> <button disabled={busy||!picked.length} onClick={()=>change("excluded")}>Undanta markerade</button><div style={{overflowX:"auto"}}><table><thead><tr><th>Välj</th><th>Datum</th><th>Fordonskontrollen-ID</th><th>Konto</th><th>Beskrivning</th><th>Belopp</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input type="checkbox" disabled={r.status!=="pending_review"} checked={picked.includes(r.id)} onChange={e=>setPicked(e.target.checked?[...picked,r.id]:picked.filter(x=>x!==r.id))}/></td><td>{r.occurred_on}</td><td>{r.external_vehicle_id}</td><td>{r.account}</td><td>{r.description}</td><td>{Number(r.amount).toLocaleString("sv-SE")} kr</td><td>{r.status}</td></tr>)}</tbody></table></div></main>;
}