"use client";
import {useEffect,useState} from "react";
export default function FuelReview(){
 const [data,setData]=useState<any>(null),[hub,setHub]=useState<any>(null),[tab,setTab]=useState("fuel"),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/kpi/hub-fuel",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);const h=await fetch("/api/kpi/control-panel",{cache:"no-store"});const hj=await h.json();if(h.ok)setHub(hj);else throw Error(hj.error||"Kontrollpanelen kunde inte läsas");}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function save(status:string){
 if(!selected||busy)return;setBusy(true);setMessage("Sparar");
 const r=await fetch("/api/kpi/hub-fuel/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,status,note,correctedCost:amount?Number(amount):null})});
 const j=await r.json();if(!r.ok){setMessage(j.error);setBusy(false);return;}setSelected(null);setNote("");setAmount("");setMessage("Sparat");await load();setBusy(false);
 }
 const rows=(data?.transactions||[]).filter((x:any)=>(filter==="all"?x.costStatus==="manual_review":filter==="resolved"?x.costStatus==="approved"||x.costStatus==="excluded":x.costStatus==="manual_review"&&x.reviewReason===filter)).filter((x:any)=>(x.registration+" "+x.transactionId+" "+x.occurredAt).toLowerCase().includes(search.toLowerCase()));
 return <main className="page"><header className="pagehead"><div><div className="eyebrow">HUMLA HUB</div><h1>Kontrollpanel</h1><p>Administration av importavvikelser, datakvalitet och anslutningar. Originaluppgifter bevaras.</p></div></header>
 <section className="metrics"><div className="metric"><span>Att granska</span><strong>{data?.manualReviewCount??"–"}</strong></div><div className="metric"><span>Spärrade belopp</span><strong>{data?.excludedSuspiciousCostSek?.toLocaleString("sv-SE")??"–"} kr</strong></div></section>
 <div className="panel"><div className="toolbar"><button className={tab==="fuel"?"btn primary":"btn"} onClick={()=>setTab("fuel")}>B.Smart ({data?.manualReviewCount??"–"})</button><button className={tab==="hub"?"btn primary":"btn"} onClick={()=>setTab("hub")}>Övriga importavvikelser ({hub?.reviews?.length??"–"})</button><button className={tab==="connections"?"btn primary":"btn"} onClick={()=>setTab("connections")}>Integrationer</button><button className="btn" onClick={()=>load().catch(e=>setMessage(e.message))}>Uppdatera</button></div></div>
 {tab==="fuel"&&<div className="panel"><h2>B.Smart – prisavvikelser</h2><div className="toolbar"><input aria-label="Sök tankning" placeholder="Sök registrering, transaktions-ID eller datum" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrera avvikelser" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Att granska</option><option value="extreme_high_unit_price">Högt literpris</option><option value="extreme_low_unit_price">Lågt literpris</option><option value="invalid_volume">Ogiltig volym</option><option value="resolved">Tidigare beslut</option></select></div><div className="tablewrap"><table><thead><tr><th>Datum</th><th>Fordon</th><th>Liter</th><th>Originalbelopp</th><th>Orsak</th><th></th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td>{x.occurredAt}</td><td>{x.registration}</td><td>{x.liters}</td><td>{x.rawCostSek}</td><td>{x.reviewReason}</td><td><button className="btn" onClick={()=>{setSelected(x);setAmount("");setNote("");}}>Granska</button></td></tr>)}</tbody></table></div></div>}
 {tab==="hub"&&<div className="panel"><h2>Övriga importavvikelser</h2><p>Här visas öppna granskningsärenden från Humla Hub. Befintlig mappningsfunktion används för att åtgärda dem.</p><div className="tablewrap"><table><thead><tr><th>Datum</th><th>Typ</th><th>Orsak</th><th>Prioritet</th></tr></thead><tbody>{(hub?.reviews||[]).map((x:any)=><tr key={x.id}><td>{x.created_at?.slice(0,16)}</td><td>{x.review_type||x.activity_kind}</td><td>{x.reason_code}</td><td>{x.severity}</td></tr>)}</tbody></table></div><a className="btn primary" href="/kpi?view=review">Öppna granskning och mappning</a></div>}
 {tab==="connections"&&<div className="panel"><h2>Integrationsstatus</h2><div className="tablewrap"><table><thead><tr><th>Källa</th><th>Status</th><th>Senaste lyckade hämtning</th><th>Senaste fel</th></tr></thead><tbody>{(hub?.connections||[]).map((x:any,i:number)=><tr key={i}><td>{x.connector_type}</td><td>{x.status}</td><td>{x.last_success_at?new Date(x.last_success_at).toLocaleString("sv-SE"):"–"}</td><td>{x.last_error_at?new Date(x.last_error_at).toLocaleString("sv-SE"):"–"}</td></tr>)}</tbody></table></div></div>}
 {tab==="fuel"&&selected&&<section className="panel"><h2>Granska tankning</h2><p>{selected.registration} · {selected.liters} liter · original {selected.rawCostSek} kr</p><label>Korrigerad totalkostnad (kr) <input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Motivering <textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div><button className="btn primary" disabled={busy||!amount||note.trim().length<3} onClick={()=>save("approved")}>Godkänn korrigerat pris</button><button className="btn" disabled={busy||note.trim().length<3} onClick={()=>save("rejected")}>Exkludera</button><button className="btn" onClick={()=>setSelected(null)}>Avbryt</button></div></section>}
 <p role="status">{message}</p></main>;
}