import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {analysisQuery,type Analysis} from '@/lib/kpi/analysis';
import {KpiPrint} from '@/app/_components/kpi-print';
export const dynamic='force-dynamic';
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2});
export default async function AnalysisPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const raw=await searchParams;const params=new URLSearchParams(Object.entries(raw).filter((v):v is [string,string]=>v[1]!==undefined));
 let args;try{args=analysisQuery(params)}catch{return <main className="content"><h1>Välj rapportperiod</h1><a href="/kpi">Till KPI</a></main>}
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await db.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(!member)return <main>Arbetsyta saknas.</main>;
 const {data,error}=await db.rpc('hub_kpi_analysis_v2',{p_tenant_id:member.tenant_id,...args});if(error)return <main className="content"><h1>Analysen kunde inte läsas</h1><p>{error.message}</p><a href="/kpi">Till KPI</a></main>;
 const report=data as Analysis;
 function href(changes:Record<string,string|null>){const p=new URLSearchParams(params);p.delete('page');for(const [k,v]of Object.entries(changes))if(v===null)p.delete(k);else p.set(k,v);return `/kpi/analys?${p}`}
 const next=args.p_level==='group'?{level:'unit',filter:'group'}:args.p_level==='unit'?{level:'project',filter:'unit'}:{level:'transaction',filter:'project'};
 const nextGrain={year:'month',month:'week',week:'day',day:'day'}[args.p_grain]??'day';
 const exportParams=new URLSearchParams(params);exportParams.delete('page');
 return <main className="content" style={{maxWidth:1500,margin:'auto'}}><style>{`@media print{.no-print{display:none!important} details{break-inside:avoid} table{font-size:9px} body{background:white!important}}`}</style>
 <header><a className="no-print" href={`/kpi?view=kpi&from=${args.p_from}&to=${args.p_to}${args.p_filters.cost_center?'&cost_center='+encodeURIComponent(args.p_filters.cost_center):''}`}>← KPI</a><h1>Transportanalys</h1><p>{args.p_from} – {args.p_to} · {Object.entries(args.p_filters).map(([k,v])=>`${k}: ${v}`).join(' · ')||'Alla ekonomiska objekt'}</p>
 <div className="no-print"><a href={href({group:null,unit:null,vehicle:null,project:null,level:'group'})}>Transport</a> → <a href={href({unit:null,project:null,level:'unit'})}>Verksamhetsgrupp</a> → <a href={href({project:null,level:'project'})}>Enhet / fordon</a> → <a href={href({level:'transaction'})}>Projekt / transaktion</a></div>
 <div className="no-print"><a className="secondary" href={`/api/kpi/export?${exportParams}&format=xlsx`}>Exportera Excel</a> <a className="secondary" href={`/api/kpi/export?${exportParams}&format=pdf`}>Exportera PDF</a> <KpiPrint/></div></header>
 <section className="panel"><h2>Vald vy · beräknad i Humla Hub</h2><p>Omsättning {money.format(report.summary.revenue??0)} · Kostnad {money.format(report.summary.cost??0)} · Resultat {money.format(report.summary.result??0)} · Marginal {report.summary.margin_pct??'–'} %</p><p>NEXT {money.format(report.summary.next_cost??0)} · TransPA {money.format(report.summary.personnel_cost??0)} · {report.summary.rows} transaktioner</p></section>
 {args.p_level!=='transaction'&&<section className="panel"><h2>{args.p_level==='group'?'Verksamhetsgrupper':args.p_level==='unit'?'Ekonomiska enheter / fordon':'Kostnadsprojekt'}</h2><table><thead><tr><th>Objekt</th><th>Omsättning</th><th>Kostnad</th><th>Resultat</th><th>Rader</th></tr></thead><tbody>{report.groups.map(g=><tr key={g.key}><td><a href={href({[next.filter]:g.key,level:next.level})}>{g.label}</a></td><td>{money.format(g.revenue)}</td><td>{money.format(g.cost)}</td><td>{money.format(g.result)}</td><td>{g.rows}</td></tr>)}</tbody></table></section>}
 <section className="panel"><h2>Tid</h2><nav className="no-print">{Object.entries({year:'År',month:'Månad',week:'Vecka',day:'Dag'}).map(([key,label])=><a style={{marginRight:16}} key={key} href={href({grain:key,date_from:null,date_to:null})}>{label}</a>)}</nav><table><thead><tr><th>Period</th><th>Omsättning</th><th>Kostnad</th><th>Resultat</th></tr></thead><tbody>{report.periods.map(p=><tr key={p.period_start}><td><a href={href({grain:nextGrain,date_from:p.period_start,date_to:p.period_end,...(args.p_grain==='day'?{level:'transaction'}:{})})}>{p.period_start} – {p.period_end}</a></td><td>{money.format(p.revenue)}</td><td>{money.format(p.cost)}</td><td>{money.format(p.result)}</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>Originaltransaktioner</h2><p>100 rader per sida. Alla giltiga belopp finns med, även när fördelning saknas. Osäkra relationer visas utan kopplad enhet.</p><table><thead><tr><th>Datum / original</th><th>Källa</th><th>Enhet / fordon</th><th>Kostnadsställe</th><th>Projekt / konto</th><th>Kategori</th><th>Typ</th><th>Belopp</th></tr></thead><tbody>{report.transactions.map(t=><tr key={t.fact_id}><td><details><summary>{t.occurred_on} · {t.description??t.fact_id}</summary><p>{t.file_name??t.source} · rad {t.row_number??'–'} · {t.fact_id}</p><pre style={{whiteSpace:'pre-wrap',maxWidth:650}}>{JSON.stringify(t.original,null,2)}</pre></details></td><td>{t.source}</td><td>{t.unit_name??t.vehicle??'Ej fördelat'}</td><td>{t.cost_center==='unclassified'?'Ej klassificerat':`${t.cost_center??'–'} ${t.cost_center_name??''}`}</td><td>{t.project??'Ej klassificerat'} / {t.account??'–'}</td><td>{t.category}</td><td>{t.kind==='revenue'?'Intäkt':'Kostnad'}</td><td>{money.format(t.amount)}</td></tr>)}</tbody></table><nav className="no-print">{args.p_page>0&&<a href={href({page:String(args.p_page-1)})}>← Föregående</a>} {report.transactions.length===100&&<a href={href({page:String(args.p_page+1)})}>Nästa →</a>}</nav></section>
 <p>TransPA-kostnad beräknas inom vald grundperiod enligt Hub-modellen. Dag- och veckofilter delar samma underlag utan omräkning av övertid.</p></main>
}
