import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {cachedKpiReport} from '@/lib/kpi/report-cache';
import {analysisHref,analysisQuery,type Analysis} from '@/lib/kpi/analysis';
import {KpiPrint} from '@/app/_components/kpi-print';
import {KpiDetailShell} from '@/app/_components/kpi-detail-shell';
import {KpiEvidenceAmount} from '@/app/_components/kpi-evidence-amount';
export const dynamic='force-dynamic';
const money=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2});
const labels:Record<string,string>={cost_center:'Kostnadsställe',group:'Verksamhetsgrupp',unit:'Ekonomisk enhet',vehicle:'Fordon',project:'Projekt',category:'Kategori',kind:'Typ',source:'Källa',date_from:'Från',date_to:'Till',personnel:'Personal',fuel:'Bränsle',service_repair:'Service & Rep',depreciation:'Avskrivning',fixed:'Fasta kostnader',material:'Material',tipp_deponi:'Tipp / Deponi',hired:'Inhyrda',other:'Övrigt',cost:'Kostnad',revenue:'Intäkt',unassigned:'Ej fördelat'};
export default async function AnalysisPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const raw=await searchParams;const params=new URLSearchParams(Object.entries(raw).filter((v):v is [string,string]=>v[1]!==undefined));
 let args:ReturnType<typeof analysisQuery>;try{args=analysisQuery(params)}catch{return <KpiDetailShell query={params.toString()}><div className="content"><h1>Välj rapportperiod</h1><Link href="/kpi" prefetch={false}>Till KPI</Link></div></KpiDetailShell>}
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await db.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(!member)return <main>Arbetsyta saknas.</main>;
 const {data:canRead}=await db.rpc('hub_has_permission',{p_tenant_id:member.tenant_id,p_permission:'kpi.read'});
 if(!canRead)return <main>Du saknar åtkomst till KPI-underlagen.</main>;
 const rpc=args.p_filters.selected_months?'hub_kpi_analysis_months_v1':'hub_kpi_analysis_v2';
 const {data,error}=await cachedKpiReport(user.id,member.tenant_id,{report:'analysis',rpc,...args},async()=>db.rpc(rpc,{p_tenant_id:member.tenant_id,...args}));
 if(error)return <KpiDetailShell query={params.toString()}><div className="content"><h1>Analysen kunde inte läsas</h1><p>{error.message}</p><Link href="/kpi" prefetch={false}>Till KPI</Link></div></KpiDetailShell>;
 const report=data as Analysis;
 function href(changes:Record<string,string|null>){return analysisHref(params.toString(),{level:args.p_level,...changes})}
 const next=args.p_level==='group'?{level:'unit',filter:'group'}:args.p_level==='unit'?{level:'project',filter:'unit'}:{level:'transaction',filter:'project'};
 const nextGrain={year:'month',month:'week',week:'day',day:'day'}[args.p_grain]??'day';
 const exportParams=new URLSearchParams(params);exportParams.delete('page');exportParams.delete('view');
 const unitLabel=report.transactions.find(t=>t.unit_name)?.unit_name;
 const selectedMonths=Array.isArray(args.p_filters.selected_months)?args.p_filters.selected_months.map(m=>({9:'Sep',10:'Okt',11:'Nov',12:'Dec',1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'Maj',6:'Jun',7:'Jul',8:'Aug'}[m])).join(' + '):null;
 return <KpiDetailShell query={params.toString()}><div className="content" style={{maxWidth:1500,margin:'auto'}}>
 <style>{`@media print{.no-print{display:none!important} details{break-inside:avoid} table{font-size:9px} body{background:white!important}}`}</style>
 <header><h2>Transportanalys</h2><p>{selectedMonths?`${selectedMonths} · ${args.p_filters.fiscal_year}/${Number(args.p_filters.fiscal_year)+1}`:`${args.p_from} – ${args.p_to}`}</p>
 <div className="analysis-filters">{Object.entries(args.p_filters).filter(([k])=>!['selected_months','fiscal_year'].includes(k)).map(([k,v])=><span key={k}>{labels[k]??k}: {k==='unit'?(unitLabel??'Vald enhet'):labels[String(v)]??String(v)}</span>)}</div>
 <nav className="no-print analysis-filters" aria-label="Underlagets hierarki"><Link prefetch={false} href={href({group:null,unit:null,vehicle:null,project:null,level:'group'})}>Verksamhetsgrupper</Link> → <Link prefetch={false} href={href({unit:null,vehicle:null,project:null,level:'unit'})}>Ekonomiska enheter</Link> → <Link prefetch={false} href={href({project:null,level:'project'})}>Kostnadsprojekt</Link> → <Link prefetch={false} href={href({level:'transaction'})}>Transaktioner</Link></nav>
 <div className="dashboard-report-actions no-print"><a className="secondary" href={`/api/kpi/export?${exportParams}&format=xlsx`}>Exportera Excel</a><a className="secondary" href={`/api/kpi/export?${exportParams}&format=pdf`}>Exportera PDF</a><KpiPrint/></div></header>
 <section className="panel"><h2>Totalsummor för aktuellt urval</h2><div className="analysis-totals"><Link prefetch={false} href={href({kind:'revenue'})}>Omsättning<strong>{money.format(report.summary.revenue??0)}</strong></Link><Link prefetch={false} href={href({kind:'cost'})}>Kostnad<strong>{money.format(report.summary.cost??0)}</strong></Link><Link prefetch={false} href={href({kind:null})}>Resultat<strong>{money.format(report.summary.result??0)}</strong></Link><div>Marginal<strong>{report.summary.margin_pct??'–'} %</strong></div></div>
 <p><Link prefetch={false} href={href({source:'NEXT',kind:'cost'})}>NEXT {money.format(report.summary.next_cost??0)}</Link> · <Link prefetch={false} href={href({source:'TransPA',kind:'cost'})}>TransPA {money.format(report.summary.personnel_cost??0)}</Link> · {report.summary.rows} transaktioner</p></section>
 {args.p_level!=='transaction'&&<section className="panel"><h2>{args.p_level==='group'?'Verksamhetsgrupper':args.p_level==='unit'?'Ekonomiska enheter / fordon':'Kostnadsprojekt'}</h2><table><thead><tr><th>Objekt</th><th>Omsättning</th><th>Kostnad</th><th>Resultat</th><th>Rader</th></tr></thead><tbody>{report.groups.map(g=><tr key={g.key}><td><Link prefetch={false} href={href({[next.filter]:g.key,level:next.level})}>{g.label}</Link></td><td><Link prefetch={false} href={href({[next.filter]:g.key,level:next.level,kind:'revenue'})}>{money.format(g.revenue)}</Link></td><td><Link prefetch={false} href={href({[next.filter]:g.key,level:next.level,kind:'cost'})}>{money.format(g.cost)}</Link></td><td><Link prefetch={false} href={href({[next.filter]:g.key,level:next.level,kind:null})}>{money.format(g.result)}</Link></td><td>{g.rows}</td></tr>)}</tbody></table>{report.groups.length===0&&<p>Inga underlag i detta urval.</p>}</section>}
 <section className="panel"><h2>Tid</h2><nav className="no-print analysis-filters">{Object.entries({year:'År',month:'Månad',week:'Vecka',day:'Dag'}).map(([key,label])=><Link prefetch={false} key={key} href={href({grain:key,date_from:null,date_to:null})}>{label}</Link>)}</nav><table><thead><tr><th>Period</th><th>Omsättning</th><th>Kostnad</th><th>Resultat</th></tr></thead><tbody>{report.periods.map(p=>{const changes={grain:nextGrain,date_from:p.period_start,date_to:p.period_end,...(args.p_grain==='day'?{level:'transaction'}:{})};return <tr key={p.period_start}><td><Link prefetch={false} href={href(changes)}>{p.period_start} – {p.period_end}</Link></td><td><Link prefetch={false} href={href({...changes,kind:'revenue'})}>{money.format(p.revenue)}</Link></td><td><Link prefetch={false} href={href({...changes,kind:'cost'})}>{money.format(p.cost)}</Link></td><td><Link prefetch={false} href={href({...changes,kind:null})}>{money.format(p.result)}</Link></td></tr>})}</tbody></table></section>
 <section className="panel"><h2>Originaltransaktioner</h2><p>100 rader per sida. Klicka på datum/rad för originalunderlaget. Alla giltiga belopp finns med, även när fördelning saknas. ”På fordon” innebär att intäkten följer fordonet och inte behöver ett separat projekt.</p><table><thead><tr><th>Datum / original</th><th>Källa</th><th>Enhet / fordon</th><th>Kostnadsställe</th><th>Projekt / konto</th><th>Kategori</th><th>Typ</th><th>Belopp</th></tr></thead><tbody>{report.transactions.map(t=><tr key={t.fact_id}><td><details id={`underlag-${t.fact_id}`}><summary>{t.occurred_on} · {t.description??t.fact_id}</summary><p>{t.file_name??t.source} · rad {t.row_number??'–'} · {t.fact_id}</p><pre style={{whiteSpace:'pre-wrap',maxWidth:650}}>{JSON.stringify(t.original,null,2)}</pre></details></td><td>{t.source}</td><td>{t.unit_name??t.vehicle??'Ej fördelat'}{!t.unit_name&&t.vehicle&&<small style={{display:'block',marginTop:4}}>Fordon kopplat · ingen ekonomisk enhet för datumet</small>}</td><td>{t.cost_center==='unclassified'?'Ej klassificerat':`${t.cost_center??'–'} ${t.cost_center_name??''}`}</td><td>{t.project??(t.vehicle?'På fordon':'Projekt / fordon saknas')} / {t.account??'–'}</td><td>{labels[t.category]??t.category}</td><td>{t.kind==='revenue'?'Intäkt':'Kostnad'}</td><td><KpiEvidenceAmount id={`underlag-${t.fact_id}`} amount={money.format(t.amount)}/></td></tr>)}</tbody></table><nav className="no-print">{args.p_page>0&&<Link prefetch={false} href={href({page:String(args.p_page-1)})}>← Föregående</Link>} {report.transactions.length===100&&<Link prefetch={false} href={href({page:String(args.p_page+1)})}>Nästa →</Link>}</nav>{report.transactions.length===0&&<p>Inga transaktioner i detta urval.</p>}</section>
 <p>Underlagen och beräkningarna hämtas från Humla Hub. TransPA-kostnad använder samma Hub-underlag och månadsurval som Översikten.</p></div></KpiDetailShell>
}
