import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {KpiDetailShell} from '@/app/_components/kpi-detail-shell';
import {ProjectInternalEvidence} from '@/app/_components/project-internal-evidence';
import {ProjectCostCenterSelect} from '@/app/_components/project-cost-center-select';
import {ProjectReportExport} from '@/app/_components/project-report-export';
import type {ProjectReport} from '@/lib/hub/project-report';
import styles from './project-report.module.css';
export const dynamic='force-dynamic';
export const maxDuration=60;
const money=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(v);
const percent=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{maximumFractionDigits:1}).format(v)+' %';
const categories:Record<string,string>={personnel:'Personal',material:'Material',tipp_deponi:'Tipp/deponi',hired:'Inhyrda / UE',fuel:'Bränsle',fixed:'Fasta',service_repair:'Service och reparation',other:'Övrigt',unclassified:'Ej kategoriserat'};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await db.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();
 const {data:allowed}=member?await db.rpc('hub_has_permission',{p_tenant_id:member.tenant_id,p_permission:'kpi.read'}):{data:false};
 if(!member||!allowed)return <main><h1>Du saknar behörighet till projektuppföljningen.</h1></main>;
 const raw=await searchParams,q=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Array.isArray(v)?v[0]:v])),groups=[...new Set((Array.isArray(raw.group)?raw.group:raw.group?[raw.group]:[]).filter(Boolean))],now=new Date(),fy=now.getUTCMonth()>=8?now.getUTCFullYear():now.getUTCFullYear()-1;
 const from=q.from??`${fy}-09-01`,to=q.to??`${fy+1}-08-31`,center=q.center||null,manager=q.manager||null,project=q.project||null,page=Number(q.page??0),kind=q.kind||null;
 if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||to<from||!Number.isInteger(page)||page<0||center&&!['10','20','30','40','50','60','90'].includes(center)||kind&&!['revenue','cost'].includes(kind)||project&&!/^[0-9a-f-]{36}$/i.test(project))return <main className="content"><h1>Ogiltigt projekturval</h1><Link href="/kpi/projekt">Återställ urval</Link></main>;
 const args={p_tenant_id:member.tenant_id,p_from:from,p_to:to,p_center:center,p_manager:manager};
 const [result,optionResult]=await Promise.all([
  db.rpc('hub_kpi_project_report_v4',{...args,p_project:project,p_page:page,p_kind:kind,p_groups:groups.length?groups:null}),
  groups.length||project?db.rpc('hub_kpi_project_report_v4',{...args,p_project:null,p_page:0,p_kind:null,p_groups:null}):Promise.resolve(null)
 ]);
 const {data,error}=result;
 const href=(changes:Record<string,string|null>)=>{const p=new URLSearchParams({from,to});for(const [k,v] of Object.entries({center,manager,project,kind,...changes}))if(v&&k!=='group')p.set(k,v);for(const g of ('group' in changes?changes.group?[changes.group]:[]:groups))p.append('group',g);return '/kpi/projekt?'+p;};
 if(error||!data)return <KpiDetailShell query="" title="Projektuppföljning"><section className="panel"><h2>Projektunderlaget kunde inte hämtas</h2><p>Inga belopp visas när underlaget inte kan läsas.</p><Link href={href({})}>Försök igen</Link></section></KpiDetailShell>;
 const report=data as ProjectReport,selected=report.projects.find(p=>p.id===project),visible=report.projects.filter(p=>p.rows>0&&(!q.search||[p.project_number,p.project_name,p.project_manager,p.business_group].join(' ').toLocaleLowerCase('sv-SE').includes(q.search.toLocaleLowerCase('sv-SE'))));
 const optionReport=(optionResult?optionResult.data:data) as ProjectReport|null;
 const groupOptions=optionReport?[...new Set(optionReport.projects.filter(p=>p.revenue!==0||p.cost!==0).map(p=>p.business_group||'Ingen grupp'))].sort((a,b)=>a.localeCompare(b,'sv-SE')):[];
 const inactiveGroups=groups.filter(g=>!groupOptions.includes(g));
 const firstYear=Number(from.slice(0,4)),baseFY=Number(from.slice(5,7))>=9?firstYear:firstYear-1,maxCost=Math.max(1,...report.months.map(m=>Math.max(Math.abs(m.revenue),Math.abs(m.cost))));
 return <KpiDetailShell query="" title="Projektuppföljning" breadcrumb="Humla Dashboard / Projekt" extraNavigation={<><Link href="/kpi/kontrollpanel" prefetch={false}>Kontrollpanel</Link><Link href="/kpi?view=internal" prefetch={false}>Interna körningar</Link></>}><div className={styles.content}>
  <section className="panel"><h2>{selected?`${selected.project_number} · ${selected.project_name}`:'Projekt — alla kostnadsställen'}</h2><p className={styles.note}>{report.scope} Personal ingår en gång i kostnader och resultat. NeXT används för övriga kostnadsställen; Transport använder TransPA via API. Externa intäkter för Sortergård och Transport hämtas från Workify.</p>
   <form className={styles.filters} key={JSON.stringify([from,to,center,manager,groups,project])}><label>Från<input type="date" name="from" defaultValue={from} required/></label><label>Till<input type="date" name="to" defaultValue={to} required/></label><ProjectCostCenterSelect value={center}/><label>Projektledare<select name="manager" defaultValue={manager??''}><option value="">Alla projektledare</option>{report.managers.map(m=><option key={m} value={m}>{m}</option>)}</select></label><fieldset className={styles.groupFilter}><legend>Verksamhetsgrupper</legend><div className={styles.groupChoices}>{groupOptions.map(g=><label key={g}><input type="checkbox" name="group" value={g} defaultChecked={groups.includes(g)}/>{g}</label>)}</div>{!optionResult?.error&&!groupOptions.length&&<p>Inga verksamhetsgrupper har belopp i urvalet.</p>}{optionResult?.error&&<p role="alert">Gruppvalen kunde inte hämtas. Försök igen.</p>}{inactiveGroups.length>0&&<p>Valda grupper utan belopp i urvalet: {inactiveGroups.join(', ')}.{inactiveGroups.map(g=><input type="hidden" key={g} name="group" value={g}/>)}</p>}<small>Visar grupper med intäkter eller kostnader i valt KST, period och projektledarurval. Inga kryss = alla grupper.</small> <Link href={href({group:null,project:null,kind:null})}>Visa alla grupper</Link></fieldset><label>Sök i projektlistan<input name="search" defaultValue={q.search??''} placeholder="Projektnummer, namn eller grupp"/></label>{project&&<input type="hidden" name="project" value={project}/>}<button className="primary">Visa urval</button><Link href={href({project:null,kind:null})}>Alla projekt i urvalet</Link></form>
   <p className={styles.note}>Senaste NeXT-bokföringsdatum i underlaget: {report.latest_source_date??'Underlag saknas'}. {report.excluded_rows} felaktiga poster undantagna. {report.summary.vehicle_allocation_pending??0} poster väntar på fordonsfördelning men ingår på säkert identifierat projekt. {report.hub_unmapped_rows} Workify/TransPA-rader saknar entydigt registerprojekt och är undantagna. {report.summary.unclassified_rows??0} kostnadsrader saknar kategori men ingår i kostnaden.</p><ProjectReportExport report={report}/>
  </section>
  <div className={styles.months}>{Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(baseFY,8+i,1)),end=new Date(Date.UTC(baseFY,9+i,0)),a=d.toISOString().slice(0,10),b=end.toISOString().slice(0,10);return <Link key={a} href={href({from:a,to:b})}>{d.toLocaleDateString('sv-SE',{month:'short',timeZone:'UTC'})}</Link>})}<Link href={href({from:`${baseFY}-09-01`,to:`${baseFY+1}-08-31`})}>Hela verksamhetsåret</Link></div>
  <div className={styles.cards}>{[['Intäkter',money(report.summary.revenue)],['Kostnader',money(report.summary.cost)],['Resultat',money(report.summary.result)],['Projektmarginal',percent(report.summary.margin)],['Personal (ingår i kostnad)',money(report.summary.personnel)]].map(([label,value])=><a className={styles.card} key={label} href={project?'#underlag':'#projektlista'}><small>{label}</small><strong>{value}</strong></a>)}</div>
  <section className="panel"><h2>Externa och interna poster</h2><p className={styles.note}>NeXT-kostnader och projektintäkter ingår en gång. För KST 20/30 används externa Workify-intäkter i stället för NeXT-intäkter. Interna Workify-körningar är kostnad på mottagande projekt och intäkt på utförande projekt. Mottagarens Workify-belopp räknas av mot redan bokfört på 4600 inom valt projekt och period. Resterande belopp läggs till kostnaden. Interna belopp nedan ingår redan i totalsummorna.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Extern intäkt</th><th>Intern intäkt</th><th>Extern kostnad</th><th>Intern kostnad</th></tr></thead><tbody><tr>{[report.summary.external_revenue,report.summary.internal_revenue,report.summary.external_cost,report.summary.internal_cost].map((v,i)=><td key={i}>{money(v)}</td>)}</tr></tbody></table></div></section>
  <section className="panel"><h2>Interna Workify-belopp i resultatet</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Workify-kostnad, mottagande projekt</th><th>Bokfört på 4600</th><th>Avräknat mot 4600</th><th>Tillägg till kostnaden</th><th>Intern intäkt, utförande projekt</th></tr></thead><tbody><tr>{[report.internal_workify.original,report.internal_workify.booked_4600,report.internal_workify.covered_4600,report.internal_workify.added,report.internal_workify.income].map((v,i)=><td key={i}>{money(v)}</td>)}</tr></tbody></table></div><p className={styles.note}>Intäkter och kostnader ovan ingår redan i resultatet. Intern intäkt kräver en entydig koppling till utförande projekt; kopplingarna hanteras i Kontrollpanelen. {report.internal_workify.rows} interna kostnadsrader och {report.internal_workify.income_rows} intäktsrader. {report.internal_workify.pending_rows} mottagarrader väntar på fakturering eller granskning och ingår ännu inte. Avräkningen mot 4600 görs på projektsumman inom vald period; raden i detaljunderlaget visar det proportionellt fördelade kostnadstillägget. Interna belopp är inte eliminerade mellan kostnadsställen i denna projektvy.</p></section>
  <section className="panel"><h2>Utveckling per månad</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Månad</th><th>Intäkter</th><th>Kostnader</th><th>Resultat</th></tr></thead><tbody>{report.months.map(m=>{const end=new Date(Date.UTC(Number(m.month_start.slice(0,4)),Number(m.month_start.slice(5,7)),0)).toISOString().slice(0,10);return <tr key={m.month_start}><th><Link href={href({from:m.month_start,to:end})}>{m.month_start.slice(0,7)}</Link></th><td>{money(m.revenue)}<div className={styles.bar} style={{width:`${Math.abs(m.revenue)/maxCost*100}%`}}/></td><td>{money(m.cost)}<div className={styles.bar} style={{width:`${Math.abs(m.cost)/maxCost*100}%`,background:'#94a3b8'}}/></td><td className={m.result<0?styles.negative:''}>{money(m.result)}</td></tr>})}</tbody></table></div>{!report.months.length&&<p>Inga importerade poster för urvalet.</p>}</section>
  <section className="panel" id="projektlista"><h2>Projekt med underlag ({visible.length})</h2><p className={styles.note}>Klicka på projekt eller belopp för att se underlaget. Projekt utan poster i perioden visas inte i listan. Sökningen begränsar listan; totalsummorna följer period, KST, projektledare och verksamhetsgrupp.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Projekt</th><th>KST</th><th>Projektledare / grupp</th><th>Intäkter</th><th>Kostnader</th><th>Intern intäkt (ingår)</th><th>Intern kostnad (ingår)</th><th>Resultat</th><th>Marginal</th><th>Personal</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><th><Link href={href({project:p.id,kind:null})}>{p.project_number} · {p.project_name}</Link></th><td>{p.cost_center}</td><td>{p.project_manager}<br/><small>{p.business_group??'—'}</small></td><td className={styles.number}><Link href={href({project:p.id,kind:'revenue'})}>{money(p.revenue)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'cost'})}>{money(p.cost)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'revenue'})}>{money(p.internal_revenue)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'cost'})}>{money(p.internal_cost)}</Link></td><td className={`${styles.number} ${p.result<0?styles.negative:''}`}><Link href={href({project:p.id,kind:null})}>{money(p.result)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:null})}>{percent(p.margin)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'cost'})}>{money(p.personnel)}</Link></td></tr>)}</tbody></table></div></section>
  {project&&<section className="panel" id="underlag"><h2>Projektunderlag · {report.transaction_count} poster</h2><nav className={styles.pager}><Link href={href({kind:null})}>Alla poster</Link><Link href={href({kind:'revenue'})}>Intäkter</Link><Link href={href({kind:'cost'})}>Kostnader</Link></nav><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Datum</th><th>Typ</th><th>Belopp</th><th>Konto / kategori</th><th>Beskrivning</th><th>Källa / fil / rad</th></tr></thead><tbody>{report.transactions.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.kind==='revenue'?'Intäkt':'Kostnad'}{t.internal?' · intern':''}</td><td className={styles.number}>{money(t.amount)}</td><td>{t.account}<br/>{categories[t.category]??t.category}</td><td>{t.description}{t.validation_errors.length>0&&<small className={styles.muted}><br/>Fordonsfördelning kvarstår; ingår på projektet.</small>}</td><td>{t.source}<br/>{t.file_name}{t.row_number!=null&&<><br/>Rad {t.row_number}</>}</td></tr>)}</tbody></table></div><nav className={styles.pager}>{page>0&&<Link href={href({page:String(page-1)})}>← Föregående</Link>}<span>Sida {page+1} · högst 200 poster per sida</span>{(page+1)*200<report.transaction_count&&<Link href={href({page:String(page+1)})}>Nästa →</Link>}</nav><p className={styles.note}>Budget och slutprognos kräver kalkyl och återstående arbete. Här visas importerat utfall och, för Transport, beräknad personal från TransPA.</p></section>}
 {selected&&<ProjectInternalEvidence key={`${from}:${to}:${project}`} from={from} to={to} project={selected.id}/>}
 </div></KpiDetailShell>;
}
