import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {KpiDetailShell} from '@/app/_components/kpi-detail-shell';
import {ProjectInternalEvidence} from '@/app/_components/project-internal-evidence';
import {ProjectReportExport} from '@/app/_components/project-report-export';
import type {ProjectReport} from '@/lib/hub/project-report';
import styles from './project-report.module.css';
export const dynamic='force-dynamic';
export const maxDuration=60;
const money=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(v);
const percent=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{maximumFractionDigits:1}).format(v)+' %';
const categories:Record<string,string>={personnel:'Personal',material:'Material',tipp_deponi:'Tipp/deponi',hired:'Inhyrda / UE',fuel:'Bränsle',fixed:'Fasta',service_repair:'Service och reparation',other:'Övrigt',unclassified:'Ej kategoriserat'};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await db.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();
 const {data:allowed}=member?await db.rpc('hub_has_permission',{p_tenant_id:member.tenant_id,p_permission:'kpi.read'}):{data:false};
 if(!member||!allowed)return <main><h1>Du saknar behörighet till projektuppföljningen.</h1></main>;
 const q=await searchParams,now=new Date(),fy=now.getUTCMonth()>=8?now.getUTCFullYear():now.getUTCFullYear()-1;
 const from=q.from??`${fy}-09-01`,to=q.to??`${fy+1}-08-31`,center=q.center||null,manager=q.manager||null,project=q.project||null,page=Number(q.page??0),kind=q.kind||null;
 if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||to<from||!Number.isInteger(page)||page<0||center&&!['10','60'].includes(center)||kind&&!['revenue','cost'].includes(kind)||project&&!/^[0-9a-f-]{36}$/i.test(project))return <main className="content"><h1>Ogiltigt projekturval</h1><Link href="/kpi/projekt">Återställ urval</Link></main>;
 const {data,error}=await db.rpc('hub_kpi_project_report_v1',{p_tenant_id:member.tenant_id,p_from:from,p_to:to,p_center:center,p_manager:manager,p_project:project,p_page:page,p_kind:kind});
 const href=(changes:Record<string,string|null>)=>{const p=new URLSearchParams({from,to});for(const [k,v] of Object.entries({center,manager,project,kind,...changes}))if(v)p.set(k,v);return '/kpi/projekt?'+p;};
 if(error||!data)return <KpiDetailShell query="" title="Projektuppföljning"><section className="panel"><h2>Projektunderlaget kunde inte hämtas</h2><p>Inga belopp visas när underlaget inte kan läsas.</p><Link href={href({})}>Försök igen</Link></section></KpiDetailShell>;
 const report=data as ProjectReport,selected=report.projects.find(p=>p.id===project),visible=report.projects.filter(p=>p.rows>0&&(!q.search||[p.project_number,p.project_name,p.project_manager,p.business_group].join(' ').toLocaleLowerCase('sv-SE').includes(q.search.toLocaleLowerCase('sv-SE'))));
 const firstYear=Number(from.slice(0,4)),baseFY=Number(from.slice(5,7))>=9?firstYear:firstYear-1,maxCost=Math.max(1,...report.months.map(m=>Math.max(Math.abs(m.revenue),Math.abs(m.cost))));
 return <KpiDetailShell query="" title="Projektuppföljning" breadcrumb="Humla Dashboard / Entreprenad och Skåne" extraNavigation={<><Link href="/kpi/kontrollpanel" prefetch={false}>Kontrollpanel</Link><Link href="/kpi?view=internal" prefetch={false}>Interna körningar</Link></>}><div className={styles.content}>
  <section className="panel"><h2>{selected?`${selected.project_number} · ${selected.project_name}`:'Projekt — KST 10 och 60'}</h2><p className={styles.note}>{report.scope} Personal ingår i kostnader och resultat här och hämtas från NeXT. Transport KST 30 använder TransPA via API.</p>
   <form className={styles.filters}><label>Från<input type="date" name="from" defaultValue={from} required/></label><label>Till<input type="date" name="to" defaultValue={to} required/></label><label>Kostnadsställe<select name="center" defaultValue={center??''}><option value="">10 + 60</option><option value="10">10 Entreprenad och maskinuthyrning</option><option value="60">60 Skåne</option></select></label><label>Projektledare<select name="manager" defaultValue={manager??''}><option value="">Alla projektledare</option>{report.managers.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>Sök i projektlistan<input name="search" defaultValue={q.search??''} placeholder="Projektnummer, namn eller grupp"/></label>{project&&<input type="hidden" name="project" value={project}/>}<button className="primary">Visa urval</button><Link href={href({project:null,kind:null})}>Alla projekt i urvalet</Link></form>
   <p className={styles.note}>Senaste bokföringsdatum i underlaget: {report.latest_source_date??'Underlag saknas'}. {report.excluded_rows} felaktiga poster undantagna. {report.summary.vehicle_allocation_pending??0} poster väntar på fordonsfördelning men ingår på säkert identifierat projekt. {report.summary.unclassified_rows??0} kostnadsrader saknar kategori men ingår i kostnaden.</p><ProjectReportExport report={report}/>
  </section>
  <div className={styles.months}>{Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(baseFY,8+i,1)),end=new Date(Date.UTC(baseFY,9+i,0)),a=d.toISOString().slice(0,10),b=end.toISOString().slice(0,10);return <Link key={a} href={href({from:a,to:b})}>{d.toLocaleDateString('sv-SE',{month:'short',timeZone:'UTC'})}</Link>})}<Link href={href({from:`${baseFY}-09-01`,to:`${baseFY+1}-08-31`})}>Hela verksamhetsåret</Link></div>
  <div className={styles.cards}>{[['Intäkter',money(report.summary.revenue)],['Kostnader',money(report.summary.cost)],['Bokfört resultat',money(report.summary.result)],['Projektmarginal',percent(report.summary.margin)],['Personal från NeXT',money(report.summary.personnel)]].map(([label,value])=><a className={styles.card} key={label} href={project?'#underlag':'#projektlista'}><small>{label}</small><strong>{value}</strong></a>)}</div>
  <section className="panel"><h2>Externa och interna bokförda poster</h2><p className={styles.note}>NeXT-poster ingår en gång i projektresultatet. Interna intäkter och kostnader nedan är delar av totalsummorna. Workify-körningar läggs inte ovanpå NeXT utan avstämning.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Extern intäkt</th><th>Intern intäkt</th><th>Extern kostnad</th><th>Intern kostnad</th></tr></thead><tbody><tr>{[report.summary.external_revenue,report.summary.internal_revenue,report.summary.external_cost,report.summary.internal_cost].map((v,i)=><td key={i}>{money(v)}</td>)}</tr></tbody></table></div></section>
  <section className="panel"><h2>Utveckling per månad</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Månad</th><th>Intäkter</th><th>Kostnader</th><th>Bokfört resultat</th></tr></thead><tbody>{report.months.map(m=>{const end=new Date(Date.UTC(Number(m.month_start.slice(0,4)),Number(m.month_start.slice(5,7)),0)).toISOString().slice(0,10);return <tr key={m.month_start}><th><Link href={href({from:m.month_start,to:end})}>{m.month_start.slice(0,7)}</Link></th><td>{money(m.revenue)}<div className={styles.bar} style={{width:`${Math.abs(m.revenue)/maxCost*100}%`}}/></td><td>{money(m.cost)}<div className={styles.bar} style={{width:`${Math.abs(m.cost)/maxCost*100}%`,background:'#94a3b8'}}/></td><td className={m.result<0?styles.negative:''}>{money(m.result)}</td></tr>})}</tbody></table></div>{!report.months.length&&<p>Inga importerade NeXT-poster för urvalet.</p>}</section>
  <section className="panel" id="projektlista"><h2>Projekt med bokförda poster ({visible.length})</h2><p className={styles.note}>Klicka på projekt eller belopp för att se underlaget. Projekt utan poster i perioden visas inte i listan. Sökningen begränsar listan; totalsummorna följer period, KST och projektledare.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Projekt</th><th>KST</th><th>Projektledare / grupp</th><th>Intäkter</th><th>Kostnader</th><th>Resultat</th><th>Marginal</th><th>Personal</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><th><Link href={href({project:p.id,kind:null})}>{p.project_number} · {p.project_name}</Link></th><td>{p.cost_center}</td><td>{p.project_manager}<br/><small>{p.business_group??'—'}</small></td><td className={styles.number}><Link href={href({project:p.id,kind:'revenue'})}>{money(p.revenue)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'cost'})}>{money(p.cost)}</Link></td><td className={`${styles.number} ${p.result<0?styles.negative:''}`}><Link href={href({project:p.id,kind:null})}>{money(p.result)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:null})}>{percent(p.margin)}</Link></td><td className={styles.number}><Link href={href({project:p.id,kind:'cost'})}>{money(p.personnel)}</Link></td></tr>)}</tbody></table></div></section>
  {project&&<section className="panel" id="underlag"><h2>NeXT-underlag · {report.transaction_count} poster</h2><nav className={styles.pager}><Link href={href({kind:null})}>Alla poster</Link><Link href={href({kind:'revenue'})}>Intäkter</Link><Link href={href({kind:'cost'})}>Kostnader</Link></nav><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Datum</th><th>Typ</th><th>Belopp</th><th>Konto / kategori</th><th>Beskrivning</th><th>Källfil / rad</th></tr></thead><tbody>{report.transactions.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.kind==='revenue'?'Intäkt':'Kostnad'}{t.internal?' · intern':''}</td><td className={styles.number}>{money(t.amount)}</td><td>{t.account}<br/>{categories[t.category]??t.category}</td><td>{t.description}{t.validation_errors.length>0&&<small className={styles.muted}><br/>Fordonsfördelning kvarstår; ingår på projektet.</small>}</td><td>{t.file_name}<br/>Rad {t.row_number}</td></tr>)}</tbody></table></div><nav className={styles.pager}>{page>0&&<Link href={href({page:String(page-1)})}>← Föregående</Link>}<span>Sida {page+1} · högst 200 poster per sida</span>{(page+1)*200<report.transaction_count&&<Link href={href({page:String(page+1)})}>Nästa →</Link>}</nav><p className={styles.note}>Budget och slutprognos kräver kalkyl och återstående arbete. Här visas enbart importerat bokfört utfall.</p></section>}
 {selected&&<ProjectInternalEvidence key={`${from}:${to}:${project}`} from={from} to={to} project={selected.id}/>}
 </div></KpiDetailShell>;
}
