import {Suspense} from 'react';
import {KpiMonthPeriod} from '@/app/_components/kpi-month-period';
import {parseProjectPeriod,projectPeriodParams,projectReportHref,type ProjectPeriod} from '@/lib/kpi/project-period';
import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {KpiDetailShell} from '@/app/_components/kpi-detail-shell';
import {ProjectInternalEvidence} from '@/app/_components/project-internal-evidence';
import {ProjectCostCenterSelect} from '@/app/_components/project-cost-center-select';
import {ProjectReportExport} from '@/app/_components/project-report-export';
import {ProjectReportLoading} from '@/app/_components/project-report-loading';
import type {ProjectReport} from '@/lib/hub/project-report';
import styles from './project-report.module.css';
export const dynamic='force-dynamic';
export const maxDuration=60;
const money=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(v);
const percent=(v:number|null)=>v===null?'—':new Intl.NumberFormat('sv-SE',{maximumFractionDigits:1}).format(v)+' %';
const categories:Record<string,string>={personnel:'Personal',material:'Material',tipp_deponi:'Tipp/deponi',hired:'Inhyrda / UE',fuel:'Bränsle',fixed:'Fasta',service_repair:'Service och reparation',other:'Övrigt',unclassified:'Ej kategoriserat'};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await db.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();
 const {data:allowed}=member?await db.rpc('hub_has_permission',{p_tenant_id:member.tenant_id,p_permission:'kpi.read'}):{data:false};
 if(!member||!allowed)return <main><h1>Du saknar behörighet till projektuppföljningen.</h1></main>;
 const raw=await searchParams,q=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Array.isArray(v)?v[0]:v])),groups=[...new Set((Array.isArray(raw.group)?raw.group:raw.group?[raw.group]:[]).filter(Boolean))];
 let selection:ProjectPeriod;
 try{selection=parseProjectPeriod(q);}catch{return <main className="content"><h1>Ogiltig period</h1><Link prefetch={false} href="/kpi/projekt">Återställ urval</Link></main>;}
 const center=q.center||null,manager=q.manager||null,project=q.project||null,page=Number(q.page??0),kind=q.kind||null;
 if(!Number.isInteger(page)||page<0||page>10000||groups.length>50||center&&!['10','20','30','40','50','60','90'].includes(center)||kind&&!['revenue','cost'].includes(kind)||project&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(project))return <main className="content"><h1>Ogiltigt projekturval</h1><Link prefetch={false} href="/kpi/projekt">Återställ urval</Link></main>;
 const query=projectPeriodParams(selection);
 for(const [k,v] of Object.entries({center,manager,project,kind,search:q.search}))if(v)query.set(k,v);
 for(const g of groups)query.append('group',g);
 const firstMonth=selection.from.slice(0,7)+'-01',lastDay=new Date(Date.UTC(Number(firstMonth.slice(0,4)),Number(firstMonth.slice(5,7)),0)).toISOString().slice(0,10);
 const monthHref=projectReportHref(query,{from:firstMonth,to:lastDay});
 return <KpiDetailShell query="" title="Projektuppföljning" breadcrumb="Humla Dashboard / Projekt" extraNavigation={<><Link href="/kpi/kontrollpanel" prefetch={false}>Kontrollpanel</Link><Link href="/kpi?view=internal" prefetch={false}>Interna körningar</Link></>}>
  {selection.custom&&<p className="panel">Eget datumintervall: {selection.from}–{selection.to}. Månadsval nedan ersätter intervallet med hela månader.</p>}
  <KpiMonthPeriod period={selection.period} costCenter="" costCenters={[]} pathname="/kpi/projekt" showFilters={false}/>
  <Suspense key={query.toString()+':'+page} fallback={<ProjectReportLoading monthHref={monthHref}/>}>
   <ProjectReportBody db={db} tenant={member.tenant_id} selection={selection} query={query.toString()} q={q} groups={groups} center={center} manager={manager} project={project} page={page} kind={kind}/>
  </Suspense>
 </KpiDetailShell>;
}
async function ProjectReportBody({db,tenant,selection,query,q,groups,center,manager,project,page,kind}:{db:Awaited<ReturnType<typeof createClient>>;tenant:string;selection:ProjectPeriod;query:string;q:Record<string,string|undefined>;groups:string[];center:string|null;manager:string|null;project:string|null;page:number;kind:string|null}){
 const {from,to,months}=selection;
 const {data,error}=await db.rpc('hub_kpi_project_report_v5',{p_tenant_id:tenant,p_from:from,p_to:to,p_center:center,p_manager:manager,p_project:project,p_page:page,p_kind:kind,p_groups:groups.length?groups:null,p_months:months}).abortSignal(AbortSignal.timeout(48_000));
 const href=(changes:Record<string,string|null>)=>projectReportHref(new URLSearchParams(query),changes);
 if(error||!data)return <section className="panel" role="alert"><h2>Projektunderlaget kunde inte hämtas</h2><p>Inga belopp visas när underlaget inte kan läsas. Välj en kortare period ovan eller försök igen.</p><Link prefetch={false} href={href({})}>Försök igen</Link></section>;
 const report=data as ProjectReport,selected=report.projects.find(p=>p.id===project),visible=report.projects.filter(p=>p.rows>0&&(!q.search||[p.project_number,p.project_name,p.project_manager,p.business_group].join(' ').toLocaleLowerCase('sv-SE').includes(q.search.toLocaleLowerCase('sv-SE'))));
 const groupOptions=report.available_groups;
 const inactiveGroups=groups.filter(g=>!groupOptions.includes(g));
 const maxCost=Math.max(1,...report.months.map(m=>Math.max(Math.abs(m.revenue),Math.abs(m.cost))));
 return <div className={styles.content}>
  <section className="panel"><h2>{selected?`${selected.project_number} · ${selected.project_name}`:'Projekt — alla kostnadsställen'}</h2><p className={styles.note}>{report.scope} Personal ingår en gång i kostnader och resultat. NeXT används för övriga kostnadsställen; Transport använder TransPA via API. Externa intäkter för Sortergård och Transport hämtas från Workify.</p>
   <form className={styles.filters} key={JSON.stringify([from,to,months,center,manager,groups,project])}>{Array.from(projectPeriodParams(selection)).map(([key,value])=><input type="hidden" key={key} name={key} value={value}/>)} <ProjectCostCenterSelect value={center}/><label>Projektledare<select name="manager" defaultValue={manager??''}><option value="">Alla projektledare</option>{report.managers.map(m=><option key={m} value={m}>{m}</option>)}</select></label><fieldset className={styles.groupFilter}><legend>Verksamhetsgrupper</legend><div className={styles.groupChoices}>{groupOptions.map(g=><label key={g}><input type="checkbox" name="group" value={g} defaultChecked={groups.includes(g)}/>{g}</label>)}</div>{!groupOptions.length&&<p>Inga verksamhetsgrupper har belopp i urvalet.</p>}{inactiveGroups.length>0&&<p>Valda grupper utan belopp i urvalet: {inactiveGroups.join(', ')}.{inactiveGroups.map(g=><input type="hidden" key={g} name="group" value={g}/>)}</p>}<small>Visar grupper med intäkter eller kostnader i valt KST, period och projektledarurval. Inga kryss = alla grupper.</small> <Link prefetch={false} href={href({group:null,project:null,kind:null})}>Visa alla grupper</Link></fieldset><label>Sök i projektlistan<input name="search" defaultValue={q.search??''} placeholder="Projektnummer, namn eller grupp"/></label>{project&&<input type="hidden" name="project" value={project}/>}<button className="primary">Visa urval</button><Link prefetch={false} href={href({project:null,kind:null})}>Alla projekt i urvalet</Link></form>
   <p className={styles.note}>Senaste NeXT-bokföringsdatum i underlaget: {report.latest_source_date??'Underlag saknas'}. {report.excluded_rows} felaktiga poster undantagna. {report.summary.vehicle_allocation_pending??0} poster väntar på fordonsfördelning men ingår på säkert identifierat projekt. {report.hub_unmapped_rows} Workify/TransPA-rader saknar entydigt registerprojekt och är undantagna. {report.summary.unclassified_rows??0} kostnadsrader saknar kategori men ingår i kostnaden.</p><ProjectReportExport report={report}/>
  </section>
  <div className={styles.cards}>{[['Intäkter',money(report.summary.revenue)],['Kostnader',money(report.summary.cost)],['Resultat',money(report.summary.result)],['Projektmarginal',percent(report.summary.margin)],['Personal (ingår i kostnad)',money(report.summary.personnel)]].map(([label,value])=><a className={styles.card} key={label} href={project?'#underlag':'#projektlista'}><small>{label}</small><strong>{value}</strong></a>)}</div>
  <section className="panel"><h2>Avstämning mot underlag</h2><p className={styles.note}>Källornas belopp nedan ingår i valt projekturval. Intern Workify-kostnad visar endast tillägget efter avräkning mot 4600. Alla belopp är exklusive moms.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Källa</th><th>Typ</th><th>Rader</th><th>Belopp som ingår</th></tr></thead><tbody>{report.reconciliation.sources.map(t=><tr key={`${t.source}:${t.kind}`}><th>{t.source}</th><td>{t.kind==='cost'?'Kostnad':'Intäkt'}</td><td>{t.rows}</td><td>{money(t.amount)}</td></tr>)}</tbody></table></div>
   {(report.reconciliation.unassigned_next.rows>0||report.reconciliation.unassigned_hub.rows>0)&&<div role="note"><h3>Underlaget är inte komplett projektfördelat</h3><p>NeXT: {report.reconciliation.unassigned_next.rows} rader på {report.reconciliation.unassigned_next.projects} projekt saknar säker koppling i det aktiva projektregistret. Kostnader {money(report.reconciliation.unassigned_next.cost)}, intäkter {money(report.reconciliation.unassigned_next.revenue)}. Gäller hela arbetsytan i vald period, även om ett KST eller projekt är valt. Beloppen ingår inte i totalsummorna.</p><p>Workify/TransPA inom aktuellt KST- och projektledarurval: {report.reconciliation.unassigned_hub.rows} rader kan inte hänföras till ett entydigt registerprojekt. Kostnader {money(report.reconciliation.unassigned_hub.cost)}, intäkter {money(report.reconciliation.unassigned_hub.revenue)}. Ingår inte heller i totalsummorna.</p><details><summary>Visa upp till 20 största NeXT-projekt som saknas</summary><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Projekt i underlaget</th><th>Rader</th><th>Kostnader (ingår inte)</th><th>Intäkter (ingår inte)</th></tr></thead><tbody>{report.reconciliation.unassigned_next.details.map(t=><tr key={t.project_number??'missing'}><th>{t.project_number||'Saknas'}</th><td>{t.rows}</td><td>{money(t.cost)}</td><td>{money(t.revenue)}</td></tr>)}</tbody></table></div></details><p>Komplettera projektregistret eller verifiera kopplingarna i <Link href="/kpi/kontrollpanel" prefetch={false}>Kontrollpanelen</Link>. Resultatet avser de kopplade projekten, inte ett komplett företagsresultat.</p></div>}
  </section>
  <section className="panel"><h2>Externa och interna poster</h2><p className={styles.note}>NeXT-kostnader och projektintäkter ingår en gång. För KST 20/30 används externa Workify-intäkter i stället för NeXT-intäkter. Interna Workify-körningar är kostnad på mottagande projekt och intäkt på utförande projekt. Mottagarens Workify-belopp räknas av mot redan bokfört på 4600 inom valt projekt och period. Resterande belopp läggs till kostnaden. Interna belopp nedan ingår redan i totalsummorna.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Extern intäkt</th><th>Intern intäkt</th><th>Extern kostnad</th><th>Intern kostnad</th></tr></thead><tbody><tr>{[report.summary.external_revenue,report.summary.internal_revenue,report.summary.external_cost,report.summary.internal_cost].map((v,i)=><td key={i}>{money(v)}</td>)}</tr></tbody></table></div></section>
  <section className="panel"><h2>Interna Workify-belopp i resultatet</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Workify-kostnad, mottagande projekt</th><th>Bokfört på 4600</th><th>Avräknat mot 4600</th><th>Tillägg till kostnaden</th><th>Intern intäkt, utförande projekt</th></tr></thead><tbody><tr>{[report.internal_workify.original,report.internal_workify.booked_4600,report.internal_workify.covered_4600,report.internal_workify.added,report.internal_workify.income].map((v,i)=><td key={i}>{money(v)}</td>)}</tr></tbody></table></div><p className={styles.note}>Intäkter och kostnader ovan ingår redan i resultatet. Intern intäkt kräver en entydig koppling till utförande projekt; kopplingarna hanteras i Kontrollpanelen. {report.internal_workify.rows} interna kostnadsrader och {report.internal_workify.income_rows} intäktsrader. {report.internal_workify.pending_rows} mottagarrader väntar på fakturering eller granskning och ingår ännu inte. Avräkningen mot 4600 görs på projektsumman inom vald period; raden i detaljunderlaget visar det proportionellt fördelade kostnadstillägget. Interna belopp är inte eliminerade mellan kostnadsställen i denna projektvy.</p></section>
  <section className="panel"><h2>Utveckling per månad</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Månad</th><th>Intäkter</th><th>Kostnader</th><th>Resultat</th></tr></thead><tbody>{report.months.map(m=>{const end=new Date(Date.UTC(Number(m.month_start.slice(0,4)),Number(m.month_start.slice(5,7)),0)).toISOString().slice(0,10);return <tr key={m.month_start}><th><Link prefetch={false} href={href({from:m.month_start,to:end})}>{m.month_start.slice(0,7)}</Link></th><td>{money(m.revenue)}<div className={styles.bar} style={{width:`${Math.abs(m.revenue)/maxCost*100}%`}}/></td><td>{money(m.cost)}<div className={styles.bar} style={{width:`${Math.abs(m.cost)/maxCost*100}%`,background:'#94a3b8'}}/></td><td className={m.result<0?styles.negative:''}>{money(m.result)}</td></tr>})}</tbody></table></div>{!report.months.length&&<p>Inga importerade poster för urvalet.</p>}</section>
  <section className="panel" id="projektlista"><h2>Projekt med underlag ({visible.length})</h2><p className={styles.note}>Klicka på projekt eller belopp för att se underlaget. Projekt utan poster i perioden visas inte i listan. Sökningen begränsar listan; totalsummorna följer period, KST, projektledare och verksamhetsgrupp.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Projekt</th><th>KST</th><th>Projektledare / grupp</th><th>Intäkter</th><th>Kostnader</th><th>Intern intäkt (ingår)</th><th>Intern kostnad (ingår)</th><th>Resultat</th><th>Marginal</th><th>Personal</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><th><Link prefetch={false} href={href({project:p.id,kind:null})}>{p.project_number} · {p.project_name}</Link></th><td>{p.cost_center}</td><td>{p.project_manager}<br/><small>{p.business_group??'—'}</small></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:'revenue'})}>{money(p.revenue)}</Link></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:'cost'})}>{money(p.cost)}</Link></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:'revenue'})}>{money(p.internal_revenue)}</Link></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:'cost'})}>{money(p.internal_cost)}</Link></td><td className={`${styles.number} ${p.result<0?styles.negative:''}`}><Link prefetch={false} href={href({project:p.id,kind:null})}>{money(p.result)}</Link></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:null})}>{percent(p.margin)}</Link></td><td className={styles.number}><Link prefetch={false} href={href({project:p.id,kind:'cost'})}>{money(p.personnel)}</Link></td></tr>)}</tbody></table></div></section>
  {project&&<section className="panel" id="underlag"><h2>Projektunderlag · {report.transaction_count} poster</h2><nav className={styles.pager}><Link prefetch={false} href={href({kind:null})}>Alla poster</Link><Link prefetch={false} href={href({kind:'revenue'})}>Intäkter</Link><Link prefetch={false} href={href({kind:'cost'})}>Kostnader</Link></nav><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Datum</th><th>Typ</th><th>Belopp</th><th>Konto / kategori</th><th>Beskrivning</th><th>Källa / fil / rad</th></tr></thead><tbody>{report.transactions.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.kind==='revenue'?'Intäkt':'Kostnad'}{t.internal?' · intern':''}</td><td className={styles.number}>{money(t.amount)}</td><td>{t.account}<br/>{categories[t.category]??t.category}</td><td>{t.description}{t.validation_errors.length>0&&<small className={styles.muted}><br/>Fordonsfördelning kvarstår; ingår på projektet.</small>}</td><td>{t.source}<br/>{t.file_name}{t.row_number!=null&&<><br/>Rad {t.row_number}</>}</td></tr>)}</tbody></table></div><nav className={styles.pager}>{page>0&&<Link prefetch={false} href={href({page:String(page-1)})}>← Föregående</Link>}<span>Sida {page+1} · högst 200 poster per sida</span>{(page+1)*200<report.transaction_count&&<Link prefetch={false} href={href({page:String(page+1)})}>Nästa →</Link>}</nav><p className={styles.note}>Budget och slutprognos kräver kalkyl och återstående arbete. Här visas importerat utfall och, för Transport, beräknad personal från TransPA.</p></section>}
 {selected&&<ProjectInternalEvidence key={JSON.stringify([from,to,months,project])} from={from} to={to} months={months} project={selected.id}/>}
 </div>;
}
