import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.57.4";
const TENANT="944597b6-9c46-4bef-998d-f19e23c4245b", CONNECTION="6f59f8bd-155b-43c8-8af7-331d502ca16b", VISMA_TENANT="b2c04564-de69-4dad-8fcb-e7c14557c21d";
const SCOPES=["transpaapi:api","transpaapi:employeecontracts:read","transpaapi:employees:read","transpaapi:employeesalaryconfigurations:read","transpaapi:files:read","transpaapi:salaries:read","transpaapi:shifts:read","transpaapi:stationplaces:read","transpaapi:tachographdata:read","transpaapi:timereportconfigurations:read","transpaapi:timereports:read","transpaapi:trips:read","transpaapi:vehiclegroups:read","transpaapi:vehicles:read","transpaapi:workgroups:read","transpaapi:worktasks:read"];
Deno.serve(async(req)=>{try{
 const url=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,pub=createClient(url,service),priv=createClient(url,service,{db:{schema:"hub_private"}});
 const input=await req.json().catch(()=>({})); const {data:wref}=await pub.from("hub_secret_references").select("vault_secret_id").eq("credential_name","worker_key").maybeSingle();
 let expected=""; if(wref?.vault_secret_id){const x=await pub.rpc("hub_internal_vault_secret_v1",{p_secret_id:wref.vault_secret_id});expected=String(x.data||"")} else {const {data:x}=await pub.rpc("hub_get_worker_key_for_internal_use");expected=String(x||"")}
 if(!expected||String(input.worker_key||"")!==expected)return new Response('{"ok":false,"error":"unauthorized"}',{status:401,headers:{"content-type":"application/json"}});
 const {data:refs,error:re}=await pub.from("hub_secret_references").select("credential_name,vault_secret_id").eq("tenant_id",TENANT).eq("connection_id",CONNECTION).eq("status","configured");if(re)throw re;
 const get=async(n:string)=>{const r=refs?.find((x:any)=>x.credential_name===n);if(!r)throw new Error("missing_"+n);const x=await pub.rpc("hub_internal_vault_secret_v1",{p_secret_id:r.vault_secret_id});if(x.error)throw x.error;return String(x.data)};
 const body=new URLSearchParams({grant_type:"client_credentials",scope:SCOPES.join(" "),client_id:await get("client_id"),client_secret:await get("client_secret"),tenant_id:VISMA_TENANT});
 const tr=await fetch("https://connect.visma.com/connect/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});const tj=await tr.json().catch(()=>({}));
 if(!tr.ok)return new Response(JSON.stringify({ok:false,stage:"oauth",status:tr.status,error:tj.error,error_description:tj.error_description}),{status:502,headers:{"content-type":"application/json"}});
 const dateFrom=String(input.from||""),dateTo=String(input.to||"");
 const requiresDates=Array.isArray(input.entities)&&input.entities.includes("timeReports");
 if(requiresDates&&(!Number.isFinite(Date.parse(dateFrom))||!Number.isFinite(Date.parse(dateTo))||Date.parse(dateTo)<=Date.parse(dateFrom)||Date.parse(dateTo)-Date.parse(dateFrom)>31*86400000))return new Response('{"ok":false,"error":"timeReports requires from/to within 31 days"}',{status:400});
 const requested=Array.isArray(input.entities)?input.entities:["vehicles","employees","workTasks","vehicleGroups","stationPlaces","trips"];
 const allowed=new Set(["vehicles","employees","workTasks","vehicleGroups","stationPlaces","trips","shifts","timeReports","employeeContracts","employeeSalaryConfigurations","tachographData"]);
 const typeMap:any={vehicles:"vehicle",employees:"employee",workTasks:"work_task",vehicleGroups:"vehicle_group",stationPlaces:"station_place",trips:"trip",shifts:"shift",timeReports:"time_report",employeeContracts:"employee_contract",employeeSalaryConfigurations:"employee_salary_configuration",tachographData:"tachograph_data"};
 const jobs:any[]=[];
 for(const ep of requested){
 if(ep==="employeeSalaryConfigurations"||ep==="employeeContracts"){
 const {data:employees,error}=await pub.from("hub_transpa_entities").select("external_id").eq("tenant_id",TENANT).eq("connection_id",CONNECTION).eq("entity_type","employee").order("external_id").limit(1000);
 if(error)throw error;
 const limit=Math.min(1000,Math.max(1,Number(input.employee_limit)||1000));
 for(const e of (employees||[]).slice(0,limit))jobs.push({ep,path:ep==="employeeSalaryConfigurations"?"employees/"+encodeURIComponent(e.external_id)+"/salaryConfiguration":"employee/"+encodeURIComponent(e.external_id)+"/employeeContracts",employeeId:e.external_id,key:ep+":"+e.external_id});
 }else jobs.push({ep,path:ep,key:ep});
 }
 const summary:any={}; const run=await pub.from("hub_transpa_sync_runs").insert({tenant_id:TENANT,connection_id:CONNECTION,status:"running",entity_types:requested}).select("id").single(); let fetched=0,upserted=0,errors=0;
 for(const job of jobs){const ep=job.ep;if(!allowed.has(ep))continue;let cursor:string|null=null,count=0,pages=0;try{do{const u=new URL("https://api.mytranspa.com/publicApi/v1/"+job.path);u.searchParams.set("limit","50");if(ep==="timeReports"){u.searchParams.set("startDateTimeAfter",dateFrom);u.searchParams.set("startDateTimeBefore",dateTo);}if(cursor)u.searchParams.set("cursor",cursor);const rr=await fetch(u,{headers:{Authorization:"Bearer "+tj.access_token,Accept:"application/json"}});const jj=await rr.json().catch(()=>null);if(!rr.ok){summary[job.key]={ok:false,status:rr.status,error:"upstream_request_failed"};errors++;break}const items=ep==="employeeSalaryConfigurations"&&jj?[{...jj,employeeId:job.employeeId}]:Array.isArray(jj)?jj:(Array.isArray(jj?.items)?jj.items:Array.isArray(jj?.data)?jj.data:Array.isArray(jj?.results)?jj.results:[]);for(const v of items){const eid=String(v?.id??v?.tripId??v?.employeeId??v?.vehicleId??v?.registrationNumber??v?.code??"");if(!eid)continue;const payload=JSON.stringify(v);const wr=await pub.from("hub_transpa_entities").upsert({tenant_id:TENANT,connection_id:CONNECTION,entity_type:typeMap[ep],external_id:eid,payload:v,payload_hash:payload,last_seen_at:new Date().toISOString()},{onConflict:"tenant_id,connection_id,entity_type,external_id"});if(wr.error)throw new Error("entity_write_failed");upserted++;}count+=items.length;fetched+=items.length;pages++;cursor=jj?.cursor?.nextToken??null;if(pages>=Math.min(100,Math.max(1,Number(input.max_pages)||100))&&cursor){summary[job.key]={ok:false,count,pages,resume_cursor:cursor,error:"page_limit_reached"};errors++;cursor=null;}}while(cursor);if(!summary[job.key])summary[job.key]={ok:true,count,pages};}catch(e){summary[job.key]={ok:false,error:e instanceof Error?e.message:"unknown"};errors++;}}
 if(run.data?.id)await pub.from("hub_transpa_sync_runs").update({status:errors?"partial":"completed",completed_at:new Date().toISOString(),fetched_count:fetched,upserted_count:upserted,error_count:errors,details:summary}).eq("id",run.data.id);
 await pub.from("hub_connections").update({status:"active"}).eq("id",CONNECTION);
 return new Response(JSON.stringify({ok:errors===0,stage:"sync",oauth_ok:true,expires_in:tj.expires_in,fetched,upserted,errors,entities:summary}),{headers:{"content-type":"application/json"}});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:"unknown"}),{status:500,headers:{"content-type":"application/json"}})}});
