import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {DistanceImport} from '@/app/_components/distance-import';
export const dynamic='force-dynamic';
type Row={registration:string;distance_mil:number|null;cost_per_mil:number|null;revenue_per_mil:number|null;basis:string};
const num=new Intl.NumberFormat('sv-SE',{maximumFractionDigits:2});
export default async function Page({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/kpi/login');
 const {data:member}=await s.from('hub_tenant_members').select('tenant_id').eq('user_id',user.id).eq('status','active').maybeSingle();if(!member)redirect('/kpi');
 const q=await searchParams;const now=new Date().toISOString().slice(0,10);const from=/^\d{4}-\d{2}-\d{2}$/.test(q.from??'')?q.from!:now.slice(0,8)+'01';const to=/^\d{4}-\d{2}-\d{2}$/.test(q.to??'')?q.to!:now;
 const [{data:report,error},{data:manage},{data:reviews}]=await Promise.all([s.rpc('hub_kpi_distance_report_v1',{p_tenant_id:member.tenant_id,p_from:from,p_to:to}),s.rpc('hub_has_permission',{p_tenant_id:member.tenant_id,p_permission:'kpi.manage'}),s.from('hub_review_queue').select('id,payload').eq('tenant_id',member.tenant_id).eq('review_type','kpi_distance_import').eq('status','open').order('created_at',{ascending:false}).limit(100)]);
 return <main className="content"><a href={`/kpi?from=${from}&to=${to}&view=kpi`}>← KPI Dashboard</a><h1>Körsträcka och kostnad per mil</h1><form><label>Från <input type="date" name="from" defaultValue={from}/></label><label>Till <input type="date" name="to" defaultValue={to}/></label><button>Visa period</button></form><p>Hubben beräknar kostnad och intäkt per mil från samma period. Körsträcka används först när hela perioden täcks. Kostnaden gäller det individuella fordonet; en sammansatt ekonomisk enhets kostnader ingår inte automatiskt.</p>{error?<p role="alert">Periodens underlag kunde inte läsas.</p>:<section className="panel"><div className="table-wrap"><table><thead><tr><th>Fordon</th><th>Körda mil</th><th>Kostnad / mil</th><th>Intäkt / mil</th><th>Underlag</th></tr></thead><tbody>{(report?.vehicles??[]).map((r:Row)=><tr key={r.registration}><td><a href={`/kpi/analys?from=${from}&to=${to}&vehicle=${encodeURIComponent(r.registration)}&level=project`}>{r.registration}</a></td><td>{r.distance_mil==null?'Saknar körsträcka':num.format(r.distance_mil)}</td><td>{r.cost_per_mil==null?'–':num.format(r.cost_per_mil)+' kr'}</td><td>{r.revenue_per_mil==null?'–':num.format(r.revenue_per_mil)+' kr'}</td><td>{r.basis==='period_import'?'Importerad periodsträcka':r.basis==='missing'?'Inväntar komplett period':'Fordonskontrollen: mätarhistorik'}</td></tr>)}</tbody></table></div></section>}{manage&&<DistanceImport/>}{Boolean(reviews?.length)&&<section className="panel"><h2>Körsträckor som behöver granskas</h2><p>Dessa rader påverkar inte KPI. Kontrollera regnummer och period i originalunderlaget före en korrigerad import.</p><table><thead><tr><th>Rad</th><th>Regnummer</th><th>Period</th><th>Orsak</th></tr></thead><tbody>{reviews?.map(r=><tr key={r.id}><td>{r.payload?.row}</td><td>{r.payload?.record?.registration}</td><td>{r.payload?.record?.from} – {r.payload?.record?.to}</td><td>{r.payload?.reason}</td></tr>)}</tbody></table></section>}{manage&&<p><a href="/integrationer/fordon-maskiner">Hämta mätarhistorik från Fordonskontrollen →</a></p>}</main>;
}
